static void ReportBogrootDungeonLoopTelemetry(const Bot::Froggy::DungeonLoopTelemetry& telemetry) {
    FroggyFeatureReport("  Bogroot loop telemetry: startLvl1=%d startLvl2=%d enteredLvl2=%d lvl1ToLvl2Started=%d lvl1ToLvl2Attempts=%u lastWp=%u(%s) wpIters=%u bossStarted=%d bossCompleted=%d chestAttempts=%u chestSuccesses=%u rewardAttempted=%d rewardLatched=%d lastDialog=0x%X finalMap=%u returnedToSparkfly=%d loaded=%d alive=%d hp=%.3f pos=(%.0f, %.0f) target=%u distToExit=%.0f nearestEnemy=%.0f nearbyEnemies=%u portal=%u portalPos=(%.0f, %.0f) portalDist=%.0f",
              telemetry.started_in_lvl1 ? 1 : 0,
              telemetry.started_in_lvl2 ? 1 : 0,
              telemetry.entered_lvl2 ? 1 : 0,
              telemetry.lvl1_to_lvl2_started ? 1 : 0,
              telemetry.lvl1_to_lvl2_attempts,
              telemetry.last_waypoint_index,
              telemetry.last_waypoint_label,
              telemetry.waypoint_iterations,
              telemetry.boss_started ? 1 : 0,
              telemetry.boss_completed ? 1 : 0,
              telemetry.chest_attempts,
              telemetry.chest_successes,
              telemetry.reward_attempted ? 1 : 0,
              telemetry.reward_dialog_latched ? 1 : 0,
              telemetry.last_dialog_id,
              telemetry.final_map_id,
              telemetry.returned_to_sparkfly ? 1 : 0,
              telemetry.map_loaded ? 1 : 0,
              telemetry.player_alive ? 1 : 0,
              telemetry.player_hp,
              telemetry.player_x,
              telemetry.player_y,
              telemetry.target_id,
              telemetry.dist_to_exit,
              telemetry.nearest_enemy_dist,
              telemetry.nearby_enemy_count,
              telemetry.lvl1_portal_id,
              telemetry.lvl1_portal_x,
              telemetry.lvl1_portal_y,
              telemetry.lvl1_portal_dist);
}
