#include "IntegrationTestFroggyFeatureCombatAgentReadTypes.h"
#include "IntegrationTestFroggyFeatureCombatAgentReadCapture.h"
#include "IntegrationTestFroggyFeatureCombatAgentReadValidationHelpers.h"
#include "IntegrationTestFroggyFeatureCombatAgentReadReport.h"
