#include "IntegrationTestFroggyFeatureBuiltinCombatTraceReports.h"
#include "IntegrationTestFroggyFeatureBuiltinCombatSignalTypes.h"
#include "IntegrationTestFroggyFeatureBuiltinCombatSignalEvaluation.h"
#include "IntegrationTestFroggyFeatureBuiltinCombatSignalObserver.h"
