#include "IntegrationTestFroggyFeatureBuiltinCombatProofFoeSelection.h"
#include "IntegrationTestFroggyFeatureBuiltinCombatSpiritFoeSelection.h"
#include "IntegrationTestFroggyFeatureBuiltinCombatProofSuiteEntry.h"
