#CS ===========================================================================
; Author: caustic-kronos (aka Kronos, Night, Svarog), Greg-76, KleuTSchi
; Contributor: Gahais
; Copyright 2025 caustic-kronos
;
; Licensed under the Apache License, Version 2.0 (the 'License');
; you may not use this file except in compliance with the License.
; You may obtain a copy of the License at
; http://www.apache.org/licenses/LICENSE-2.0
;
; Unless required by applicable law or agreed to in writing, software
; distributed under the License is distributed on an 'AS IS' BASIS,
; WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
; See the License for the specific language governing permissions and
; limitations under the License.
#CE ===========================================================================

#include-once
#include <Array.au3>
#include 'Utils.au3'


#Region MapTypes
Global Const $ID_OUTPOST	= 0
Global Const $ID_EXPLORABLE	= 1
Global Const $ID_LOADING	= 2
#EndRegion MapTypes


#Region Map Campaign
Global Const $ID_CAMPAIGN_CORE = 0
Global Const $ID_CAMPAIGN_PROPHECIES = 1
Global Const $ID_CAMPAIGN_FACTIONS = 2
Global Const $ID_CAMPAIGN_NIGHTFALL = 3
Global Const $ID_CAMPAIGN_EOTN = 4
Global Const $ID_CAMPAIGN_BONUSPACK = 5
#EndRegion Map Campaign


#Region Map Continent
Global Const $ID_Continent_Kryta = 0
Global Const $ID_Continent_DevContinent = 1
Global Const $ID_Continent_Cantha = 2
Global Const $ID_Continent_BattleIsles = 3
Global Const $ID_Continent_Elona = 4
Global Const $ID_Continent_RealmOfTorment = 5
#EndRegion Map Continent

#Region Region Type
Global Const $ID_REGIONTYPE_ALLIANCEBATTLE = 0
Global Const $ID_REGIONTYPE_ARENA = 1
Global Const $ID_REGIONTYPE_EXPLORABLEZONE = 2
Global Const $ID_REGIONTYPE_GUILDBATTLEAREA = 3
Global Const $ID_REGIONTYPE_GUILDHALL = 4
Global Const $ID_REGIONTYPE_MISSIONOUTPOST = 5
Global Const $ID_REGIONTYPE_COOPERATIVEMISSION = 6
Global Const $ID_REGIONTYPE_COMPETITIVEMISSION = 7
Global Const $ID_REGIONTYPE_ELITEMISSION = 8
Global Const $ID_REGIONTYPE_CHALLENGE = 9
Global Const $ID_REGIONTYPE_OUTPOST = 10
Global Const $ID_REGIONTYPE_ZAISHENBATTLE = 11
Global Const $ID_REGIONTYPE_HEROESASCENT = 12
Global Const $ID_REGIONTYPE_CITY = 13
Global Const $ID_REGIONTYPE_MISSIONAREA = 14
Global Const $ID_REGIONTYPE_HEROBATTLEOUTPOST = 15
Global Const $ID_REGIONTYPE_HEROBATTLEAREA = 16
Global Const $ID_REGIONTYPE_EOTNMISSION = 17
Global Const $ID_REGIONTYPE_DUNGEON = 18
Global Const $ID_REGIONTYPE_MARKETPLACE = 19
Global Const $ID_REGIONTYPE_UNKNOWN = 20
Global Const $ID_REGIONTYPE_DEVREGION = 21
#EndRegion Region Type


#Region Region
Global Const $ID_REGION_KRYTA = 0
Global Const $ID_REGION_MAGUUMA = 1
Global Const $ID_REGION_ASCALON = 2
Global Const $ID_REGION_NORTHERNSHIVERPEAKS = 2
Global Const $ID_REGION_HEROESASCENT = 3
Global Const $ID_REGION_CRYSTALDESERT = 4
Global Const $ID_REGION_FISSUREOFWOE = 5
Global Const $ID_REGION_PRESEARING = 6
Global Const $ID_REGION_KAINENG = 7
Global Const $ID_REGION_KURZICK = 8
Global Const $ID_REGION_LUXON = 9
Global Const $ID_REGION_SHINGJEA = 10
Global Const $ID_REGION_KOURNA = 11
Global Const $ID_REGION_VAABI = 12
Global Const $ID_REGION_DESOLATION = 13
Global Const $ID_REGION_ISTAN = 14
Global Const $ID_REGION_DOMAINOFANGUISH = 15
Global Const $ID_REGION_TARNISHEDCOAST = 16
Global Const $ID_REGION_DEPTHSOFTYRIA = 17
Global Const $ID_REGION_FARSHIVERPEAKS = 18
Global Const $ID_REGION_CHARRHOMELANDS = 19
Global Const $ID_REGION_BATTLEISLANDS = 20
Global Const $ID_REGION_THEBATTLEOFJAHAI = 21
Global Const $ID_REGION_THEFLIGHTNORTH = 22
Global Const $ID_REGION_THETENGUACCORDS = 23
Global Const $ID_REGION_THERISEOFTHEWHITEMANTLE = 24
Global Const $ID_REGION_SWAT = 25
Global Const $ID_REGION_DEVREGION = 26
#EndRegion Region


#Region Map Location IDs
Global Const $ID_GLADIATORS_ARENA = 1
Global Const $ID_DEV_TEST_ARENA_1V1 = 2
Global Const $ID_TEST_MAP = 3
Global Const $ID_GUILD_HALL_WARRIORS_ISLE = 4
Global Const $ID_GUILD_HALL_HUNTERS_ISLE = 5
Global Const $ID_GUILD_HALL_WIZARDS_ISLE = 6
Global Const $ID_WARRIORS_ISLE_EXPLORABLE = 7
Global Const $ID_HUNTERS_ISLE_EXPLORABLE = 8
Global Const $ID_WIZARDS_ISLE_EXPLORABLE = 9
; Prophecies
Global Const $ID_BLOODSTONE_FEN = 10
Global Const $ID_THE_WILDS = 11
Global Const $ID_AURORA_GLADE = 12
Global Const $ID_DIESSA_LOWLANDS = 13
Global Const $ID_GATES_OF_KRYTA = 14
Global Const $ID_DALESSIO_SEABOARD = 15
Global Const $ID_DIVINITY_COAST = 16
Global Const $ID_TALMARK_WILDERNESS = 17
Global Const $ID_THE_BLACK_CURTAIN = 18
Global Const $ID_SANCTUM_CAY = 19
Global Const $ID_DROKNARS_FORGE_DEFAULT = 20
Global Const $ID_THE_FROST_GATE = 21
Global Const $ID_ICE_CAVES_OF_SORROW = 22
Global Const $ID_THUNDERHEAD_KEEP = 23
Global Const $ID_IRON_MINES_OF_MOLADUNE = 24
Global Const $ID_BORLIS_PASS = 25
Global Const $ID_TALUS_CHUTE = 26
Global Const $ID_GRIFFONS_MOUTH = 27
Global Const $ID_THE_GREAT_NORTHERN_WALL = 28
Global Const $ID_FORT_RANIK = 29
Global Const $ID_RUINS_OF_SURMIA = 30
Global Const $ID_XAQUANG_SKYWAY = 31
Global Const $ID_NOLANI_ACADEMY = 32
Global Const $ID_OLD_ASCALON = 33
Global Const $ID_THE_FISSURE_OF_WOE = 34
Global Const $ID_EMBER_LIGHT_CAMP = 35
Global Const $ID_GRENDICH_COURTHOUSE = 36
Global Const $ID_GLINTS_CHALLENGE = 37
Global Const $ID_AUGURY_ROCK = 38
Global Const $ID_SARDELAC_SANCTARIUM = 39
Global Const $ID_PIKEN_SQUARE = 40
Global Const $ID_SAGE_LANDS = 41
Global Const $ID_MAMNOON_LAGOON = 42
Global Const $ID_SILVERWOOD = 43
Global Const $ID_ETTINS_BACK = 44
Global Const $ID_REED_BOG = 45
Global Const $ID_THE_FALLS = 46
Global Const $ID_DRY_TOP = 47
Global Const $ID_TANGLE_ROOT = 48
Global Const $ID_HENGE_OF_DENRAVI = 49
Global Const $ID_TEST_MAP2 = 50
Global Const $ID_SENJIS_CORNER = 51
Global Const $ID_GUILD_HALL_BURNING_ISLE = 52
Global Const $ID_TEARS_OF_THE_FALLEN = 53
Global Const $ID_SCOUNDRELS_RISE = 54
Global Const $ID_LIONS_ARCH_DEFAULT = 55
Global Const $ID_CURSED_LANDS = 56
Global Const $ID_BERGEN_HOT_SPRINGS = 57
Global Const $ID_NORTH_KRYTA_PROVINCE = 58
Global Const $ID_NEBO_TERRACE = 59
Global Const $ID_MAJESTYS_REST = 60
Global Const $ID_TWIN_SERPENT_LAKES = 61
Global Const $ID_WATCHTOWER_COAST = 62
Global Const $ID_STINGRAY_STRAND = 63
Global Const $ID_KESSEX_PEAK = 64
Global Const $ID_DALESSIO_ARENA_1 = 65
Global Const $ID_ALLCALLCLICKPOINT1 = 66
Global Const $ID_BURNING_ISLE_EXPLORABLE = 67
Global Const $ID_FROZEN_ISLE_EXPLORABLE = 68
Global Const $ID_NOMADS_ISLE_EXPLORABLE = 69
Global Const $ID_DRUIDS_ISLE_EXPLORABLE = 70
Global Const $ID_ISLE_OF_THE_DEAD_EXPLORABLE = 71
Global Const $ID_THE_UNDERWORLD = 72
Global Const $ID_RIVERSIDE_PROVINCE = 73
Global Const $ID_TOURNAMENT6 = 74
Global Const $ID_THE_HALL_OF_HEROES_ARENA = 75
Global Const $ID_BROKEN_TOWER_ARENA = 76
Global Const $ID_HOUSE_ZU_HELTZER = 77
Global Const $ID_THE_COURTYARD_ARENA = 78
Global Const $ID_UNHOLY_TEMPLES_ARENA = 79
Global Const $ID_BURIAL_MOUNDS_ARENA = 80
Global Const $ID_ASCALON_CITY_DEFAULT = 81
Global Const $ID_TOMB_OF_THE_PRIMEVAL_KINGS_DEFAULT = 82
Global Const $ID_THE_VAULT_ARENA = 83
Global Const $ID_THE_UNDERWORLD_ARENA = 84
Global Const $ID_ASCALON_ARENA = 85
Global Const $ID_SACRED_TEMPLES_ARENA = 86
Global Const $ID_ICEDOME = 87
Global Const $ID_IRON_HORSE_MINE = 88
Global Const $ID_ANVIL_ROCK = 89
Global Const $ID_LORNARS_PASS = 90
Global Const $ID_SNAKE_DANCE = 91
Global Const $ID_TASCAS_DEMISE = 92
Global Const $ID_SPEARHEAD_PEAK = 93
Global Const $ID_ICE_FLOE = 94
Global Const $ID_WITMANS_FOLLY = 95
Global Const $ID_MINERAL_SPRINGS = 96
Global Const $ID_DREADNOUGHTS_DRIFT = 97
Global Const $ID_FROZEN_FOREST = 98
Global Const $ID_TRAVELERS_VALE = 99
Global Const $ID_DELDRIMOR_BOWL = 100
Global Const $ID_REGENT_VALLEY = 101
Global Const $ID_THE_BREACH = 102
Global Const $ID_ASCALON_FOOTILLS = 103
Global Const $ID_POCKMARK_FLATS = 104
Global Const $ID_DRAGONS_GULLET = 105
Global Const $ID_FLAME_TEMPLE_CORRIDOR = 106
Global Const $ID_EASTERN_FRONTIER = 107
Global Const $ID_THE_SCAR = 108
Global Const $ID_THE_AMNOON_OASIS = 109
Global Const $ID_DIVINERS_ASCENT = 110
Global Const $ID_VULTURE_DRIFTS = 111
Global Const $ID_THE_ARID_SEA = 112
Global Const $ID_PROPHETS_PATH = 113
Global Const $ID_SALT_FLATS = 114
Global Const $ID_SKYWARD_REACH = 115
Global Const $ID_DUNES_OF_DESPAIR = 116
Global Const $ID_THIRSTY_RIVER = 117
Global Const $ID_ELONA_REACH = 118
Global Const $ID_AUGURY_ROCK_MISSION = 119
Global Const $ID_THE_DRAGONS_LAIR = 120
Global Const $ID_PERDITION_ROCK = 121
Global Const $ID_RING_OF_FIRE = 122
Global Const $ID_ABADDONS_MOUTH = 123
Global Const $ID_HELLS_PRECIPICE = 124
Global Const $ID_TITANS_TEARS = 125
Global Const $ID_GOLDEN_GATES = 126
Global Const $ID_SCARRED_EARTH_1 = 127
Global Const $ID_THE_ETERNAL_GROVE_EXPLORABLE = 128
Global Const $ID_LUTGARDIS_CONSERVATORY = 129
Global Const $ID_VASBURG_ARMORY = 130
Global Const $ID_SERENITY_TEMPLE = 131
Global Const $ID_ICE_TOOTH_CAVE = 132
Global Const $ID_BEACONS_PERCH = 133
Global Const $ID_YAKS_BEND = 134
Global Const $ID_FRONTIER_GATE = 135
Global Const $ID_BEETLETUN = 136
Global Const $ID_FISHERMENS_HAVEN = 137
Global Const $ID_TEMPLE_OF_THE_AGES = 138
Global Const $ID_VENTARIS_REFUGE = 139
Global Const $ID_DRUIDS_OVERLOOK = 140
Global Const $ID_MAGUUMA_STADE = 141
Global Const $ID_QUARREL_FALLS = 142
Global Const $ID_ASCALON_ACADEMY_DEVOUTPOST = 143
Global Const $ID_GYALA_HATCHERY_EXPLORABLE = 144
; Eden/Ascalon
Global Const $ID_THE_CATACOMBS = 145
Global Const $ID_LAKESIDE_COUNTY = 146
Global Const $ID_THE_NORTHLANDS = 147
Global Const $ID_ASCALON_CITY_PRESEARING = 148
Global Const $ID_ASCALON_ACADEMY_DEVARENA = 149
Global Const $ID_ASCALON_ACADEMY_PVP_BATTLE = 150
Global Const $ID_ASCALON_ACADEMY_EXPLORABLE = 151
; Prophecies
Global Const $ID_HEROES_AUDIENCE = 152
Global Const $ID_SEEKERS_PASSAGE = 153
Global Const $ID_DESTINYS_GORGE = 154
Global Const $ID_CAMP_RANKOR = 155
Global Const $ID_THE_GRANITE_CITADEL = 156
Global Const $ID_MARHANS_GROTTO = 157
Global Const $ID_PORT_SLEDGE = 158
Global Const $ID_COPPERHAMMER_MINES = 159
; Eden/Ascalon
Global Const $ID_GREEN_HILLS_COUNTY = 160
Global Const $ID_WIZARDS_FOLLY = 161
Global Const $ID_REGENT_VALLEY_PRESEARING = 162
Global Const $ID_BARRADIN_ESTATE = 163
Global Const $ID_ASHFORD_ABBEY = 164
Global Const $ID_FOIBLES_FAIR = 165
Global Const $ID_FORT_RANIK_PRESEARING = 166
; Prophecies
Global Const $ID_BURNING_ISLE = 167
Global Const $ID_DRUIDS_ISLE = 168
Global Const $ID_UNKNOWN_DEVMAP = 169
Global Const $ID_FROZEN_ISLE = 170
Global Const $ID_WARRIORS_ISLE = 171
Global Const $ID_HUNTERS_ISLE = 172
Global Const $ID_WIZARDS_ISLE = 173
Global Const $ID_NOMADS_ISLE = 174
Global Const $ID_ISLE_OF_THE_DEAD = 175
Global Const $ID_GUILD_HALL_FROZEN_ISLE = 176
Global Const $ID_GUILD_HALL_NOMADS_ISLE = 177
Global Const $ID_GUILD_HALL_DRUIDS_ISLE = 178
Global Const $ID_GUILD_HALL_ISLE_OF_THE_DEAD = 179
Global Const $ID_FORT_KOGA_1 = 180
Global Const $ID_SHIVERPEAK_ARENA = 181
Global Const $ID_AMNOON_ARENA = 182
Global Const $ID_DELDRIMOR_ARENA = 183
Global Const $ID_THE_CRAG = 184
Global Const $ID_THE_UNDERWORLD_GUILD_BATTLE = 185
Global Const $ID_THE_UNDERWORLD_GUILD_HALL = 186
Global Const $ID_THE_UNDERWORLD_EXPLORABLE_ALT = 187
Global Const $ID_RANDOM_ARENAS = 188
Global Const $ID_TEAM_ARENAS = 189
Global Const $ID_SORROWS_FURNACE = 190
Global Const $ID_GRENTHS_FOOTPRINT = 191
;Global Const $ID_UNKNOWN_LOCATION = 192
; Factions
Global Const $ID_CAVALON = 193
Global Const $ID_KAINENG_CENTER_DEFAULT = 194
Global Const $ID_DRAZACH_THICKET = 195
Global Const $ID_JAYA_BLUFFS = 196
Global Const $ID_SHENZUN_TUNNELS = 197
Global Const $ID_ARCHIPELAGO = 198
Global Const $ID_MAISHANG_HILLS = 199
Global Const $ID_MOUNT_QINKAI = 200
Global Const $ID_MELANDRUS_HOPE = 201
Global Const $ID_RHEAS_CRATER = 202
Global Const $ID_SILENT_SURF = 203
Global Const $ID_UNWAKING_WATERS_MISSION = 204
Global Const $ID_MOROSTAV_TRAIL = 205
Global Const $ID_DELDRIMOR_WAR_CAMP = 206
Global Const $ID_DRAGONS_THIEVES = 207
Global Const $ID_HEROES_CRYPT_1 = 208
Global Const $ID_MOURNING_VEIL_FALLS = 209
Global Const $ID_FERNDALE = 210
Global Const $ID_PONGMEI_VALLEY = 211
Global Const $ID_MONASTERY_OVERLOOK = 212
Global Const $ID_ZEN_DAIJUN = 213
Global Const $ID_MINISTER_CHOS_ESTATE = 214
Global Const $ID_VIZUNAH_SQUARE = 215
Global Const $ID_NAHPUI_QUARTER = 216
Global Const $ID_TAHNAKAI_TEMPLE = 217
Global Const $ID_ARBORSTONE = 218
Global Const $ID_BOREAS_SEABED = 219
Global Const $ID_SUNJIANG_DISTRICT = 220
Global Const $ID_FORT_ASPENWOOD = 221
Global Const $ID_THE_ETERNAL_GROVE = 222
Global Const $ID_THE_JADE_QUARRY = 223
Global Const $ID_GYALA_HATCHERY = 224
Global Const $ID_RAISU_PALACE = 225
Global Const $ID_RAISU_PALACE_MISSION = 225
Global Const $ID_IMPERIAL_SANCTUM = 226
Global Const $ID_UNWAKING_WATERS_EXPLORABLE = 227
Global Const $ID_GRENZ_FRONTIER = 228
Global Const $ID_THE_ANCESTRAL_LANDS = 229
Global Const $ID_AMTZ_BASIN_EXPLORABLE = 230
Global Const $ID_AMTZ_BASIN = 230
Global Const $ID_KAANAI_CANYON = 231
Global Const $ID_SHADOWS_PASSAGE = 232
Global Const $ID_RAISU_PALACE_EXPLORABLE = 233
Global Const $ID_THE_AURIOS_MINES = 234
Global Const $ID_PANJANG_PENINSULA = 235
Global Const $ID_KINYA_PROVINCE = 236
Global Const $ID_HAIJU_LAGOON = 237
Global Const $ID_SUNQUA_VALE = 238
Global Const $ID_WAJJUN_BAZAAR = 239
Global Const $ID_BUKDEK_BYWAY = 240
Global Const $ID_THE_UNDERCITY = 241
Global Const $ID_SHING_JEA_MONASTERY_DEFAULT = 242
Global Const $ID_SHING_JEA_ARENA = 243
Global Const $ID_ARBORSTONE_EXPLORABLE = 244
Global Const $ID_MINISTER_CHOS_ESTATE_EXPLORABLE = 245
Global Const $ID_ZEN_DAIJUN_EXPLORABLE = 246
Global Const $ID_BOREAS_SEABED_EXPLORABLE = 247
Global Const $ID_GREAT_TEMPLE_OF_BALTHAZAR = 248
Global Const $ID_TSUMEI_VILLAGE = 249
Global Const $ID_SEITUNG_HARBOR = 250
Global Const $ID_RAN_MUSU_GARDENS = 251
Global Const $ID_LINNOK_COURTYARD = 252
Global Const $ID_DWAYNA_VS_GRENTH = 253
Global Const $ID_DWAYNA_CAMP = 254
Global Const $ID_GRENTH_CAMP = 255
Global Const $ID_SUNJIANG_DISTRICT_EXPLORABLE = 256
Global Const $ID_MINISTER_CHOS_ESTATE_MISSION = 257
Global Const $ID_ZEN_DAIJUN_MISSION = 258
Global Const $ID_THE_JADE_QUARRY_KURZICK_MISSION = 259
Global Const $ID_NAHPUI_QUARTER_MISSION = 260
Global Const $ID_TAHNAKAI_TEMPLE_MISSION = 261
Global Const $ID_ARBORSTONE_MISSION = 262
Global Const $ID_BOREAS_SEABED_MISSION = 263
Global Const $ID_SUNJIANG_DISTRICT_MISSION = 264
Global Const $ID_NAHPUI_QUARTER_EXPLORABLE = 265
Global Const $ID_URGOZS_WARREN = 266
Global Const $ID_THE_ETERNAL_GROVE_MISSION = 267
Global Const $ID_GYALA_HATCHERY_MISSION = 268
Global Const $ID_TAHNAKAI_TEMPLE_EXPLORABLE = 269
Global Const $ID_RAISU_PALACE_MISSION_2 = 270
Global Const $ID_IMPERIAL_SANCTUM_MISSION = 271
Global Const $ID_ALTRUMM_RUINS = 272
Global Const $ID_ZOS_SHIVROS_CHANNEL = 273
Global Const $ID_DRAGONS_THROAT = 274
Global Const $ID_GUILD_HALL_ISLE_OF_WEPING_STONE = 275
Global Const $ID_GUILD_HALL_ISLE_OF_JADE = 276
Global Const $ID_HARVEST_TEMPLE = 277
Global Const $ID_BREAKER_HOLLOW = 278
Global Const $ID_LEVIATHAN_PITS = 279
Global Const $ID_ISLE_OF_THE_NAMELESS_1 = 280
Global Const $ID_ZAISHEN_CHALLENGE = 281
Global Const $ID_ZAISHEN_ELITE = 282
Global Const $ID_MAATU_KEEP = 283
Global Const $ID_ZIN_KU_CORRIDOR = 284
Global Const $ID_MONASTERY_OVERLOOK_2 = 285
Global Const $ID_BRAUER_ACADEMY = 286
Global Const $ID_DURHEIM_ARCHIVES = 287
Global Const $ID_BAI_PAASU_REACH = 288
Global Const $ID_SEAFARERS_REST = 289
Global Const $ID_BEJUNKAN_PIER = 290
Global Const $ID_VIZUNAH_SQUARE_LOCAL_QUARTER = 291
Global Const $ID_VIZUNAH_SQUARE_FOREIGN_QUARTER = 292
Global Const $ID_FORT_ASPENWOOD_LUXON = 293
Global Const $ID_FORT_ASPENWOOD_KURZICK = 294
Global Const $ID_THE_JADE_QUARRY_LUXON = 295
Global Const $ID_THE_JADE_QUARRY_KURZICK = 296
Global Const $ID_UNWAKING_WATERS_LUXON_MISSION = 297
Global Const $ID_UNWAKING_WATERS_KURZICK_MISSION = 298
Global Const $ID_SALTSPRAY_BEACH = 299
Global Const $ID_ETNARAN_KEYS = 300
Global Const $ID_RAISU_PAVILLION = 301
Global Const $ID_KAINENG_DOCKS = 302
Global Const $ID_THE_MARKETPLACE = 303
Global Const $ID_VIZUNAH_SQUARE_LOCAL_QUARTER_MISSION = 304
Global Const $ID_VIZUNAH_SQUARE_FOREIGN_QUARTER_MISSION = 305
Global Const $ID_THE_JADE_QUARRY_LUXON_MISSION = 306
Global Const $ID_THE_DEEP = 307
Global Const $ID_ASCALON_ARENA_2 = 308
Global Const $ID_ANNIHILATION = 309
Global Const $ID_KILL_COUNT_TRAINING = 310
Global Const $ID_ANNIHILATION_2 = 311
Global Const $ID_OBELISK_ANNIHILATION_TRAINING = 312
Global Const $ID_SAOSHANG_TRAIL = 313
Global Const $ID_SHIVERPEAK_ARENA_1 = 314
Global Const $ID_UNKNOWN_BATTLE_ISLES = 315
Global Const $ID_UNKNOWN_KRYTA = 316
Global Const $ID_UNKNOWN_CANTHA = 317
Global Const $ID_DALESSIO_ARENA_2 = 318
Global Const $ID_AMNOON_ARENA_1 = 319
Global Const $ID_FORT_KOGA_2 = 320
Global Const $ID_HEROES_CRYPT_2 = 321
Global Const $ID_SHIVERPEAK_ARENA_2 = 322
Global Const $ID_FORT_ASPENWOOD_KURZICK_MISSION = 323
Global Const $ID_FORT_ASPENWOOD_LUXON_MISSION = 324
Global Const $ID_THE_HARVEST_CEREMONY_KURZICK = 325
Global Const $ID_THE_HARVEST_CEREMONY_LUXON = 326
Global Const $ID_IMPERIAL_SANCTUM_EXPLORABLE = 327
Global Const $ID_SALTSPRAY_BEACH_LUXON = 328
Global Const $ID_SALTSPRAY_BEACH_KURZICK = 329
Global Const $ID_HEROES_ASCENT = 330
Global Const $ID_GRENZ_FRONTIER_LUXON = 331
Global Const $ID_GRENZ_FRONTIER_KURZICK = 332
Global Const $ID_THE_ANCESTORAL_LANDS_LUXON = 333
Global Const $ID_THE_ANCESTORAL_LANDS_KURZICK = 334
Global Const $ID_ETNARAN_KEYS_LUXON = 335
Global Const $ID_ETNARAN_KEYS_KURZICK = 336
Global Const $ID_KAANAI_CANYON_LUXON = 337
Global Const $ID_KAANAI_CANYON_KURZICK = 338
Global Const $ID_DALESSIO_ARENA_3 = 339
Global Const $ID_AMNOON_ARENA_2 = 340
Global Const $ID_FORT_KOGA_3 = 341
Global Const $ID_HEROES_CRYPT_3 = 342
Global Const $ID_SHIVERPEAK_ARENA_3 = 343
Global Const $ID_THE_HALL_OF_HEROES = 344
Global Const $ID_THE_COURTYARD = 345
Global Const $ID_SCARRED_EARTH_2 = 346
Global Const $ID_THE_UNDERWORLD_EXPLORABLE = 347
Global Const $ID_TANGLEWOOD_COPSE = 348
Global Const $ID_SAINT_ANJEKAS_SHRINE = 349
Global Const $ID_EREDON_TERRACE = 350
Global Const $ID_DIVINE_PATH = 351
Global Const $ID_BRAWLERS_PIT = 352
Global Const $ID_PETRIFIED_ARENA = 353
Global Const $ID_SEABED_ARENA = 354
Global Const $ID_ISLE_OF_WEPING_STONE = 355
Global Const $ID_ISLE_OF_JADE = 356
Global Const $ID_IMPERIAL_ISLE = 357
Global Const $ID_ISLE_OF_MEDITATION = 358
Global Const $ID_GUILD_HALL_IMPERIAL_ISLE = 359
Global Const $ID_GUILD_HALL_ISLE_OF_MEDITATION = 360
Global Const $ID_ISLE_OF_WEPING_STONE_EXPLORABLE = 361
Global Const $ID_ISLE_OF_JADE_EXPLORABLE = 362
Global Const $ID_IMPERIAL_ISLE_EXPLORABLE = 363
Global Const $ID_ISLE_OF_MEDITATION_EXPLORABLE = 364
Global Const $ID_RANDOM_ARENAS_TEST = 365
Global Const $ID_SHING_JEA_ARENA_TEST = 366
Global Const $ID_ALL_SKILLS = 367
Global Const $ID_DRAGON_ARENA = 368
; Nightfall
Global Const $ID_JAHAI_BLUFFS = 369
Global Const $ID_KAMADAN_JEWEL_OF_ISTAN_MISSION = 370
Global Const $ID_MARGA_COAST = 371
Global Const $ID_FAHRANUR_EXPLORABLE = 372
Global Const $ID_SUNWARD_MARCHES = 373
Global Const $ID_ROLEPLAYING_CHARACTER = 374
Global Const $ID_BARBAROUS_SHORE = 375
Global Const $ID_CAMP_HOJANU = 376
Global Const $ID_BAHDOK_CAVENS = 377
Global Const $ID_WEHHAN_TERRACES = 378
Global Const $ID_DEJARIN_ESTATE = 379
Global Const $ID_ARKJOK_WARD = 380
Global Const $ID_YOHLON_HAVEN = 381
Global Const $ID_GANDARA_THE_MOON_FORTRESS = 382
Global Const $ID_VORTEX = 383
Global Const $ID_THE_FLOODPLAIN_OF_MAHKELEN = 384
Global Const $ID_LIONS_ARCH_DURING_SUNSPEARS_IN_KRYTA = 385
Global Const $ID_TURAIS_PROCESSION = 386
Global Const $ID_SUNSPEAR_SANCTUARY = 387
Global Const $ID_ASPENWOOD_GATE_KURZICK = 388
Global Const $ID_ASPENWOOD_GATE_LUXON = 389
Global Const $ID_JADE_FLATS_KURZICK = 390
Global Const $ID_JADE_FLATS_LUXON = 391
Global Const $ID_YATENDI_CANYONS = 392
Global Const $ID_CHANTRY_OF_SECRETS = 393
Global Const $ID_GARDEN_OF_SEBORHIN = 394
Global Const $ID_HOLDINGSOFCHOKHIN = 395
Global Const $ID_MIHANU_TOWNSHIP = 396
Global Const $ID_VEHJIN_MINES = 397
Global Const $ID_BASALT_GROTTO = 398
Global Const $ID_FORUM_HIGHLANDS = 399
Global Const $ID_KAINENG_CENTER_DURING_SUNSPEARS_IN_CANTHA = 400
Global Const $ID_SEBELKEH_BASILICA = 401
Global Const $ID_RESPLENDENT_MAKUUN = 402
Global Const $ID_HONUR_HILL = 403
Global Const $ID_WILDERNESS_OF_BAHDZA = 404
Global Const $ID_SUN_DOCKS_MISSION = 405
Global Const $ID_VEHTENDI_VALLEY = 406
Global Const $ID_YAHNUR_MARKET = 407
Global Const $ID_HERE_BE_DRAGONS_1 = 408
Global Const $ID_HERE_BE_DRAGONS_2 = 409
Global Const $ID_HERE_BE_DRAGONS_3 = 410
Global Const $ID_HERE_BE_DRAGONS_4 = 411
Global Const $ID_HERE_BE_DRAGONS_5 = 412
Global Const $ID_THE_HIDDEN_CITY_OF_AHDASHIM = 413
Global Const $ID_THE_KODASH_BAZAAR = 414
Global Const $ID_LIONS_GATE = 415
Global Const $ID_MONASTERY_OVERLOOK_MISSION = 416
Global Const $ID_BEJUNKAN_PIER_MISSION = 417
Global Const $ID_LIONS_GATE_MISSION = 418
Global Const $ID_THE_MIRROR_OF_LYSS = 419
Global Const $ID_SECURE_THE_REFUGE = 420
Global Const $ID_VENTA_CEMETERY = 421
Global Const $ID_BAD_TIDE_RISING_KAMADAN_EXPLORABLE = 422
Global Const $ID_THE_TRIBUNAL = 423
Global Const $ID_KODONUR_CROSSROADS = 424
Global Const $ID_RILOHN_REFUGE = 425
Global Const $ID_POGAHN_PASSAGE = 426
Global Const $ID_MODDOK_CREVICE = 427
Global Const $ID_TIHARK_ORCHARD = 428
Global Const $ID_CONSULATE = 429
Global Const $ID_PLAIN_OF_JARIN = 430
Global Const $ID_SUNSPEAR_GREAT_HALL = 431
Global Const $ID_CLIFFS_OF_DOJOK = 432
Global Const $ID_DZAGONUR_BASTION = 433
Global Const $ID_DASHA_VESTIBULE = 434
Global Const $ID_GRAND_COURT_OF_SEBELKEH = 435
Global Const $ID_COMMAND_POST = 436
Global Const $ID_JOKOS_DOMAIN = 437
Global Const $ID_BONE_PALACE = 438
Global Const $ID_THE_RUPTURED_HEART = 439
Global Const $ID_THE_MOUTH_OF_TORMENT = 440
Global Const $ID_THE_SHATTERED_RAVINES = 441
Global Const $ID_LAIR_OF_THE_FORGOTTEN = 442
Global Const $ID_POISONED_OUTCROPS = 443
Global Const $ID_THE_SULFUROUS_WASTES = 444
Global Const $ID_THE_EBONY_CITADEL_OF_MALLYX = 445
Global Const $ID_THE_ALKALI_PAN = 446
Global Const $ID_A_LAND_OF_HEROES = 447
Global Const $ID_CRYSTAL_OVERLOOK = 448
Global Const $ID_KAMADAN_JEWEL_OF_ISTAN_DEFAULT = 449
Global Const $ID_GATE_OF_TORMENT = 450
; Below map ID does not seem to work, 474 works instead as below
;Global Const $ID_GATE_OF_ANGUISH = 451
Global Const $ID_SECURE_THE_REFUGE_MISSION = 452
Global Const $ID_EVACUATION = 453
Global Const $ID_TEST_MAP_2 = 454
Global Const $ID_NIGHTFALLEN_GARDEN = 455
Global Const $ID_CHUURHIR_FIELDS = 456
Global Const $ID_BEKNUR_HARBOR_1 = 457
Global Const $ID_KODONUR_CROSSROADS_MISSION = 458
Global Const $ID_RILOHN_REFUGE_MISSION = 459
Global Const $ID_POGAHN_PASSAGE_MISSION = 460
Global Const $ID_THE_UNDERWORLD_2 = 461
Global Const $ID_HEART_OF_ABADDON = 462
Global Const $ID_THE_UNDERWORLD_3 = 463
Global Const $ID_NIGHTFALLEN_COAST = 464
Global Const $ID_NIGHTFALLEN_JAHAI = 465
Global Const $ID_DEPTHS_OF_MADNESS = 466
Global Const $ID_ROLLERBEETLE_RACING = 467
Global Const $ID_DOMAIN_OF_FEAR = 468
Global Const $ID_GATE_OF_FEAR = 469
Global Const $ID_DOMAIN_OF_PAIN = 470
Global Const $ID_BLOODSTONE_FEN_EXPLORABLE = 471
Global Const $ID_DOMAIN_OF_SECRETS = 472
Global Const $ID_GATE_OF_SECRETS = 473
; Surprisingly map ID of Gate of Anguish is the same as Domain of Anguish
;Global Const $ID_DOMAIN_OF_ANGUISH = 474
Global Const $ID_GATE_OF_ANGUISH = 474
Global Const $ID_OOZE_PIT_ALT = 475
Global Const $ID_JENNURS_HORDE = 476
Global Const $ID_NUNDU_BAY = 477
Global Const $ID_GATE_OF_DESOLATION = 478
Global Const $ID_CHAMPIONS_DAWN = 479
Global Const $ID_RUINS_OF_MORAH = 480
Global Const $ID_FAHRANUR_THE_FIRST_CITY = 481
Global Const $ID_BJORA_MARCHES = 482
Global Const $ID_ZEHLON_REACH = 483
Global Const $ID_LAHTEDA_BOG = 484
Global Const $ID_ARBOR_BAY = 485
Global Const $ID_ISSNUR_ISLES = 486
Global Const $ID_BEKNUR_HARBOR_2 = 487
Global Const $ID_MEHTANI_KEYS = 488
Global Const $ID_KODLONU_HAMLET = 489
Global Const $ID_ISLAND_OF_SHEKHAH = 490
Global Const $ID_JOKANUR_DIGGINGS = 491
Global Const $ID_BLACKTIDE_DEN = 492
Global Const $ID_CONSULATE_DOCKS = 493
Global Const $ID_GATE_OF_PAIN = 494
Global Const $ID_GATE_OF_MADNESS = 495
Global Const $ID_ABADDONS_GATE = 496
Global Const $ID_SUNSPEAR_ARENA = 497
Global Const $ID_UNKNOWN_KOURNA = 498
Global Const $ID_ICE_CLIFF_CHASMS = 499
Global Const $ID_BOKKA_AMPHITHEATRE = 500
Global Const $ID_RIVEN_EARTH = 501
Global Const $ID_THE_ASTRALARIUM = 502
Global Const $ID_THRONE_OF_SECRETS = 503
Global Const $ID_CHURRANU_ISLAND_ARENA = 504
Global Const $ID_SHING_JEA_MONASTERY_MISSION = 505
Global Const $ID_HAIJU_LAGOON_MISSION = 506
Global Const $ID_JAYA_BLUFFS_MISSION = 507
Global Const $ID_SEITUNG_HARBOR_MISSION = 508
Global Const $ID_TSUMEI_VILLAGE_MISSION = 509
Global Const $ID_SEITUNG_HARBOR_MISSION_2 = 510
Global Const $ID_TSUMEI_VILLAGE_MISSION_2 = 511
Global Const $ID_MINISTER_CHOS_ESTATE_MISSION_2 = 512
Global Const $ID_DRAKKAR_LAKE = 513
Global Const $ID_ISLAND_OF_SHEKHAH_MISSION = 514
Global Const $ID_JOKANUR_DIGGINGS_MISSION = 515
Global Const $ID_BLACKTIDE_DEN_MISSION = 516
Global Const $ID_CONSULATE_DOCKS_MISSION = 517
Global Const $ID_TIHARK_ORCHARD_MISSION = 518
Global Const $ID_DZAGONUR_BASTION_MISSION = 519
Global Const $ID_HIDDEN_CITY_OF_AHDASHIM_MISSION = 520
Global Const $ID_GRAND_COURT_OF_SEBELKEH_MISSION = 521
Global Const $ID_JENNURS_HORDE_MISSION = 522
Global Const $ID_NUNDU_BAY_MISSION = 523
Global Const $ID_GATES_OF_DESOLATION_MISSION = 524
Global Const $ID_RUINS_OF_MORAH_MISSION = 525
Global Const $ID_DOMAIN_OF_PAIN_MISSION = 526
Global Const $ID_GATE_OF_MADNESS_MISSION = 527
Global Const $ID_ABADDONS_GATE_MISSION = 528
Global Const $ID_GUILD_HALL_UNCHARTED_ISLE = 529
Global Const $ID_GUILD_HALL_ISLE_OF_WURMS = 530
Global Const $ID_UNCHARTED_ISLE_EXPLORABLE = 531
Global Const $ID_ISLE_OF_WURMS_EXPLORABLE = 532
Global Const $ID_UNCHARTED_ISLE = 533
Global Const $ID_ISLE_OF_WURMS = 534
Global Const $ID_AHMTUR_ARENA = 535
Global Const $ID_SUNSPEAR_ARENA_2 = 536
Global Const $ID_GUILD_HALL_CORRUPTED_ISLE = 537
Global Const $ID_GUILD_HALL_ISLE_OF_SOLITUDE = 538
Global Const $ID_CORRUPTED_ISLE_EXPLORABLE = 539
Global Const $ID_ISLE_OF_SOLITUDE_EXPLORABLE = 540
Global Const $ID_CORRUPTED_ISLE = 541
Global Const $ID_ISLE_OF_SOLITUDE = 542
Global Const $ID_SUN_DOCKS = 543
Global Const $ID_CHAHBEK_VILLAGE = 544
Global Const $ID_REMAINS_OF_SAHLAHJA = 545
Global Const $ID_JAGA_MORAINE = 546
Global Const $ID_BOMBARDMENT = 547
Global Const $ID_NORRHART_DOMAINS = 548
Global Const $ID_HERO_BATTLES = 549
Global Const $ID_THE_BEACHHEAD = 550
Global Const $ID_THE_CROSSING = 551
Global Const $ID_DESERT_SANDS = 552
Global Const $ID_VARAJAR_FELLS = 553
Global Const $ID_DAJKAH_INLET = 554
Global Const $ID_THE_SHADOW_NEXUS = 555
Global Const $ID_CHAHBEK_VILLAGE_MISSION = 556
Global Const $ID_THRONE_OF_SECRETS_2 = 557
Global Const $ID_SPARKFLY_SWAMP = 558
Global Const $ID_GATE_OF_THE_NIGHTFALLEN_LANDS = 559
Global Const $ID_CATHEDRAL_OF_FLAMES = 560
Global Const $ID_THE_TROUBLED_KEEPER = 561
Global Const $ID_FORTRESS_OF_JAHAI = 562
Global Const $ID_HALLS_OF_CHOKHIN = 563
Global Const $ID_CITADEL_OF_DZAGON = 564
Global Const $ID_DYNASTIC_TOMBS = 565
Global Const $ID_VERDANT_CASCADES = 566
Global Const $ID_CATHEDRAL_OF_FLAMES_LVL_1 = 567
Global Const $ID_CATHEDRAL_OF_FLAMES_LVL_2 = 568
Global Const $ID_MAGUS_STONES = 569
Global Const $ID_CATACOMBS_OF_KATHANDRAX_LVL_1 = 570
Global Const $ID_CATACOMBS_OF_KATHANDRAX_LVL_2 = 571
Global Const $ID_ALCAZIA_TANGLE = 572
Global Const $ID_RRAGARS_MENAGERIE_LVL_1 = 573
Global Const $ID_RRAGARS_MENAGERIE_LVL_2 = 574
Global Const $ID_RRAGARS_MENAGERIE_LVL_3 = 575
Global Const $ID_OOZE_PIT = 576
Global Const $ID_SLAVERS_EXILE = 577
Global Const $ID_OOLAS_LAB_LVL_1 = 578
Global Const $ID_OOLAS_LAB_LVL_2 = 579
Global Const $ID_OOLAS_LAB_LVL_3 = 580
Global Const $ID_SHARDS_OF_ORR_LVL_1 = 581
Global Const $ID_SHARDS_OF_ORR_LVL_2 = 582
Global Const $ID_SHARDS_OF_ORR_LVL_3 = 583
Global Const $ID_ARACHNIS_HAUNT_LVL_1 = 584
Global Const $ID_ARACHNIS_HAUNT_LVL_2 = 585
Global Const $ID_BURNING_EMBERS = 586
Global Const $ID_BURNING_FURNACE = 587
Global Const $ID_BURNING_TEMPLE = 588
Global Const $ID_CATACOMBS_LUSH = 589
Global Const $ID_CATACOMBS_STONE = 590
Global Const $ID_CATACOMBS_TOMB = 591
;Global Const $ID_UNKNOWN_LOCATION = 592
Global Const $ID_FETID_RIVER = 593
Global Const $ID_OVERLOOK = 594
Global Const $ID_CEMETERY = 595
Global Const $ID_FORGOTTEN_SHRINES = 596
Global Const $ID_TRACK = 597
Global Const $ID_ANTECHAMBER = 598
Global Const $ID_COLLISION = 599
Global Const $ID_THE_HALL_OF_HEROES_2 = 600
Global Const $ID_FROZEN_CREVASSE = 601
Global Const $ID_FROZEN_DEPLETED = 602
Global Const $ID_FROZEN_FORT = 603
; Eye of the North
Global Const $ID_VLOXEN_EXCAVATIONS_LVL_1 = 604
Global Const $ID_VLOXEN_EXCAVATIONS_LVL_2 = 605
Global Const $ID_VLOXEN_EXCAVATIONS_LVL_3 = 606
Global Const $ID_HEART_OF_THE_SHIVERPEAKS_LVL_1 = 607
Global Const $ID_HEART_OF_THE_SHIVERPEAKS_LVL_2 = 608
Global Const $ID_HEART_OF_THE_SHIVERPEAKS_LVL_3 = 609
Global Const $ID_THE_JOURNEY_TO_NORNHEIM_1 = 610
Global Const $ID_THE_JOURNEY_TO_NORNHEIM_2 = 611
Global Const $ID_BLOODSTONE_CAVES_LVL_1 = 612
Global Const $ID_BLOODSTONE_CAVES_LVL_2 = 613
Global Const $ID_BLOODSTONE_CAVES_LVL_3 = 614
Global Const $ID_BOGROOT_GROWTHS_LVL_1 = 615
Global Const $ID_BOGROOT_GROWTHS_LVL_2 = 616
Global Const $ID_RAVENS_POINT_LVL_1 = 617
Global Const $ID_RAVENS_POINT_LVL_2 = 618
Global Const $ID_RAVENS_POINT_LVL_3 = 619
Global Const $ID_SLAVERS_EXILE_LVL_1 = 620
Global Const $ID_SLAVERS_EXILE_LVL_2 = 621
Global Const $ID_SLAVERS_EXILE_LVL_3 = 622
Global Const $ID_SLAVERS_EXILE_LVL_4 = 623
Global Const $ID_VLOXS_FALLS = 624
Global Const $ID_BATTLEDEPTHS = 625
Global Const $ID_BATTLEDEPTHS_LVL_2 = 626
Global Const $ID_BATTLEDEPTHS_LVL_3 = 627
Global Const $ID_SEPULCHRE_OF_DRAGRIMMAR_LVL_1 = 628
Global Const $ID_SEPULCHRE_OF_DRAGRIMMAR_LVL_2 = 629
Global Const $ID_FROSTMAWS_BURROWS_LVL_1 = 630
Global Const $ID_FROSTMAWS_BURROWS_LVL_2 = 631
Global Const $ID_FROSTMAWS_BURROWS_LVL_3 = 632
Global Const $ID_FROSTMAWS_BURROWS_LVL_4 = 633
Global Const $ID_FROSTMAWS_BURROWS_LVL_5 = 634
Global Const $ID_DARKRIME_DELVES_LVL_1 = 635
Global Const $ID_DARKRIME_DELVES_LVL_2 = 636
Global Const $ID_DARKRIME_DELVES_LVL_3 = 637
Global Const $ID_GADDS_ENCAMPMENT = 638
Global Const $ID_UMBRAL_GROTTO = 639
Global Const $ID_RATA_SUM = 640
Global Const $ID_TARNISHED_HAVEN = 641
Global Const $ID_EYE_OF_THE_NORTH_DEFAULT = 642
Global Const $ID_SIFHALLA = 643
Global Const $ID_GUNNARS_HOLD = 644
Global Const $ID_OLAFSTEAD = 645
Global Const $ID_HALL_OF_MONUMENTS = 646
Global Const $ID_DALADA_UPLANDS = 647
Global Const $ID_DOOMLORE_SHRINE = 648
Global Const $ID_GROTHMAR_WARDOWNS = 649
Global Const $ID_LONGEYES_LEDGE = 650
Global Const $ID_SACNOTH_VALLEY = 651
Global Const $ID_CENTRAL_TRANSFER_CHAMBER = 652
Global Const $ID_CURSE_OF_THE_NORNBEAR = 653
Global Const $ID_BLOOD_WASHES_BLOOD = 654
Global Const $ID_A_GATE_TOO_FAR_LVL_1 = 655
Global Const $ID_A_GATE_TOO_FAR_LVL_2 = 656
Global Const $ID_A_GATE_TOO_FAR_LVL_3 = 657
Global Const $ID_THE_ELUSIVE_GOLEMANCER_LVL_1 = 658
Global Const $ID_THE_ELUSIVE_GOLEMANCER_LVL_2 = 659
Global Const $ID_THE_ELUSIVE_GOLEMANCER_LVL_3 = 660
Global Const $ID_FINDING_THE_BLOODSTONE_LVL_1 = 661
Global Const $ID_FINDING_THE_BLOODSTONE_LVL_2 = 662
Global Const $ID_FINDING_THE_BLOODSTONE_LVL_3 = 663
Global Const $ID_GENIUS_OPERATED_LIVING_ENCHANTED_MANIFESTATION = 664
Global Const $ID_AGAINST_THE_CHARR = 665
Global Const $ID_WARBANDS_OF_BROTHERS_LVL_1 = 666
Global Const $ID_WARBANDS_OF_BROTHERS_LVL_2 = 667
Global Const $ID_WARBANDS_OF_BROTHERS_LVL_3 = 668
Global Const $ID_ASSAULT_THE_STRONGHOLD = 669
Global Const $ID_DESTRUCTIONS_DEPTHS_LVL_1 = 670
Global Const $ID_DESTRUCTIONS_DEPTHS_LVL_2 = 671
Global Const $ID_DESTRUCTIONS_DEPTHS_LVL_3 = 672
Global Const $ID_A_TIME_FOR_HEROES = 673
Global Const $ID_WARBANDS_TRAINING = 674
Global Const $ID_BOREAL_STATION = 675
Global Const $ID_CATACOMBS_OF_KATHANDRAX = 676
Global Const $ID_HALL_OF_PRIMORDUS = 677
Global Const $ID_ATTACK_OF_THE_NORNBEAR = 678
Global Const $ID_CINEMATIC_CAVE_NORN_CURSED = 679
Global Const $ID_CINEMATIC_STEPPE_INTERROGATION = 680
Global Const $ID_CINEMATIC_INTERIOR_RESEARCH = 681
Global Const $ID_CINEMATIC_EYE_VISION_A = 682
Global Const $ID_CINEMATIC_EYE_VISION_B = 683
Global Const $ID_CINEMATIC_EYE_VISION_C = 684
Global Const $ID_CINEMATIC_EYE_VISION_D = 685
Global Const $ID_POLYMOCK_COLISEUM = 686
Global Const $ID_POLYMOCK_GLACIER = 687
Global Const $ID_POLYMOCK_CROSSING = 688
Global Const $ID_CINEMATIC_MOUNTAIN_RESOLUTION = 689
Global Const $ID_COLD_AS_ICE = 690
Global Const $ID_BENEATH_LIONS_ARCH = 691
Global Const $ID_TUNNELS_BELOW_CANTHAA = 692
Global Const $ID_CAVERNS_BELOW_KAMADAN = 693
Global Const $ID_CINEMATIC_DWARFS_MOUNTAIN = 694
Global Const $ID_SERVICE_IN_DEFENSE_OF_THE_EYE = 695
Global Const $ID_MANO_A_NORNO = 696
Global Const $ID_SERVICE_PRACTICE_DUMMY = 697
Global Const $ID_HERO_TUTORIAL = 698
Global Const $ID_PROTOTYPE_MAP = 699
Global Const $ID_THE_NORN_FIGHTING_TOURNAMENT = 700
Global Const $ID_SNOWMEN_LAIR = 701
Global Const $ID_NORN_BRAWLING_CHAMPIONSHIP = 702
Global Const $ID_KILROYS_PUNCHOUT_TRAINING = 703
Global Const $ID_FRONIS_IRONTOES_LAIR = 704
Global Const $ID_THE_JUSTICIARS_END = 705
Global Const $ID_DESIGNER_TEST_MAP = 706
Global Const $ID_THE_GREAT_NORN_ALEMOOT = 707
Global Const $ID_VARAJAR_FELLS_2 = 708
Global Const $ID_BATTLE_FOR_NORNHEIM = 709
Global Const $ID_EPILOGUE = 710
Global Const $ID_INSIDIOUS_REMNANTS = 711
Global Const $ID_UNKNOWN_ISTAN_ARENA = 712
Global Const $ID_UNKNOWN_VABBI_ARENA = 713
Global Const $ID_UNKNOWN_DESOLATION_ARENA = 714
Global Const $ID_UNKNOWN_RISE_OF_WHITE_MANTLE = 715
Global Const $ID_UNKNOWN_CHARR_MISSION = 716
Global Const $ID_ATTACK_ON_JALISS_CAMP = 717
Global Const $ID_UNKNOWN_CHARR_MISSION_2 = 718
Global Const $ID_UNKNOWN_TARNISHED_COAST_MISSION = 719
Global Const $ID_UNKNOWN_CHARR_EXPLORABLE = 720
Global Const $ID_COSTUME_BRAWL = 721
Global Const $ID_WHITEFURY_RAPIDS = 722
Global Const $ID_KYSTEN_SHORE = 723
Global Const $ID_DEEPWAY_RUINS = 724
Global Const $ID_PLIKKUP_WORKS = 725
Global Const $ID_KILROYS_PUNCHOUT_TOURNAMET = 726
Global Const $ID_SPECIAL_OPS_FLAME_TEMPLE_CORRIDOR = 727
Global Const $ID_SPECIAL_OPS_GRENDICH_COURTHOUSE = 728
Global Const $ID_SPECIAL_OPS_GRENDICH_COURTHOUSE_2 = 729
Global Const $ID_UNKNOWN_DEPTHS_MISSION = 730
Global Const $ID_UNKNOWN_FAR_SHIVERPEAKS_MISSION_1 = 731
Global Const $ID_UNKNOWN_FAR_SHIVERPEAKS_MISSION_2 = 732
Global Const $ID_UNKNOWN_FAR_SHIVERPEAKS_MISSION_3 = 733
Global Const $ID_UNKNOWN_FAR_SHIVERPEAKS_MISSION_4 = 734
Global Const $ID_UNKNOWN_FAR_SHIVERPEAKS_MISSION_5 = 735
Global Const $ID_UNKNOWN_FAR_SHIVERPEAKS_MISSION_6 = 736
Global Const $ID_UNKNOWN_FAR_SHIVERPEAKS_MISSION_7 = 737
Global Const $ID_UNKNOWN_FAR_SHIVERPEAKS_MISSION_8 = 738
Global Const $ID_UNKNOWN_FAR_SHIVERPEAKS_MISSION_9 = 739
Global Const $ID_UNKNOWN_CHARR_MISSION_3 = 740
Global Const $ID_UNKNOWN_CHARR_MISSION_4 = 741
Global Const $ID_UNKNOWN_CHARR_MISSION_5 = 742
Global Const $ID_UNKNOWN_CHARR_MISSION_6 = 743
Global Const $ID_UNKNOWN_CHARR_MISSION_7 = 744
Global Const $ID_UNKNOWN_CHARR_MISSION_8 = 745
Global Const $ID_UNKNOWN_TARNISHED_COAST_MISSION_2 = 746
Global Const $ID_UNKNOWN_TARNISHED_COAST_MISSION_3 = 747
Global Const $ID_UNKNOWN_TARNISHED_COAST_MISSION_4 = 748
Global Const $ID_UNKNOWN_TARNISHED_COAST_MISSION_5 = 749
Global Const $ID_UNKNOWN_TARNISHED_COAST_MISSION_6 = 750
Global Const $ID_UNKNOWN_TARNISHED_COAST_MISSION_7 = 751
Global Const $ID_UNKNOWN_TARNISHED_COAST_MISSION_8 = 752
Global Const $ID_UNKNOWN_DEPTHS_MISSION_2 = 753
Global Const $ID_UNKNOWN_DEPTHS_MISSION_3 = 754
Global Const $ID_UNKNOWN_DEPTHS_MISSION_4 = 755
Global Const $ID_UNKNOWN_PROPHECIES_DEV = 756
Global Const $ID_UNKNOWN_FACTIONS_DEV = 757
Global Const $ID_UNKNOWN_NIGHTFALL_DEV = 758
Global Const $ID_UNKNOWN_TARNISHED_COAST_EOTN_MISSION = 759
Global Const $ID_UNKNOWN_TARNISHED_COAST_EOTN_MISSION_2 = 760
Global Const $ID_UNKNOWN_CHARR_EOTN_MISSION = 761
Global Const $ID_UNKNOWN_CHARR_EOTN_MISSION_2 = 762
Global Const $ID_UNKNOWN_CHARR_EOTN_MISSION_3 = 763
Global Const $ID_UNKNOWN_DEPTHS_EOTN_MISSION = 764
Global Const $ID_UNKNOWN_DEPTHS_EOTN_MISSION_2 = 765
Global Const $ID_UNKNOWN_FAR_SHIVERPEAKS_EOTN_MISSION = 766
Global Const $ID_UNKNOWN_FAR_SHIVERPEAKS_EOTN_MISSION_2 = 767
Global Const $ID_UNKNOWN_FAR_SHIVERPEAKS_EOTN_MISSION_3 = 768
Global Const $ID_UNKNOWN_TARNISHED_COAST_EOTN_MISSION_3 = 769
Global Const $ID_THE_TENGU_ACCORDS = 770
Global Const $ID_THE_BATTLE_OF_JAHAI = 771
Global Const $ID_THE_FLIGHT_NORTH = 772
Global Const $ID_THE_RISE_OF_THE_WHITE_MANTLE = 773
Global Const $ID_UNKNOWN_MARKETPLACE = 774
Global Const $ID_THE_TENGU_ACCORDS_MISSION = 775
Global Const $ID_UNKNOWN_KRYTA_EXPLORABLE = 776
Global Const $ID_THE_BATTLE_OF_JAHAI_MISSION = 777
Global Const $ID_THE_FLIGHT_NORTH_MISSION = 778
Global Const $ID_UNKNOWN_DEV_REGION_1 = 779
Global Const $ID_UNKNOWN_DEV_REGION_2 = 780
Global Const $ID_SECRET_LAIR_OF_THE_SNOWMEN_LVL_1 = 781
Global Const $ID_SECRET_LAIR_OF_THE_SNOWMEN_LVL_2 = 782
Global Const $ID_DROKNARS_FORGE_EXPLORABLE = 783
Global Const $ID_ISLE_OF_THE_NAMELESS_2 = 784
Global Const $ID_UNKNOWN_JADE_SEA_HERO_BATTLE = 785
Global Const $ID_UNKNOWN_KAINENG_GUILD_BATTLE = 786
Global Const $ID_UNKNOWN_HEROES_ASCENT_GUILD_BATTLE = 787
Global Const $ID_DEACTIVATING_ROX = 788
Global Const $ID_DEACTIVATING_POX = 789
Global Const $ID_DEACTIVATING_NOX = 790
Global Const $ID_SECRET_UNDERGROUND_LAIR = 791
Global Const $ID_GOLEM_TUTORIAL_SIMULATION = 792
Global Const $ID_SNOWBALL_DOMINANCE = 793
Global Const $ID_ZAISHEN_MENAGERIE_GROUNDS = 794
Global Const $ID_ZAISHEN_MENAGERIE = 795
Global Const $ID_CODEX_ARENA = 796
Global Const $ID_UNKNOWN_DUNGEON_1 = 797
Global Const $ID_UNKNOWN_DUNGEON_2 = 798
Global Const $ID_UNKNOWN_DUNGEON_3 = 799
Global Const $ID_UNKNOWN_DUNGEON_4 = 800
Global Const $ID_UNKNOWN_DUNGEON_5 = 801
Global Const $ID_UNKNOWN_DUNGEON_6 = 802
Global Const $ID_UNKNOWN_DUNGEON_7 = 803
Global Const $ID_UNKNOWN_DUNGEON_8 = 804
Global Const $ID_UNKNOWN_DUNGEON_9 = 805
Global Const $ID_THE_UNDERWORLD_SOMETHING_WICKED_THIS_WAY_COMES = 806
Global Const $ID_THE_UNDERWORLD_DONT_FEAR_THE_REAPERS = 807
Global Const $ID_LIONS_ARCH_HALLOWEEN = 808
Global Const $ID_LIONS_ARCH_WINTERSDAY = 809
Global Const $ID_LIONS_ARCH_CANTHANS_NEW_YEAR = 810
Global Const $ID_ASCALON_CITY_WINTERSDAY = 811
Global Const $ID_DROKNARS_FORGE_HALLOWEEN = 812
Global Const $ID_DROKNARS_FORGE_WINTERSDAY = 813
Global Const $ID_TOMB_OF_THE_PRIMEVAL_KINGS_HALLOWEEN = 814
Global Const $ID_SHING_JEA_MONASTERY_DRAGON_FESTIVAL = 815
Global Const $ID_SHING_JEA_MONASTERY_CANTHAN_NEW_YEAR = 816
Global Const $ID_KAINENG_CENTER_CANTHAN_NEW_YEAR = 817
Global Const $ID_KAMADAN_JEWEL_OF_ISTAN_HALLOWEEN = 818
Global Const $ID_KAMADAN_JEWEL_OF_ISTAN_WINTERSDAY = 819
Global Const $ID_KAMADAN_JEWEL_OF_ISTAN_CANTHAN_NEW_YEAR = 820
Global Const $ID_EYE_OF_THE_NORTH_WINTERSDAY = 821
Global Const $ID_UNKNOWN_MAGUUMA_CITY = 822
Global Const $ID_UNKNOWN_KRYTA_ARENA = 823
Global Const $ID_UNKNOWN_CRYSTAL_DESERT_ARENA = 824
Global Const $ID_UNKNOWN_KOURNA_ARENA = 825
Global Const $ID_UNKNOWN_MAGUUMA_ARENA = 826
Global Const $ID_UNKNOWN_ECHOVALD_ARENA = 827
Global Const $ID_UNKNOWN_ASCALON_ARENA = 828
Global Const $ID_UNKNOWN_JADE_SEA_ARENA = 829
Global Const $ID_UNKNOWN_SHIVERPEAKS_ARENA = 830
Global Const $ID_UNKNOWN_KAINENG_ARENA = 831
Global Const $ID_UNKNOWN_FOW_ARENA = 832
Global Const $ID_UNKNOWN_ISTAN_ARENA_2 = 833
Global Const $ID_UNKNOWN_SHING_JEA_ARENA_2 = 834
Global Const $ID_UNKNOWN_ASCALON_ARENA_2 = 835
Global Const $ID_UNKNOWN_SHIVERPEAKS_ARENA_2 = 836
Global Const $ID_WAR_IN_KRYTA_TALMARK_WILDERNESS = 837
Global Const $ID_TRIAL_OF_ZINN = 838
Global Const $ID_DIVINITY_COAST_EXPLORABLE = 839
Global Const $ID_LIONS_ARCH_KEEP = 840
Global Const $ID_DALESSIO_SEABOARD_EXPLORABLE = 841
Global Const $ID_THE_BATTLE_FOR_LIONS_ARCH_EXPLORABLE = 842
Global Const $ID_RIVERSIDE_PROVINCE_EXPLORABLE = 843
Global Const $ID_WAR_IN_KRYTA_LIONS_ARCH = 844
Global Const $ID_THE_MASOLEUM = 845
Global Const $ID_RISE_MAP = 846
Global Const $ID_SHADOWS_IN_THE_JUNGLE = 847
Global Const $ID_A_VENGEANCE_OF_BLADES = 848
Global Const $ID_AUSPICIOUS_BEGINNINGS = 849
Global Const $ID_UNKNOWN_KRYTA_WIK_1 = 850
Global Const $ID_UNKNOWN_MAGUUMA_WIK = 851
Global Const $ID_UNKNOWN_KRYTA_WIK_2 = 852
Global Const $ID_UNKNOWN_KRYTA_WIK_3 = 853
Global Const $ID_OLFSTEAD_EXPLORABLE = 854
Global Const $ID_THE_GREAT_SNOWBALL_FIGHT_CRUSH_SPIRITS = 855
Global Const $ID_THE_GREAT_SNOWBALL_FIGHT_WINTER_WONDERLAND = 856
Global Const $ID_EMBARK_BEACH = 857
Global Const $ID_UNKNOWN_SWAT_1 = 858
Global Const $ID_UNKNOWN_SWAT_2 = 859
Global Const $ID_WHAT_WAITS_IN_SHADOW_DRAGONS_THROAT_EXPLORABLE = 860
Global Const $ID_KAINENG_A_CHANCE_ENCOUNTER = 861
Global Const $ID_TRACKING_THE_CORRUPTION_MARKETPLACE_EXPLORABLE = 862
Global Const $ID_CANTHA_COURIER_BUKDEK_BYWAY = 863
Global Const $ID_A_TREATYS_A_TREATY_TSUMEI_VILLAGE = 864
Global Const $ID_DEADLY_CARGO_SEITUNG_HARBOR_EXPLORABLE = 865
Global Const $ID_THE_RESCUE_ATTEMPT_TAHNAKAI_TEMPLE = 866
Global Const $ID_VILOENCE_IN_THE_STREETS_WAJJUN_BAZAAR = 867
Global Const $ID_SACRED_PSYCHE = 868
Global Const $ID_CALLING_ALL_THUGS_SHADOWS_PASSAGE = 869
Global Const $ID_FINDING_JINNAI_ALTRUMM_RUINS = 870
Global Const $ID_RAID_ON_SHING_JEA_MONASTERY_SHING_JEA_MONASTERY = 871
Global Const $ID_RAID_ON_KAINENG_CENTER_KAINENG_CENTER = 872
Global Const $ID_MINISTRY_OF_OPPRESSION_WAJJUN_BAZAAR = 873
Global Const $ID_THE_FINAL_CONFRONTATION = 874
Global Const $ID_LAKESIDE_COUNTY_1070_AE = 875
Global Const $ID_ASHFORD_CATACOMBS_1070_AE = 876
#EndRegion Map Location IDs


#Region Varying Map Location IDs
; Locations varying seasonally, these are being set automatically according to decorated state during festivals or undecorated not during festivals
Global Const $ID_ASCALON_CITY = IsChristmasFestival() ? $ID_ASCALON_CITY_WINTERSDAY : $ID_ASCALON_CITY_DEFAULT
Global Const $ID_LIONS_ARCH = IsChristmasFestival() ? $ID_LIONS_ARCH_WINTERSDAY : IsHalloweenFestival() ? $ID_LIONS_ARCH_HALLOWEEN : IsAnniversaryCelebration() ? $ID_LIONS_ARCH_CANTHAN_NEW_YEAR : $ID_LIONS_ARCH_DEFAULT
Global Const $ID_DROKNARS_FORGE = IsChristmasFestival() ? $ID_DROKNARS_FORGE_WINTERSDAY : IsHalloweenFestival() ? $ID_DROKNARS_FORGE_HALLOWEEN : $ID_DROKNARS_FORGE_DEFAULT
Global Const $ID_TOMB_OF_THE_PRIMEVAL_KINGS = IsHalloweenFestival() ? $ID_TOMB_OF_THE_PRIMEVAL_KINGS_HALLOWEEN : $ID_TOMB_OF_THE_PRIMEVAL_KINGS_DEFAULT
Global Const $ID_SHING_JEA_MONASTERY = IsAnniversaryCelebration() ? $ID_SHING_JEA_MONASTERY_CANTHAN_NEW_YEAR : IsDragonFestival() ? $ID_SHING_JEA_MONASTERY_DRAGON_FESTIVAL : $ID_SHING_JEA_MONASTERY_DEFAULT
Global Const $ID_KAINENG_CENTER = IsAnniversaryCelebration()? $ID_KAINENG_CENTER_CANTHAN_NEW_YEAR : $ID_KAINENG_CENTER_DEFAULT
Global Const $ID_KAMADAN_JEWEL_OF_ISTAN = IsChristmasFestival() ? $ID_KAMADAN_JEWEL_OF_ISTAN_WINTERSDAY : IsHalloweenFestival() ? $ID_KAMADAN_JEWEL_OF_ISTAN_HALLOWEEN : IsAnniversaryCelebration() ? $ID_KAMADAN_JEWEL_OF_ISTAN_CANTHAN_NEW_YEAR : $ID_KAMADAN_JEWEL_OF_ISTAN_DEFAULT
Global Const $ID_EYE_OF_THE_NORTH = IsChristmasFestival() ? $ID_EYE_OF_THE_NORTH_WINTERSDAY : $ID_EYE_OF_THE_NORTH_DEFAULT
#EndRegion Varying Map Location IDs


#Region Map Arrays
Global Const $MAP_IDS[] = [ _
	$ID_GLADIATORS_ARENA, _
	$ID_DEV_TEST_ARENA_1V1, _
	$ID_TEST_MAP, _
	$ID_GUILD_HALL_WARRIORS_ISLE, _
	$ID_GUILD_HALL_HUNTERS_ISLE, _
	$ID_GUILD_HALL_WIZARDS_ISLE, _
	$ID_WARRIORS_ISLE_EXPLORABLE, _
	$ID_HUNTERS_ISLE_EXPLORABLE, _
	$ID_WIZARDS_ISLE_EXPLORABLE, _
	$ID_BLOODSTONE_FEN, _
	$ID_THE_WILDS, _
	$ID_AURORA_GLADE, _
	$ID_DIESSA_LOWLANDS, _
	$ID_GATES_OF_KRYTA, _
	$ID_DALESSIO_SEABOARD, _
	$ID_DIVINITY_COAST, _
	$ID_TALMARK_WILDERNESS, _
	$ID_THE_BLACK_CURTAIN, _
	$ID_SANCTUM_CAY, _
	$ID_DROKNARS_FORGE_DEFAULT, _
	$ID_THE_FROST_GATE, _
	$ID_ICE_CAVES_OF_SORROW, _
	$ID_THUNDERHEAD_KEEP, _
	$ID_IRON_MINES_OF_MOLADUNE, _
	$ID_BORLIS_PASS, _
	$ID_TALUS_CHUTE, _
	$ID_GRIFFONS_MOUTH, _
	$ID_THE_GREAT_NORTHERN_WALL, _
	$ID_FORT_RANIK, _
	$ID_RUINS_OF_SURMIA, _
	$ID_XAQUANG_SKYWAY, _
	$ID_NOLANI_ACADEMY, _
	$ID_OLD_ASCALON, _
	$ID_THE_FISSURE_OF_WOE, _
	$ID_EMBER_LIGHT_CAMP, _
	$ID_GRENDICH_COURTHOUSE, _
	$ID_GLINTS_CHALLENGE, _
	$ID_AUGURY_ROCK, _
	$ID_SARDELAC_SANCTARIUM, _
	$ID_PIKEN_SQUARE, _
	$ID_SAGE_LANDS, _
	$ID_MAMNOON_LAGOON, _
	$ID_SILVERWOOD, _
	$ID_ETTINS_BACK, _
	$ID_REED_BOG, _
	$ID_THE_FALLS, _
	$ID_DRY_TOP, _
	$ID_TANGLE_ROOT, _
	$ID_HENGE_OF_DENRAVI, _
	$ID_TEST_MAP2, _
	$ID_SENJIS_CORNER, _
	$ID_GUILD_HALL_BURNING_ISLE, _
	$ID_TEARS_OF_THE_FALLEN, _
	$ID_SCOUNDRELS_RISE, _
	$ID_LIONS_ARCH_DEFAULT, _
	$ID_CURSED_LANDS, _
	$ID_BERGEN_HOT_SPRINGS, _
	$ID_NORTH_KRYTA_PROVINCE, _
	$ID_NEBO_TERRACE, _
	$ID_MAJESTYS_REST, _
	$ID_TWIN_SERPENT_LAKES, _
	$ID_WATCHTOWER_COAST, _
	$ID_STINGRAY_STRAND, _
	$ID_KESSEX_PEAK, _
	$ID_DALESSIO_ARENA_1, _
	$ID_ALLCALLCLICKPOINT1, _
	$ID_BURNING_ISLE_EXPLORABLE, _
	$ID_FROZEN_ISLE_EXPLORABLE, _
	$ID_NOMADS_ISLE_EXPLORABLE, _
	$ID_DRUIDS_ISLE_EXPLORABLE, _
	$ID_ISLE_OF_THE_DEAD_EXPLORABLE, _
	$ID_THE_UNDERWORLD, _
	$ID_RIVERSIDE_PROVINCE, _
	$ID_TOURNAMENT6, _
	$ID_THE_HALL_OF_HEROES_ARENA, _
	$ID_BROKEN_TOWER_ARENA, _
	$ID_HOUSE_ZU_HELTZER, _
	$ID_THE_COURTYARD_ARENA, _
	$ID_UNHOLY_TEMPLES_ARENA, _
	$ID_BURIAL_MOUNDS_ARENA, _
	$ID_ASCALON_CITY_DEFAULT, _
	$ID_TOMB_OF_THE_PRIMEVAL_KINGS_DEFAULT, _
	$ID_THE_VAULT_ARENA, _
	$ID_THE_UNDERWORLD_ARENA, _
	$ID_ASCALON_ARENA, _
	$ID_SACRED_TEMPLES_ARENA, _
	$ID_ICEDOME, _
	$ID_IRON_HORSE_MINE, _
	$ID_ANVIL_ROCK, _
	$ID_LORNARS_PASS, _
	$ID_SNAKE_DANCE, _
	$ID_TASCAS_DEMISE, _
	$ID_SPEARHEAD_PEAK, _
	$ID_ICE_FLOE, _
	$ID_WITMANS_FOLLY, _
	$ID_MINERAL_SPRINGS, _
	$ID_DREADNOUGHTS_DRIFT, _
	$ID_FROZEN_FOREST, _
	$ID_TRAVELERS_VALE, _
	$ID_DELDRIMOR_BOWL, _
	$ID_REGENT_VALLEY, _
	$ID_THE_BREACH, _
	$ID_ASCALON_FOOTILLS, _
	$ID_POCKMARK_FLATS, _
	$ID_DRAGONS_GULLET, _
	$ID_FLAME_TEMPLE_CORRIDOR, _
	$ID_EASTERN_FRONTIER, _
	$ID_THE_SCAR, _
	$ID_THE_AMNOON_OASIS, _
	$ID_DIVINERS_ASCENT, _
	$ID_VULTURE_DRIFTS, _
	$ID_THE_ARID_SEA, _
	$ID_PROPHETS_PATH, _
	$ID_SALT_FLATS, _
	$ID_SKYWARD_REACH, _
	$ID_DUNES_OF_DESPAIR, _
	$ID_THIRSTY_RIVER, _
	$ID_ELONA_REACH, _
	$ID_AUGURY_ROCK_MISSION, _
	$ID_THE_DRAGONS_LAIR, _
	$ID_PERDITION_ROCK, _
	$ID_RING_OF_FIRE, _
	$ID_ABADDONS_MOUTH, _
	$ID_HELLS_PRECIPICE, _
	$ID_TITANS_TEARS, _
	$ID_GOLDEN_GATES, _
	$ID_SCARRED_EARTH_1, _
	$ID_THE_ETERNAL_GROVE_EXPLORABLE, _
	$ID_LUTGARDIS_CONSERVATORY, _
	$ID_VASBURG_ARMORY, _
	$ID_SERENITY_TEMPLE, _
	$ID_ICE_TOOTH_CAVE, _
	$ID_BEACONS_PERCH, _
	$ID_YAKS_BEND, _
	$ID_FRONTIER_GATE, _
	$ID_BEETLETUN, _
	$ID_FISHERMENS_HAVEN, _
	$ID_TEMPLE_OF_THE_AGES, _
	$ID_VENTARIS_REFUGE, _
	$ID_DRUIDS_OVERLOOK, _
	$ID_MAGUUMA_STADE, _
	$ID_QUARREL_FALLS, _
	$ID_ASCALON_ACADEMY_DEVOUTPOST, _
	$ID_GYALA_HATCHERY_EXPLORABLE, _
	$ID_THE_CATACOMBS, _
	$ID_LAKESIDE_COUNTY, _
	$ID_THE_NORTHLANDS, _
	$ID_ASCALON_CITY_PRESEARING, _
	$ID_ASCALON_ACADEMY_DEVARENA, _
	$ID_ASCALON_ACADEMY_PVP_BATTLE, _
	$ID_ASCALON_ACADEMY_EXPLORABLE, _
	$ID_HEROES_AUDIENCE, _
	$ID_SEEKERS_PASSAGE, _
	$ID_DESTINYS_GORGE, _
	$ID_CAMP_RANKOR, _
	$ID_THE_GRANITE_CITADEL, _
	$ID_MARHANS_GROTTO, _
	$ID_PORT_SLEDGE, _
	$ID_COPPERHAMMER_MINES, _
	$ID_GREEN_HILLS_COUNTY, _
	$ID_WIZARDS_FOLLY, _
	$ID_REGENT_VALLEY_PRESEARING, _
	$ID_BARRADIN_ESTATE, _
	$ID_ASHFORD_ABBEY, _
	$ID_FOIBLES_FAIR, _
	$ID_FORT_RANIK_PRESEARING, _
	$ID_BURNING_ISLE, _
	$ID_DRUIDS_ISLE, _
	$ID_UNKNOWN_DEVMAP, _
	$ID_FROZEN_ISLE, _
	$ID_WARRIORS_ISLE, _
	$ID_HUNTERS_ISLE, _
	$ID_WIZARDS_ISLE, _
	$ID_NOMADS_ISLE, _
	$ID_ISLE_OF_THE_DEAD, _
	$ID_GUILD_HALL_FROZEN_ISLE, _
	$ID_GUILD_HALL_NOMADS_ISLE, _
	$ID_GUILD_HALL_DRUIDS_ISLE, _
	$ID_GUILD_HALL_ISLE_OF_THE_DEAD, _
	$ID_FORT_KOGA_1, _
	$ID_SHIVERPEAK_ARENA, _
	$ID_AMNOON_ARENA, _
	$ID_DELDRIMOR_ARENA, _
	$ID_THE_CRAG, _
	$ID_THE_UNDERWORLD_GUILD_BATTLE, _
	$ID_THE_UNDERWORLD_GUILD_HALL, _
	$ID_THE_UNDERWORLD_EXPLORABLE_ALT, _
	$ID_RANDOM_ARENAS, _
	$ID_TEAM_ARENAS, _
	$ID_SORROWS_FURNACE, _
	$ID_GRENTHS_FOOTPRINT, _
	$ID_CAVALON, _
	$ID_KAINENG_CENTER_DEFAULT, _
	$ID_DRAZACH_THICKET, _
	$ID_JAYA_BLUFFS, _
	$ID_SHENZUN_TUNNELS, _
	$ID_ARCHIPELAGO, _
	$ID_MAISHANG_HILLS, _
	$ID_MOUNT_QINKAI, _
	$ID_MELANDRUS_HOPE, _
	$ID_RHEAS_CRATER, _
	$ID_SILENT_SURF, _
	$ID_UNWAKING_WATERS_MISSION, _
	$ID_MOROSTAV_TRAIL, _
	$ID_DELDRIMOR_WAR_CAMP, _
	$ID_DRAGONS_THIEVES, _
	$ID_HEROES_CRYPT_1, _
	$ID_MOURNING_VEIL_FALLS, _
	$ID_FERNDALE, _
	$ID_PONGMEI_VALLEY, _
	$ID_MONASTERY_OVERLOOK, _
	$ID_ZEN_DAIJUN, _
	$ID_MINISTER_CHOS_ESTATE, _
	$ID_VIZUNAH_SQUARE, _
	$ID_NAHPUI_QUARTER, _
	$ID_TAHNAKAI_TEMPLE, _
	$ID_ARBORSTONE, _
	$ID_BOREAS_SEABED, _
	$ID_SUNJIANG_DISTRICT, _
	$ID_FORT_ASPENWOOD, _
	$ID_THE_ETERNAL_GROVE, _
	$ID_THE_JADE_QUARRY, _
	$ID_GYALA_HATCHERY, _
	$ID_RAISU_PALACE, _
	$ID_RAISU_PALACE_MISSION, _
	$ID_IMPERIAL_SANCTUM, _
	$ID_UNWAKING_WATERS_EXPLORABLE, _
	$ID_GRENZ_FRONTIER, _
	$ID_THE_ANCESTRAL_LANDS, _
	$ID_AMTZ_BASIN_EXPLORABLE, _
	$ID_AMTZ_BASIN, _
	$ID_KAANAI_CANYON, _
	$ID_SHADOWS_PASSAGE, _
	$ID_RAISU_PALACE_EXPLORABLE, _
	$ID_THE_AURIOS_MINES, _
	$ID_PANJANG_PENINSULA, _
	$ID_KINYA_PROVINCE, _
	$ID_HAIJU_LAGOON, _
	$ID_SUNQUA_VALE, _
	$ID_WAJJUN_BAZAAR, _
	$ID_BUKDEK_BYWAY, _
	$ID_THE_UNDERCITY, _
	$ID_SHING_JEA_MONASTERY_DEFAULT, _
	$ID_SHING_JEA_ARENA, _
	$ID_ARBORSTONE_EXPLORABLE, _
	$ID_MINISTER_CHOS_ESTATE_EXPLORABLE, _
	$ID_ZEN_DAIJUN_EXPLORABLE, _
	$ID_BOREAS_SEABED_EXPLORABLE, _
	$ID_GREAT_TEMPLE_OF_BALTHAZAR, _
	$ID_TSUMEI_VILLAGE, _
	$ID_SEITUNG_HARBOR, _
	$ID_RAN_MUSU_GARDENS, _
	$ID_LINNOK_COURTYARD, _
	$ID_DWAYNA_VS_GRENTH, _
	$ID_DWAYNA_CAMP, _
	$ID_GRENTH_CAMP, _
	$ID_SUNJIANG_DISTRICT_EXPLORABLE, _
	$ID_MINISTER_CHOS_ESTATE_MISSION, _
	$ID_ZEN_DAIJUN_MISSION, _
	$ID_THE_JADE_QUARRY_KURZICK_MISSION, _
	$ID_NAHPUI_QUARTER_MISSION, _
	$ID_TAHNAKAI_TEMPLE_MISSION, _
	$ID_ARBORSTONE_MISSION, _
	$ID_BOREAS_SEABED_MISSION, _
	$ID_SUNJIANG_DISTRICT_MISSION, _
	$ID_NAHPUI_QUARTER_EXPLORABLE, _
	$ID_URGOZS_WARREN, _
	$ID_THE_ETERNAL_GROVE_MISSION, _
	$ID_GYALA_HATCHERY_MISSION, _
	$ID_TAHNAKAI_TEMPLE_EXPLORABLE, _
	$ID_RAISU_PALACE_MISSION_2, _
	$ID_IMPERIAL_SANCTUM_MISSION, _
	$ID_ALTRUMM_RUINS, _
	$ID_ZOS_SHIVROS_CHANNEL, _
	$ID_DRAGONS_THROAT, _
	$ID_GUILD_HALL_ISLE_OF_WEPING_STONE, _
	$ID_GUILD_HALL_ISLE_OF_JADE, _
	$ID_HARVEST_TEMPLE, _
	$ID_BREAKER_HOLLOW, _
	$ID_LEVIATHAN_PITS, _
	$ID_ISLE_OF_THE_NAMELESS_1, _
	$ID_ZAISHEN_CHALLENGE, _
	$ID_ZAISHEN_ELITE, _
	$ID_MAATU_KEEP, _
	$ID_ZIN_KU_CORRIDOR, _
	$ID_MONASTERY_OVERLOOK_2, _
	$ID_BRAUER_ACADEMY, _
	$ID_DURHEIM_ARCHIVES, _
	$ID_BAI_PAASU_REACH, _
	$ID_SEAFARERS_REST, _
	$ID_BEJUNKAN_PIER, _
	$ID_VIZUNAH_SQUARE_LOCAL_QUARTER, _
	$ID_VIZUNAH_SQUARE_FOREIGN_QUARTER, _
	$ID_FORT_ASPENWOOD_LUXON, _
	$ID_FORT_ASPENWOOD_KURZICK, _
	$ID_THE_JADE_QUARRY_LUXON, _
	$ID_THE_JADE_QUARRY_KURZICK, _
	$ID_UNWAKING_WATERS_LUXON_MISSION, _
	$ID_UNWAKING_WATERS_KURZICK_MISSION, _
	$ID_SALTSPRAY_BEACH, _
	$ID_ETNARAN_KEYS, _
	$ID_RAISU_PAVILLION, _
	$ID_KAINENG_DOCKS, _
	$ID_THE_MARKETPLACE, _
	$ID_VIZUNAH_SQUARE_LOCAL_QUARTER_MISSION, _
	$ID_VIZUNAH_SQUARE_FOREIGN_QUARTER_MISSION, _
	$ID_THE_JADE_QUARRY_LUXON_MISSION, _
	$ID_THE_DEEP, _
	$ID_ASCALON_ARENA_2, _
	$ID_ANNIHILATION, _
	$ID_KILL_COUNT_TRAINING, _
	$ID_ANNIHILATION_2, _
	$ID_OBELISK_ANNIHILATION_TRAINING, _
	$ID_SAOSHANG_TRAIL, _
	$ID_SHIVERPEAK_ARENA_1, _
	$ID_UNKNOWN_BATTLE_ISLES, _
	$ID_UNKNOWN_KRYTA, _
	$ID_UNKNOWN_CANTHA, _
	$ID_DALESSIO_ARENA_2, _
	$ID_AMNOON_ARENA_1, _
	$ID_FORT_KOGA_2, _
	$ID_HEROES_CRYPT_2, _
	$ID_SHIVERPEAK_ARENA_2, _
	$ID_FORT_ASPENWOOD_KURZICK_MISSION, _
	$ID_FORT_ASPENWOOD_LUXON_MISSION, _
	$ID_THE_HARVEST_CEREMONY_KURZICK, _
	$ID_THE_HARVEST_CEREMONY_LUXON, _
	$ID_IMPERIAL_SANCTUM_EXPLORABLE, _
	$ID_SALTSPRAY_BEACH_LUXON, _
	$ID_SALTSPRAY_BEACH_KURZICK, _
	$ID_HEROES_ASCENT, _
	$ID_GRENZ_FRONTIER_LUXON, _
	$ID_GRENZ_FRONTIER_KURZICK, _
	$ID_THE_ANCESTORAL_LANDS_LUXON, _
	$ID_THE_ANCESTORAL_LANDS_KURZICK, _
	$ID_ETNARAN_KEYS_LUXON, _
	$ID_ETNARAN_KEYS_KURZICK, _
	$ID_KAANAI_CANYON_LUXON, _
	$ID_KAANAI_CANYON_KURZICK, _
	$ID_DALESSIO_ARENA_3, _
	$ID_AMNOON_ARENA_2, _
	$ID_FORT_KOGA_3, _
	$ID_HEROES_CRYPT_3, _
	$ID_SHIVERPEAK_ARENA_3, _
	$ID_THE_HALL_OF_HEROES, _
	$ID_THE_COURTYARD, _
	$ID_SCARRED_EARTH_2, _
	$ID_THE_UNDERWORLD_EXPLORABLE, _
	$ID_TANGLEWOOD_COPSE, _
	$ID_SAINT_ANJEKAS_SHRINE, _
	$ID_EREDON_TERRACE, _
	$ID_DIVINE_PATH, _
	$ID_BRAWLERS_PIT, _
	$ID_PETRIFIED_ARENA, _
	$ID_SEABED_ARENA, _
	$ID_ISLE_OF_WEPING_STONE, _
	$ID_ISLE_OF_JADE, _
	$ID_IMPERIAL_ISLE, _
	$ID_ISLE_OF_MEDITATION, _
	$ID_GUILD_HALL_IMPERIAL_ISLE, _
	$ID_GUILD_HALL_ISLE_OF_MEDITATION, _
	$ID_ISLE_OF_WEPING_STONE_EXPLORABLE, _
	$ID_ISLE_OF_JADE_EXPLORABLE, _
	$ID_IMPERIAL_ISLE_EXPLORABLE, _
	$ID_ISLE_OF_MEDITATION_EXPLORABLE, _
	$ID_RANDOM_ARENAS_TEST, _
	$ID_SHING_JEA_ARENA_TEST, _
	$ID_ALL_SKILLS, _
	$ID_DRAGON_ARENA, _
	$ID_JAHAI_BLUFFS, _
	$ID_KAMADAN_JEWEL_OF_ISTAN_MISSION, _
	$ID_MARGA_COAST, _
	$ID_FAHRANUR_EXPLORABLE, _
	$ID_SUNWARD_MARCHES, _
	$ID_ROLEPLAYING_CHARACTER, _
	$ID_BARBAROUS_SHORE, _
	$ID_CAMP_HOJANU, _
	$ID_BAHDOK_CAVENS, _
	$ID_WEHHAN_TERRACES, _
	$ID_DEJARIN_ESTATE, _
	$ID_ARKJOK_WARD, _
	$ID_YOHLON_HAVEN, _
	$ID_GANDARA_THE_MOON_FORTRESS, _
	$ID_VORTEX, _
	$ID_THE_FLOODPLAIN_OF_MAHKELEN, _
	$ID_LIONS_ARCH_DURING_SUNSPEARS_IN_KRYTA, _
	$ID_TURAIS_PROCESSION, _
	$ID_SUNSPEAR_SANCTUARY, _
	$ID_ASPENWOOD_GATE_KURZICK, _
	$ID_ASPENWOOD_GATE_LUXON, _
	$ID_JADE_FLATS_KURZICK, _
	$ID_JADE_FLATS_LUXON, _
	$ID_YATENDI_CANYONS, _
	$ID_CHANTRY_OF_SECRETS, _
	$ID_GARDEN_OF_SEBORHIN, _
	$ID_HOLDINGSOFCHOKHIN, _
	$ID_MIHANU_TOWNSHIP, _
	$ID_VEHJIN_MINES, _
	$ID_BASALT_GROTTO, _
	$ID_FORUM_HIGHLANDS, _
	$ID_KAINENG_CENTER_DURING_SUNSPEARS_IN_CANTHA, _
	$ID_SEBELKEH_BASILICA, _
	$ID_RESPLENDENT_MAKUUN, _
	$ID_HONUR_HILL, _
	$ID_WILDERNESS_OF_BAHDZA, _
	$ID_SUN_DOCKS_MISSION, _
	$ID_VEHTENDI_VALLEY, _
	$ID_YAHNUR_MARKET, _
	$ID_HERE_BE_DRAGONS_1, _
	$ID_HERE_BE_DRAGONS_2, _
	$ID_HERE_BE_DRAGONS_3, _
	$ID_HERE_BE_DRAGONS_4, _
	$ID_HERE_BE_DRAGONS_5, _
	$ID_THE_HIDDEN_CITY_OF_AHDASHIM, _
	$ID_THE_KODASH_BAZAAR, _
	$ID_LIONS_GATE, _
	$ID_MONASTERY_OVERLOOK_MISSION, _
	$ID_BEJUNKAN_PIER_MISSION, _
	$ID_LIONS_GATE_MISSION, _
	$ID_THE_MIRROR_OF_LYSS, _
	$ID_SECURE_THE_REFUGE, _
	$ID_VENTA_CEMETERY, _
	$ID_BAD_TIDE_RISING_KAMADAN_EXPLORABLE, _
	$ID_THE_TRIBUNAL, _
	$ID_KODONUR_CROSSROADS, _
	$ID_RILOHN_REFUGE, _
	$ID_POGAHN_PASSAGE, _
	$ID_MODDOK_CREVICE, _
	$ID_TIHARK_ORCHARD, _
	$ID_CONSULATE, _
	$ID_PLAIN_OF_JARIN, _
	$ID_SUNSPEAR_GREAT_HALL, _
	$ID_CLIFFS_OF_DOJOK, _
	$ID_DZAGONUR_BASTION, _
	$ID_DASHA_VESTIBULE, _
	$ID_GRAND_COURT_OF_SEBELKEH, _
	$ID_COMMAND_POST, _
	$ID_JOKOS_DOMAIN, _
	$ID_BONE_PALACE, _
	$ID_THE_RUPTURED_HEART, _
	$ID_THE_MOUTH_OF_TORMENT, _
	$ID_THE_SHATTERED_RAVINES, _
	$ID_LAIR_OF_THE_FORGOTTEN, _
	$ID_POISONED_OUTCROPS, _
	$ID_THE_SULFUROUS_WASTES, _
	$ID_THE_EBONY_CITADEL_OF_MALLYX, _
	$ID_THE_ALKALI_PAN, _
	$ID_A_LAND_OF_HEROES, _
	$ID_CRYSTAL_OVERLOOK, _
	$ID_KAMADAN_JEWEL_OF_ISTAN_DEFAULT, _
	$ID_GATE_OF_TORMENT, _
	_ ;$ID_GATE_OF_ANGUISH, _
	$ID_SECURE_THE_REFUGE_MISSION, _
	$ID_EVACUATION, _
	$ID_TEST_MAP_2, _
	$ID_NIGHTFALLEN_GARDEN, _
	$ID_CHUURHIR_FIELDS, _
	$ID_BEKNUR_HARBOR_1, _
	$ID_KODONUR_CROSSROADS_MISSION, _
	$ID_RILOHN_REFUGE_MISSION, _
	$ID_POGAHN_PASSAGE_MISSION, _
	$ID_THE_UNDERWORLD_2, _
	$ID_HEART_OF_ABADDON, _
	$ID_THE_UNDERWORLD_3, _
	$ID_NIGHTFALLEN_COAST, _
	$ID_NIGHTFALLEN_JAHAI, _
	$ID_DEPTHS_OF_MADNESS, _
	$ID_ROLLERBEETLE_RACING, _
	$ID_DOMAIN_OF_FEAR, _
	$ID_GATE_OF_FEAR, _
	$ID_DOMAIN_OF_PAIN, _
	$ID_BLOODSTONE_FEN_EXPLORABLE, _
	$ID_DOMAIN_OF_SECRETS, _
	$ID_GATE_OF_SECRETS, _
	_ ; $ID_DOMAIN_OF_ANGUISH, _ ; Gate of Anguish instead of Domain of Anguish
	$ID_GATE_OF_ANGUISH, _
	$ID_OOZE_PIT_ALT, _
	$ID_JENNURS_HORDE, _
	$ID_NUNDU_BAY, _
	$ID_GATE_OF_DESOLATION, _
	$ID_CHAMPIONS_DAWN, _
	$ID_RUINS_OF_MORAH, _
	$ID_FAHRANUR_THE_FIRST_CITY, _
	$ID_BJORA_MARCHES, _
	$ID_ZEHLON_REACH, _
	$ID_LAHTEDA_BOG, _
	$ID_ARBOR_BAY, _
	$ID_ISSNUR_ISLES, _
	$ID_BEKNUR_HARBOR_2, _
	$ID_MEHTANI_KEYS, _
	$ID_KODLONU_HAMLET, _
	$ID_ISLAND_OF_SHEKHAH, _
	$ID_JOKANUR_DIGGINGS, _
	$ID_BLACKTIDE_DEN, _
	$ID_CONSULATE_DOCKS, _
	$ID_GATE_OF_PAIN, _
	$ID_GATE_OF_MADNESS, _
	$ID_ABADDONS_GATE, _
	$ID_SUNSPEAR_ARENA, _
	$ID_UNKNOWN_KOURNA, _
	$ID_ICE_CLIFF_CHASMS, _
	$ID_BOKKA_AMPHITHEATRE, _
	$ID_RIVEN_EARTH, _
	$ID_THE_ASTRALARIUM, _
	$ID_THRONE_OF_SECRETS, _
	$ID_CHURRANU_ISLAND_ARENA, _
	$ID_SHING_JEA_MONASTERY_MISSION, _
	$ID_HAIJU_LAGOON_MISSION, _
	$ID_JAYA_BLUFFS_MISSION, _
	$ID_SEITUNG_HARBOR_MISSION, _
	$ID_TSUMEI_VILLAGE_MISSION, _
	$ID_SEITUNG_HARBOR_MISSION_2, _
	$ID_TSUMEI_VILLAGE_MISSION_2, _
	$ID_MINISTER_CHOS_ESTATE_MISSION_2, _
	$ID_DRAKKAR_LAKE, _
	$ID_ISLAND_OF_SHEKHAH_MISSION, _
	$ID_JOKANUR_DIGGINGS_MISSION, _
	$ID_BLACKTIDE_DEN_MISSION, _
	$ID_CONSULATE_DOCKS_MISSION, _
	$ID_TIHARK_ORCHARD, _
	$ID_DZAGONUR_BASTION_MISSION, _
	$ID_HIDDEN_CITY_OF_AHDASHIM_MISSION, _
	$ID_GRAND_COURT_OF_SEBELKEH_MISSION, _
	$ID_JENNURS_HORDE_MISSION, _
	$ID_NUNDU_BAY_MISSION, _
	$ID_GATES_OF_DESOLATION_MISSION, _
	$ID_RUINS_OF_MORAH_MISSION, _
	$ID_DOMAIN_OF_PAIN_MISSION, _
	$ID_GATE_OF_MADNESS_MISSION, _
	$ID_ABADDONS_GATE_MISSION, _
	$ID_GUILD_HALL_UNCHARTED_ISLE, _
	$ID_GUILD_HALL_ISLE_OF_WURMS, _
	$ID_UNCHARTED_ISLE_EXPLORABLE, _
	$ID_ISLE_OF_WURMS_EXPLORABLE, _
	$ID_UNCHARTED_ISLE, _
	$ID_ISLE_OF_WURMS, _
	$ID_AHMTUR_ARENA, _
	$ID_SUNSPEAR_ARENA_2, _
	$ID_GUILD_HALL_CORRUPTED_ISLE, _
	$ID_GUILD_HALL_ISLE_OF_SOLITUDE, _
	$ID_CORRUPTED_ISLE_EXPLORABLE, _
	$ID_ISLE_OF_SOLITUDE_EXPLORABLE, _
	$ID_CORRUPTED_ISLE, _
	$ID_ISLE_OF_SOLITUDE, _
	$ID_SUN_DOCKS, _
	$ID_CHAHBEK_VILLAGE, _
	$ID_REMAINS_OF_SAHLAHJA, _
	$ID_JAGA_MORAINE, _
	$ID_BOMBARDMENT, _
	$ID_NORRHART_DOMAINS, _
	$ID_HERO_BATTLES, _
	$ID_THE_BEACHHEAD, _
	$ID_THE_CROSSING, _
	$ID_DESERT_SANDS, _
	$ID_VARAJAR_FELLS, _
	$ID_DAJKAH_INLET, _
	$ID_THE_SHADOW_NEXUS, _
	$ID_CHAHBEK_VILLAGE_MISSION, _
	$ID_THRONE_OF_SECRETS_2, _
	$ID_SPARKFLY_SWAMP, _
	$ID_GATE_OF_THE_NIGHTFALLEN_LANDS, _
	$ID_CATHEDRAL_OF_FLAMES, _
	$ID_THE_TROUBLED_KEEPER, _
	$ID_FORTRESS_OF_JAHAI, _
	$ID_HALLS_OF_CHOKHIN, _
	$ID_CITADEL_OF_DZAGON, _
	$ID_DYNASTIC_TOMBS, _
	$ID_VERDANT_CASCADES, _
	$ID_CATHEDRAL_OF_FLAMES_LVL_1, _
	$ID_CATHEDRAL_OF_FLAMES_LVL_2, _
	$ID_MAGUS_STONES, _
	$ID_CATACOMBS_OF_KATHANDRAX_LVL_1, _
	$ID_CATACOMBS_OF_KATHANDRAX_LVL_2, _
	$ID_ALCAZIA_TANGLE, _
	$ID_RRAGARS_MENAGERIE_LVL_1, _
	$ID_RRAGARS_MENAGERIE_LVL_2, _
	$ID_RRAGARS_MENAGERIE_LVL_3, _
	$ID_OOZE_PIT, _
	$ID_SLAVERS_EXILE, _
	$ID_OOLAS_LAB_LVL_1, _
	$ID_OOLAS_LAB_LVL_2, _
	$ID_OOLAS_LAB_LVL_3, _
	$ID_SHARDS_OF_ORR_LVL_1, _
	$ID_SHARDS_OF_ORR_LVL_2, _
	$ID_SHARDS_OF_ORR_LVL_3, _
	$ID_ARACHNIS_HAUNT_LVL_1, _
	$ID_ARACHNIS_HAUNT_LVL_2, _
	$ID_BURNING_EMBERS, _
	$ID_BURNING_FURNACE, _
	$ID_BURNING_TEMPLE, _
	$ID_CATACOMBS_LUSH, _
	$ID_CATACOMBS_STONE, _
	$ID_CATACOMBS_TOMB, _
	$ID_FETID_RIVER, _
	$ID_OVERLOOK, _
	$ID_CEMETERY, _
	$ID_FORGOTTEN_SHRINES, _
	$ID_TRACK, _
	$ID_ANTECHAMBER, _
	$ID_COLLISION, _
	$ID_THE_HALL_OF_HEROES_2, _
	$ID_FROZEN_CREVASSE, _
	$ID_FROZEN_DEPLETED, _
	$ID_FROZEN_FORT, _
	$ID_VLOXEN_EXCAVATIONS_LVL_1, _
	$ID_VLOXEN_EXCAVATIONS_LVL_2, _
	$ID_VLOXEN_EXCAVATIONS_LVL_3, _
	$ID_HEART_OF_THE_SHIVERPEAKS_LVL_1, _
	$ID_HEART_OF_THE_SHIVERPEAKS_LVL_2, _
	$ID_HEART_OF_THE_SHIVERPEAKS_LVL_3, _
	$ID_THE_JOURNEY_TO_NORNHEIM_1, _
	$ID_THE_JOURNEY_TO_NORNHEIM_2, _
	$ID_BLOODSTONE_CAVES_LVL_1, _
	$ID_BLOODSTONE_CAVES_LVL_2, _
	$ID_BLOODSTONE_CAVES_LVL_3, _
	$ID_BOGROOT_GROWTHS_LVL_1, _
	$ID_BOGROOT_GROWTHS_LVL_2, _
	$ID_RAVENS_POINT_LVL_1, _
	$ID_RAVENS_POINT_LVL_2, _
	$ID_RAVENS_POINT_LVL_3, _
	$ID_SLAVERS_EXILE_LVL_1, _
	$ID_SLAVERS_EXILE_LVL_2, _
	$ID_SLAVERS_EXILE_LVL_3, _
	$ID_SLAVERS_EXILE_LVL_4, _
	$ID_VLOXS_FALLS, _
	$ID_BATTLEDEPTHS, _
	$ID_BATTLEDEPTHS_LVL_2, _
	$ID_BATTLEDEPTHS_LVL_3, _
	$ID_SEPULCHRE_OF_DRAGRIMMAR_LVL_1, _
	$ID_SEPULCHRE_OF_DRAGRIMMAR_LVL_2, _
	$ID_FROSTMAWS_BURROWS_LVL_1, _
	$ID_FROSTMAWS_BURROWS_LVL_2, _
	$ID_FROSTMAWS_BURROWS_LVL_3, _
	$ID_FROSTMAWS_BURROWS_LVL_4, _
	$ID_FROSTMAWS_BURROWS_LVL_5, _
	$ID_DARKRIME_DELVES_LVL_1, _
	$ID_DARKRIME_DELVES_LVL_2, _
	$ID_DARKRIME_DELVES_LVL_3, _
	$ID_GADDS_ENCAMPMENT, _
	$ID_UMBRAL_GROTTO, _
	$ID_RATA_SUM, _
	$ID_TARNISHED_HAVEN, _
	$ID_EYE_OF_THE_NORTH_DEFAULT, _
	$ID_SIFHALLA, _
	$ID_GUNNARS_HOLD, _
	$ID_OLAFSTEAD, _
	$ID_HALL_OF_MONUMENTS, _
	$ID_DALADA_UPLANDS, _
	$ID_DOOMLORE_SHRINE, _
	$ID_GROTHMAR_WARDOWNS, _
	$ID_LONGEYES_LEDGE, _
	$ID_SACNOTH_VALLEY, _
	$ID_CENTRAL_TRANSFER_CHAMBER, _
	$ID_CURSE_OF_THE_NORNBEAR, _
	$ID_BLOOD_WASHES_BLOOD, _
	$ID_A_GATE_TOO_FAR_LVL_1, _
	$ID_A_GATE_TOO_FAR_LVL_2, _
	$ID_A_GATE_TOO_FAR_LVL_3, _
	$ID_THE_ELUSIVE_GOLEMANCER_LVL_1, _
	$ID_THE_ELUSIVE_GOLEMANCER_LVL_2, _
	$ID_THE_ELUSIVE_GOLEMANCER_LVL_3, _
	$ID_FINDING_THE_BLOODSTONE_LVL_1, _
	$ID_FINDING_THE_BLOODSTONE_LVL_2, _
	$ID_FINDING_THE_BLOODSTONE_LVL_3, _
	$ID_GENIUS_OPERATED_LIVING_ENCHANTED_MANIFESTATION, _
	$ID_AGAINST_THE_CHARR, _
	$ID_WARBANDS_OF_BROTHERS_LVL_1, _
	$ID_WARBANDS_OF_BROTHERS_LVL_2, _
	$ID_WARBANDS_OF_BROTHERS_LVL_3, _
	$ID_ASSAULT_THE_STRONGHOLD, _
	$ID_DESTRUCTIONS_DEPTHS_LVL_1, _
	$ID_DESTRUCTIONS_DEPTHS_LVL_2, _
	$ID_DESTRUCTIONS_DEPTHS_LVL_3, _
	$ID_A_TIME_FOR_HEROES, _
	$ID_WARBANDS_TRAINING, _
	$ID_BOREAL_STATION, _
	$ID_CATACOMBS_OF_KATHANDRAX, _
	$ID_HALL_OF_PRIMORDUS, _
	$ID_ATTACK_OF_THE_NORNBEAR, _
	$ID_CINEMATIC_CAVE_NORN_CURSED, _
	$ID_CINEMATIC_STEPPE_INTERROGATION, _
	$ID_CINEMATIC_INTERIOR_RESEARCH, _
	$ID_CINEMATIC_EYE_VISION_A, _
	$ID_CINEMATIC_EYE_VISION_B, _
	$ID_CINEMATIC_EYE_VISION_C, _
	$ID_CINEMATIC_EYE_VISION_D, _
	$ID_POLYMOCK_COLISEUM, _
	$ID_POLYMOCK_GLACIER, _
	$ID_POLYMOCK_CROSSING, _
	$ID_CINEMATIC_MOUNTAIN_RESOLUTION, _
	$ID_COLD_AS_ICE, _
	$ID_BENEATH_LIONS_ARCH, _
	$ID_TUNNELS_BELOW_CANTHAA, _
	$ID_CAVERNS_BELOW_KAMADAN, _
	$ID_CINEMATIC_DWARFS_MOUNTAIN, _
	$ID_SERVICE_IN_DEFENSE_OF_THE_EYE, _
	$ID_MANO_A_NORNO, _
	$ID_SERVICE_PRACTICE_DUMMY, _
	$ID_HERO_TUTORIAL, _
	$ID_PROTOTYPE_MAP, _
	$ID_THE_NORN_FIGHTING_TOURNAMENT, _
	$ID_SNOWMEN_LAIR, _
	$ID_NORN_BRAWLING_CHAMPIONSHIP, _
	$ID_KILROYS_PUNCHOUT_TRAINING, _
	$ID_FRONIS_IRONTOES_LAIR, _
	$ID_THE_JUSTICIARS_END, _
	$ID_DESIGNER_TEST_MAP, _
	$ID_THE_GREAT_NORN_ALEMOOT, _
	$ID_VARAJAR_FELLS_2, _
	$ID_BATTLE_FOR_NORNHEIM, _
	$ID_EPILOGUE, _
	$ID_INSIDIOUS_REMNANTS, _
	$ID_UNKNOWN_ISTAN_ARENA, _
	$ID_UNKNOWN_VABBI_ARENA, _
	$ID_UNKNOWN_DESOLATION_ARENA, _
	$ID_UNKNOWN_RISE_OF_WHITE_MANTLE, _
	$ID_UNKNOWN_CHARR_MISSION, _
	$ID_ATTACK_ON_JALISS_CAMP, _
	$ID_UNKNOWN_CHARR_MISSION_2, _
	$ID_UNKNOWN_TARNISHED_COAST_MISSION, _
	$ID_UNKNOWN_CHARR_EXPLORABLE, _
	$ID_COSTUME_BRAWL, _
	$ID_WHITEFURY_RAPIDS, _
	$ID_KYSTEN_SHORE, _
	$ID_DEEPWAY_RUINS, _
	$ID_PLIKKUP_WORKS, _
	$ID_KILROYS_PUNCHOUT_TOURNAMET, _
	$ID_SPECIAL_OPS_FLAME_TEMPLE_CORRIDOR, _
	$ID_SPECIAL_OPS_GRENDICH_COURTHOUSE, _
	$ID_SPECIAL_OPS_GRENDICH_COURTHOUSE_2, _
	$ID_UNKNOWN_DEPTHS_MISSION, _
	$ID_UNKNOWN_FAR_SHIVERPEAKS_MISSION_1, _
	$ID_UNKNOWN_FAR_SHIVERPEAKS_MISSION_2, _
	$ID_UNKNOWN_FAR_SHIVERPEAKS_MISSION_3, _
	$ID_UNKNOWN_FAR_SHIVERPEAKS_MISSION_4, _
	$ID_UNKNOWN_FAR_SHIVERPEAKS_MISSION_5, _
	$ID_UNKNOWN_FAR_SHIVERPEAKS_MISSION_6, _
	$ID_UNKNOWN_FAR_SHIVERPEAKS_MISSION_7, _
	$ID_UNKNOWN_FAR_SHIVERPEAKS_MISSION_8, _
	$ID_UNKNOWN_FAR_SHIVERPEAKS_MISSION_9, _
	$ID_UNKNOWN_CHARR_MISSION_3, _
	$ID_UNKNOWN_CHARR_MISSION_4, _
	$ID_UNKNOWN_CHARR_MISSION_5, _
	$ID_UNKNOWN_CHARR_MISSION_6, _
	$ID_UNKNOWN_CHARR_MISSION_7, _
	$ID_UNKNOWN_CHARR_MISSION_8, _
	$ID_UNKNOWN_TARNISHED_COAST_MISSION_2, _
	$ID_UNKNOWN_TARNISHED_COAST_MISSION_3, _
	$ID_UNKNOWN_TARNISHED_COAST_MISSION_4, _
	$ID_UNKNOWN_TARNISHED_COAST_MISSION_5, _
	$ID_UNKNOWN_TARNISHED_COAST_MISSION_6, _
	$ID_UNKNOWN_TARNISHED_COAST_MISSION_7, _
	$ID_UNKNOWN_TARNISHED_COAST_MISSION_8, _
	$ID_UNKNOWN_DEPTHS_MISSION_2, _
	$ID_UNKNOWN_DEPTHS_MISSION_3, _
	$ID_UNKNOWN_DEPTHS_MISSION_4, _
	$ID_UNKNOWN_PROPHECIES_DEV, _
	$ID_UNKNOWN_FACTIONS_DEV, _
	$ID_UNKNOWN_NIGHTFALL_DEV, _
	$ID_UNKNOWN_TARNISHED_COAST_EOTN_MISSION, _
	$ID_UNKNOWN_TARNISHED_COAST_EOTN_MISSION_2, _
	$ID_UNKNOWN_CHARR_EOTN_MISSION, _
	$ID_UNKNOWN_CHARR_EOTN_MISSION_2, _
	$ID_UNKNOWN_CHARR_EOTN_MISSION_3, _
	$ID_UNKNOWN_DEPTHS_EOTN_MISSION, _
	$ID_UNKNOWN_DEPTHS_EOTN_MISSION_2, _
	$ID_UNKNOWN_FAR_SHIVERPEAKS_EOTN_MISSION, _
	$ID_UNKNOWN_FAR_SHIVERPEAKS_EOTN_MISSION_2, _
	$ID_UNKNOWN_FAR_SHIVERPEAKS_EOTN_MISSION_3, _
	$ID_UNKNOWN_TARNISHED_COAST_EOTN_MISSION_3, _
	$ID_THE_TENGU_ACCORDS, _
	$ID_THE_BATTLE_OF_JAHAI, _
	$ID_THE_FLIGHT_NORTH, _
	$ID_THE_RISE_OF_THE_WHITE_MANTLE, _
	$ID_UNKNOWN_MARKETPLACE, _
	$ID_THE_TENGU_ACCORDS_MISSION, _
	$ID_UNKNOWN_KRYTA_EXPLORABLE, _
	$ID_THE_BATTLE_OF_JAHAI_MISSION, _
	$ID_THE_FLIGHT_NORTH_MISSION, _
	$ID_UNKNOWN_DEV_REGION_1, _
	$ID_UNKNOWN_DEV_REGION_2, _
	$ID_SECRET_LAIR_OF_THE_SNOWMEN_LVL_1, _
	$ID_SECRET_LAIR_OF_THE_SNOWMEN_LVL_2, _
	$ID_DROKNARS_FORGE_EXPLORABLE, _
	$ID_ISLE_OF_THE_NAMELESS_2, _
	$ID_UNKNOWN_JADE_SEA_HERO_BATTLE, _
	$ID_UNKNOWN_KAINENG_GUILD_BATTLE, _
	$ID_UNKNOWN_HEROES_ASCENT_GUILD_BATTLE, _
	$ID_DEACTIVATING_ROX, _
	$ID_DEACTIVATING_POX, _
	$ID_DEACTIVATING_NOX, _
	$ID_SECRET_UNDERGROUND_LAIR, _
	$ID_GOLEM_TUTORIAL_SIMULATION, _
	$ID_SNOWBALL_DOMINANCE, _
	$ID_ZAISHEN_MENAGERIE_GROUNDS, _
	$ID_ZAISHEN_MENAGERIE, _
	$ID_CODEX_ARENA, _
	$ID_UNKNOWN_DUNGEON_1, _
	$ID_UNKNOWN_DUNGEON_2, _
	$ID_UNKNOWN_DUNGEON_3, _
	$ID_UNKNOWN_DUNGEON_4, _
	$ID_UNKNOWN_DUNGEON_5, _
	$ID_UNKNOWN_DUNGEON_6, _
	$ID_UNKNOWN_DUNGEON_7, _
	$ID_UNKNOWN_DUNGEON_8, _
	$ID_UNKNOWN_DUNGEON_9, _
	$ID_THE_UNDERWORLD_SOMETHING_WICKED_THIS_WAY_COMES, _
	$ID_THE_UNDERWORLD_DONT_FEAR_THE_REAPERS, _
	$ID_LIONS_ARCH_HALLOWEEN, _
	$ID_LIONS_ARCH_WINTERSDAY, _
	$ID_LIONS_ARCH_CANTHANS_NEW_YEAR, _
	$ID_ASCALON_CITY_WINTERSDAY, _
	$ID_DROKNARS_FORGE_HALLOWEEN, _
	$ID_DROKNARS_FORGE_WINTERSDAY, _
	$ID_TOMB_OF_THE_PRIMEVAL_KINGS_HALLOWEEN, _
	$ID_SHING_JEA_MONASTERY_DRAGON_FESTIVAL, _
	$ID_SHING_JEA_MONASTERY_CANTHAN_NEW_YEAR, _
	$ID_KAINENG_CENTER_CANTHAN_NEW_YEAR, _
	$ID_KAMADAN_JEWEL_OF_ISTAN_HALLOWEEN, _
	$ID_KAMADAN_JEWEL_OF_ISTAN_WINTERSDAY, _
	$ID_KAMADAN_JEWEL_OF_ISTAN_CANTHAN_NEW_YEAR, _
	$ID_EYE_OF_THE_NORTH_WINTERSDAY, _
	$ID_UNKNOWN_MAGUUMA_CITY, _
	$ID_UNKNOWN_KRYTA_ARENA, _
	$ID_UNKNOWN_CRYSTAL_DESERT_ARENA, _
	$ID_UNKNOWN_KOURNA_ARENA, _
	$ID_UNKNOWN_MAGUUMA_ARENA, _
	$ID_UNKNOWN_ECHOVALD_ARENA, _
	$ID_UNKNOWN_ASCALON_ARENA, _
	$ID_UNKNOWN_JADE_SEA_ARENA, _
	$ID_UNKNOWN_SHIVERPEAKS_ARENA, _
	$ID_UNKNOWN_KAINENG_ARENA, _
	$ID_UNKNOWN_FOW_ARENA, _
	$ID_UNKNOWN_ISTAN_ARENA_2, _
	$ID_UNKNOWN_SHING_JEA_ARENA_2, _
	$ID_UNKNOWN_ASCALON_ARENA_2, _
	$ID_UNKNOWN_SHIVERPEAKS_ARENA_2, _
	$ID_WAR_IN_KRYTA_TALMARK_WILDERNESS, _
	$ID_TRIAL_OF_ZINN, _
	$ID_DIVINITY_COAST_EXPLORABLE, _
	$ID_LIONS_ARCH_KEEP, _
	$ID_DALESSIO_SEABOARD_EXPLORABLE, _
	$ID_THE_BATTLE_FOR_LIONS_ARCH_EXPLORABLE, _
	$ID_RIVERSIDE_PROVINCE_EXPLORABLE, _
	$ID_WAR_IN_KRYTA_LIONS_ARCH, _
	$ID_THE_MASOLEUM, _
	$ID_RISE_MAP, _
	$ID_SHADOWS_IN_THE_JUNGLE, _
	$ID_A_VENGEANCE_OF_BLADES, _
	$ID_AUSPICIOUS_BEGINNINGS, _
	$ID_UNKNOWN_KRYTA_WIK_1, _
	$ID_UNKNOWN_MAGUUMA_WIK, _
	$ID_UNKNOWN_KRYTA_WIK_2, _
	$ID_UNKNOWN_KRYTA_WIK_3, _
	$ID_OLFSTEAD_EXPLORABLE, _
	$ID_THE_GREAT_SNOWBALL_FIGHT_CRUSH_SPIRITS, _
	$ID_THE_GREAT_SNOWBALL_FIGHT_WINTER_WONDERLAND, _
	$ID_EMBARK_BEACH, _
	$ID_UNKNOWN_SWAT_1, _
	$ID_UNKNOWN_SWAT_2, _
	$ID_WHAT_WAITS_IN_SHADOW_DRAGONS_THROAT_EXPLORABLE, _
	$ID_KAINENG_A_CHANCE_ENCOUNTER, _
	$ID_TRACKING_THE_CORRUPTION_MARKETPLACE_EXPLORABLE, _
	$ID_CANTHA_COURIER_BUKDEK_BYWAY, _
	$ID_A_TREATYS_A_TREATY_TSUMEI_VILLAGE, _
	$ID_DEADLY_CARGO_SEITUNG_HARBOR_EXPLORABLE, _
	$ID_THE_RESCUE_ATTEMPT_TAHNAKAI_TEMPLE, _
	$ID_VILOENCE_IN_THE_STREETS_WAJJUN_BAZAAR, _
	$ID_SACRED_PSYCHE, _
	$ID_CALLING_ALL_THUGS_SHADOWS_PASSAGE, _
	$ID_FINDING_JINNAI_ALTRUMM_RUINS, _
	$ID_RAID_ON_SHING_JEA_MONASTERY_SHING_JEA_MONASTERY, _
	$ID_RAID_ON_KAINENG_CENTER_KAINENG_CENTER, _
	$ID_MINISTRY_OF_OPPRESSION_WAJJUN_BAZAAR, _
	$ID_THE_FINAL_CONFRONTATION, _
	$ID_LAKESIDE_COUNTY_1070_AE, _
	$ID_ASHFORD_CATACOMBS_1070_AE _
]


Global Const $MAP_NAMES[] = [ _
	'Gladiators Arena', _
	'Dev Test Arena 1v1', _
	'Test Map', _
	'Guild Hall Warriors Isle', _
	'Guild Hall Hunters Isle', _
	'Guild Hall Wizards Isle', _
	'Warriors Isle Explorable', _
	'Hunters Isle Explorable', _
	'Wizards Isle Explorable', _
	'Bloodstone Fen', _
	'The Wilds', _
	'Aurora Glade', _
	'Diessa Lowlands', _
	'Gates of Kryta', _
	'Dalessio Seaboard', _
	'Divinity Coast', _
	'Talmark Wilderness', _
	'The Black Curtain', _
	'Sanctum Cay', _
	'Droknars Forge Default', _
	'The Frost Gate', _
	'Ice Caves of Sorrow', _
	'Thunderhead Keep', _
	'Iron Mines of Moladune', _
	'Borlis Pass', _
	'Talus Chute', _
	'Griffons Mouth', _
	'The Great Northern Wall', _
	'Fort Ranik', _
	'Ruins of Surmia', _
	'Xaquang Skyway', _
	'Nolani Academy', _
	'Old Ascalon', _
	'The Fissure of Woe', _
	'Ember Light Camp', _
	'Grendich Courthouse', _
	'Glints Challenge', _
	'Augury Rock', _
	'Sardelac Sanctarium', _
	'Piken Square', _
	'Sage Lands', _
	'Mamnoon Lagoon', _
	'Silverwood', _
	'Ettins Back', _
	'Reed Bog', _
	'The Falls', _
	'Dry Top', _
	'Tangle Root', _
	'Henge of Denravi', _
	'Test Map2', _
	'Senjis Corner', _
	'Guild Hall Burning Isle', _
	'Tears of The Fallen', _
	'Scoundrels Rise', _
	'Lions Arch Default', _
	'Cursed Lands', _
	'Bergen Hot Springs', _
	'North Kryta Province', _
	'Nebo Terrace', _
	'Majestys Rest', _
	'Twin Serpent Lakes', _
	'Watchtower Coast', _
	'Stingray Strand', _
	'Kessex Peak', _
	'Dalessio Arena 1', _
	'Allcallclickpoint1', _
	'Burning Isle Explorable', _
	'Frozen Isle Explorable', _
	'Nomads Isle Explorable', _
	'Druids Isle Explorable', _
	'Isle of The Dead Explorable', _
	'The Underworld', _
	'Riverside Province', _
	'Tournament6', _
	'The Hall of Heroes Arena', _
	'Broken Tower Arena', _
	'House Zu Heltzer', _
	'The Courtyard Arena', _
	'Unholy Temples Arena', _
	'Burial Mounds Arena', _
	'Ascalon City Default', _
	'Tomb of The Primeval Kings Default', _
	'The Vault Arena', _
	'The Underworld Arena', _
	'Ascalon Arena', _
	'Sacred Temples Arena', _
	'IceDome', _
	'Iron Horse Mine', _
	'Anvil Rock', _
	'Lornars Pass', _
	'Snake Dance', _
	'Tascas Demise', _
	'Spearhead Peak', _
	'Ice Floe', _
	'Witmans Folly', _
	'Mineral Springs', _
	'Dreadnoughts Drift', _
	'Frozen Forest', _
	'Travelers Vale', _
	'Deldrimor Bowl', _
	'Regent Valley', _
	'The Breach', _
	'Ascalon Footills', _
	'Pockmark Flats', _
	'Dragons Gullet', _
	'Flame Temple Corridor', _
	'Eastern Frontier', _
	'The Scar', _
	'The Amnoon Oasis', _
	'Diviners Ascent', _
	'Vulture Drifts', _
	'The Arid Sea', _
	'Prophets Path', _
	'Salt Flats', _
	'Skyward Reach', _
	'Dunes of Despair', _
	'Thirsty River', _
	'Elona Reach', _
	'Augury Rock Mission', _
	'The Dragons Lair', _
	'Perdition Rock', _
	'Ring of Fire', _
	'Abaddons Mouth', _
	'Hells Precipice', _
	'Titans Tears', _
	'Golden Gates', _
	'Scarred Earth 1', _
	'The Eternal Grove Explorable', _
	'Lutgardis Conservatory', _
	'Vasburg Armory', _
	'Serenity Temple', _
	'Ice Tooth Cave', _
	'Beacons Perch', _
	'Yaks Bend', _
	'Frontier Gate', _
	'Beetletun', _
	'Fishermens Haven', _
	'Temple of The Ages', _
	'VentarIs Refuge', _
	'Druids Overlook', _
	'Maguuma Stade', _
	'Quarrel Falls', _
	'Ascalon Academy DevOutpost', _
	'Gyala Hatchery Explorable', _
	'The Catacombs', _
	'Lakeside County', _
	'The Northlands', _
	'Ascalon City Presearing', _
	'Ascalon Academy DevArena', _
	'Ascalon Academy Pvp Battle', _
	'Ascalon Academy Explorable', _
	'Heroes Audience', _
	'Seekers Passage', _
	'Destinys Gorge', _
	'Camp Rankor', _
	'The Granite Citadel', _
	'Marhans Grotto', _
	'Port Sledge', _
	'Copperhammer Mines', _
	'Green Hills County', _
	'Wizards Folly', _
	'Regent Valley Presearing', _
	'Barradin Estate', _
	'Ashford Abbey', _
	'Foibles Fair', _
	'Fort Ranik Presearing', _
	'Burning Isle', _
	'Druids Isle', _
	'Unknown DevMap', _
	'Frozen Isle', _
	'Warriors Isle', _
	'Hunters Isle', _
	'Wizards Isle', _
	'Nomads Isle', _
	'Isle of The Dead', _
	'Guild Hall Frozen Isle', _
	'Guild Hall Nomads Isle', _
	'Guild Hall Druids Isle', _
	'Guild Hall Isle of The Dead', _
	'Fort Koga 1', _
	'Shiverpeak Arena', _
	'Amnoon Arena', _
	'Deldrimor Arena', _
	'The Crag', _
	'The Underworld Guild Battle', _
	'The Underworld Guild Hall', _
	'The Underworld Explorable Alt', _
	'Random Arenas', _
	'Team Arenas', _
	'Sorrows Furnace', _
	'Grenths Footprint', _
	'Cavalon', _
	'Kaineng Center Default', _
	'Drazach Thicket', _
	'Jaya Bluffs', _
	'Shenzun Tunnels', _
	'Archipelago', _
	'Maishang Hills', _
	'Mount Qinkai', _
	'Melandus Hope', _
	'Rheas Crater', _
	'Silent Surf', _
	'Unwaking Waters Mission', _
	'Morostav Trail', _
	'Deldrimor War Camp', _
	'Dragons Thieves', _
	'Heroes Crypt 1', _
	'Mourning Veil Falls', _
	'Ferndale', _
	'Pongmei Valley', _
	'Monastery Overlook', _
	'Zen Daijun', _
	'Minister Chos Estate', _
	'Vizunah Square', _
	'Nahpui Quarter', _
	'Tahnakai Temple', _
	'Arborstone', _
	'Boreas Seabed', _
	'Sunjiang District', _
	'Fort Aspenwood', _
	'The Eternal Grove', _
	'The Jade Quarry', _
	'Gyala Hatchery', _
	'Raisu Palace', _
	'Raisu Palace Mission', _
	'Imperial Sanctum', _
	'Unwaking Waters Explorable', _
	'Grenz Frontier', _
	'The Ancestral Lands', _
	'Amtz Basin Explorable', _
	'Amtz Basin', _
	'Kaanai Canyon', _
	'Shadows Passage', _
	'Raisu Palace Explorable', _
	'The Aurios Mines', _
	'Panjang Peninsula', _
	'Kinya Province', _
	'Haiju Lagoon', _
	'Sunqua Vale', _
	'Wajjun Bazaar', _
	'Bukdek Byway', _
	'The Undercity', _
	'Shing Jea Monastery Default', _
	'Shing Jea Arena', _
	'Arborstone Explorable', _
	'Minister Chos Estate Explorable', _
	'Zen Daijun Explorable', _
	'Boreas Seabed Explorable', _
	'Great Temple of Balthazar', _
	'Tsumei Village', _
	'Seitung Harbor', _
	'Ran Musu Gardens', _
	'Linnok Courtyard', _
	'Dwayna Vs Grenth', _
	'Dwayna Camp', _
	'Grenth Camp', _
	'Sunjiang District Explorable', _
	'Minister Chos Estate Mission', _
	'Zen Daijun Mission', _
	'The Jade Quarry Kurzick Mission', _
	'Nahpui Quarter Mission', _
	'Tahnakai Temple Mission', _
	'Arborstone Mission', _
	'Boreas Seabed Mission', _
	'Sunjiang District Mission', _
	'Nahpui Quarter Explorable', _
	'Urgozs Warren', _
	'The Eternal Grove Mission', _
	'Gyala Hatchery Mission', _
	'Tahnakai Temple Explorable', _
	'Raisu Palace Mission 2', _
	'Imperial Sanctum Mission', _
	'Altrumm Ruins', _
	'Zos Shivros Channel', _
	'Dragons Throat', _
	'Guild Hall Isle of Weping Stone', _
	'Guild Hall Isle of Jade', _
	'Harvest Temple', _
	'Breaker Hollow', _
	'Leviathan Pits', _
	'Isle of The Nameless 1', _
	'Zaishen Challenge', _
	'Zaishen Elite', _
	'Maatu Keep', _
	'Zin Ku Corridor', _
	'Monastery Overlook 2', _
	'Brauer Academy', _
	'Durheim Archives', _
	'Bai Paasu Reach', _
	'Seafarers Rest', _
	'Bejunkan Pier', _
	'Vizunah Square Local Quarter', _
	'Vizunah Square Foreign Quarter', _
	'Fort Aspenwood Luxon', _
	'Fort Aspenwood Kurzick', _
	'The Jade Quarry Luxon', _
	'The Jade Quarry Kurzick', _
	'Unwaking Waters Luxon Mission', _
	'Unwaking Waters Kurzick Mission', _
	'SaltSpray Beach', _
	'Etnaran Keys', _
	'Raisu Pavillion', _
	'Kaineng Docks', _
	'The Marketplace', _
	'Vizunah Square Local Quarter Mission', _
	'Vizunah Square Foreign Quarter Mission', _
	'The Jade Quarry Luxon Mission', _
	'The Deep', _
	'Ascalon Arena 2', _
	'Annihilation', _
	'Kill Count Training', _
	'Annihilation 2', _
	'Obelisk Annihilation Training', _
	'Saoshang Trail', _
	'Shiverpeak Arena', _
	'Unknown Battle Isles', _
	'Unknown Kryta', _
	'Unknown Cantha', _
	'Dalessio Arena 2', _
	'Amnoon Arena 1', _
	'Fort Koga 2', _
	'Heroes Crypt 2', _
	'Shiverpeak Arena 2', _
	'Fort Aspenwood Kurzick Mission', _
	'Fort Aspenwood Luxon Mission', _
	'The Harvest Ceremony Kurzick', _
	'The Harvest Ceremony Luxon', _
	'Imperial Sanctum Explorable', _
	'SaltSpray Beach Luxon', _
	'SaltSpray Beach Kurzick', _
	'Heroes Ascent', _
	'Grenz Frontier Luxon', _
	'Grenz Frontier Kurzick', _
	'The Anestoral Lands Luxon', _
	'The Anestoral Lands Kurzick', _
	'Etnaran Keys Luxon', _
	'Etnaran Keys Kurzick', _
	'Kaanai Canyon Luxon', _
	'Kaanai Canyon Kurzick', _
	'Dalessio Arena 3', _
	'Amnoon Arena 2', _
	'Fort Koga 3', _
	'Heroes Crypt 3', _
	'Shiverpeak Arena 3', _
	'The Hall of Heroes', _
	'The Courtyard', _
	'Scarred Earth 2', _
	'The Underworld Explorable', _
	'Tanglewood Copse', _
	'Saint Anjekas Shrine', _
	'Eredon Terrace', _
	'Divine Path', _
	'Brawlers Pit', _
	'Petrified Arena', _
	'Seabed Arena', _
	'Weping Stone Isle', _
	'Jade Isle', _
	'Imperial Isle', _
	'Isle of Meditation', _
	'Guild Hall Imperial Isle', _
	'Guild Hall Isle of Meditation', _
	'Weping Stone Explorable', _
	'Jade Explorable', _
	'Imperial Explorable', _
	'Meditation Explorable', _
	'Random Arenas Test', _
	'Shing Jea Arena Test', _
	'All Skills', _
	'Dragon Arena', _
	'Jahai Bluffs', _
	'Kamadan Jewel of Istan Mission', _
	'Marga Coast', _
	'Fahranur Explorable', _
	'Sunward Marches', _
	'Roleplaying Character', _
	'Barbarous Shore', _
	'Camp Hojanu', _
	'Bahdok Caverns', _
	'Wehhan Terraces', _
	'Dejarin Estate', _
	'Arkjok Ward', _
	'Yohlon Haven', _
	'Gandara The Moon Fortress', _
	'Vortex', _
	'The Floodplain of Mahkelen', _
	'Lions Arch During Sunspears In Kryta', _
	'Turais Procession', _
	'Sunspear Sanctuary', _
	'Aspenwood Gate Kurzick', _
	'Aspenwood Gate Luxon', _
	'Jade Flats Kurzick', _
	'Jade Flats Luxon', _
	'Yatendi Canyons', _
	'Chantry of Secrets', _
	'Garden of Seborhin', _
	'HoldingsOfChokhin', _
	'Mihanu Township', _
	'Vehjin Mines', _
	'Basalt Grotto', _
	'Forum Highlands', _
	'Kaineng Center During Sunspears In Cantha', _
	'Sebelkeh Basilica', _
	'Resplendent Makuun', _
	'Honur Hill', _
	'Wilderness of Bahdza', _
	'Sun Docks Mission', _
	'Vehtendi Valley', _
	'Yahnur Market', _
	'Here Be Dragons 1', _
	'Here Be Dragons 2', _
	'Here Be Dragons 3', _
	'Here Be Dragons 4', _
	'Here Be Dragons 5', _
	'The Hidden City of Ahdashim', _
	'The Kodash Bazaar', _
	'Lions Gate', _
	'Monastery Overlook Mission', _
	'Bejunkan Pier Mission', _
	'Lions Gate Mission', _
	'The Mirror of Lyss', _
	'Secure The Refuge', _
	'Venta Cemetery', _
	'Bad Tide Rising Kamadan Explorable', _
	'The Tribunal', _
	'Kodonur Crossroads', _
	'Rilohn Refuge', _
	'Pogahn Passage', _
	'Moddok Crevice', _
	'Tihark Orchard', _
	'Consulate', _
	'Plain of Jarin', _
	'Sunspear Great Hall', _
	'Cliffs of Dojok', _
	'Dzagonur Bastion', _
	'Dasha Vestibule', _
	'Grand Court of Sebelkeh', _
	'Command Post', _
	'Jokos Domain', _
	'Bone Palace', _
	'The Ruptured Heart', _
	'The Mouth of Torment', _
	'The Shattered Ravines', _
	'Lair of The Forgotten', _
	'Poisoned Outcrops', _
	'The Sulfurous Wastes', _
	'The Ebony Citadel of Mallyx', _
	'The Alkali Pan', _
	'A Land of Heroes', _
	'Crystal Overlook', _
	'Kamadan Jewel of Istan Default', _
	'Gate of Torment', _
	_ ; 'Gate of Anguish', _
	'Secure The Refuge Mission', _
	'Evacuation', _
	'Test Map 2', _
	'Nightfallen Garden', _
	'Chuurhir Fields', _
	'Beknur Harbor 1', _
	'Kodonur Crossroads Mission', _
	'Rilohn Refuge Mission', _
	'Pogahn Passage Mission', _
	'The Underworld 2', _
	'Heart of Abaddon', _
	'The Underworld 3', _
	'Nightfallen Coast', _
	'Nightfallen Jahai', _
	'Depths of Madness', _
	'Rollerbeetle Racing', _
	'Domain of Fear', _
	'Gate of Fear', _
	'Domain of Pain', _
	'Bloodstone Fen Explorable', _
	'Domain of Secrets', _
	'Gate of Secrets', _
	_ ; 'Domain of Anguish', _ ; Gate of Anguish instead of Domain of Anguish
	'Gate of Anguish', _
	'Ooze Pit Alt', _
	'Jennurs Horde', _
	'Nundu Bay', _
	'Gate of Desolation', _
	'Champions Dawn', _
	'Ruins of Morah', _
	'Fahranur The First City', _
	'Bjora Marches', _
	'Zehlon Reach', _
	'Lahteda Bog', _
	'Arbor Bay', _
	'Issnur Isles', _
	'Beknur Harbor 2', _
	'MehTani Keys', _
	'Kodlonu Hamlet', _
	'Island of Shekhah', _
	'Jokanur Diggings', _
	'Blacktide Den', _
	'Consulate Docks', _
	'Gate of Pain', _
	'Gate of Madness', _
	'Abaddons Gate', _
	'Sunspear Arena', _
	'Unknown Kourna', _
	'Ice Cliff Chasms', _
	'Bokka Amphitheatre', _
	'Riven Earth', _
	'The Astralarium', _
	'Throne of Secrets', _
	'Churranu Island Arena', _
	'Shing Jea Monastery Mission', _
	'Haiju Lagoon Mission', _
	'Jaya Bluffs Mission', _
	'Seitung Harbor Mission', _
	'Tsumei Village Mission', _
	'Seitung Harbor Mission 2', _
	'Tsumei Village Mission 2', _
	'Minister Chos Estate Mission 2', _
	'Drakkar Lake', _
	'Island of Shekhah Mission', _
	'Jokanur Diggings Mission', _
	'Blacktide Den Mission', _
	'Consulate Docks Mission', _
	'Tihark Orchard', _
	'Dzagonur Bastion Mission', _
	'Hidden City of Ahdashim Mission', _
	'Grand Court of Sebelkeh Mission', _
	'Jennurs Horde Mission', _
	'Nundu Bay Mission', _
	'Gates of Desolation Mission', _
	'Ruins of Morah Mission', _
	'Domain of Pain Mission', _
	'Gate of Madness Mission', _
	'Abaddons Gate Mission', _
	'Guild Hall Uncharted Isle', _
	'Guild Hall Isle of Wurms', _
	'Uncharted Isle Explorable', _
	'Wurms Isle Explorable', _
	'Uncharted Isle', _
	'Wurms Isle', _
	'Ahmtur Arena', _
	'Sunspear Arena 2', _
	'Guild Hall Corrupted Isle', _
	'Guild Hall Isle of Solitude', _
	'Corrupted Isle Explorable', _
	'Isle of Solitude Explorable', _
	'Corrupted Isle', _
	'Isle of Solitude', _
	'Sun Docks', _
	'Chahbek Village', _
	'Remains of Sahlahja', _
	'Jaga Moraine', _
	'Bombardment', _
	'Norrhart Domains', _
	'Hero Battles', _
	'The Beachhead', _
	'The Crossing', _
	'Desert Sands', _
	'Varajar Fells', _
	'Dajkah Inlet', _
	'The Shadow Nexus', _
	'Chahbek Village Mission', _
	'Throne of Secrets 2', _
	'Sparkfly Swamp', _
	'Gate of The Nightfallen Lands', _
	'Cathedral of Flames', _
	'The Troubled Keeper', _
	'Fortress of Jahai', _
	'Halls of Chokhin', _
	'Citadel of Dzagon', _
	'Dynastic Tombs', _
	'Verdant Cascades', _
	'Cathedral of Flames Lvl 1', _
	'Cathedral of Flames Lvl 2', _
	'Magus Stones', _
	'Catacombs of Kathandrax Lvl 1', _
	'Catacombs of Kathandrax Lvl 2', _
	'Alcazia Tangle', _
	'Rragars Menagerie Lvl 1', _
	'Rragars Menagerie Lvl 2', _
	'Rragars Menagerie Lvl 3', _
	'Ooze Pit', _
	'Slavers Exile', _
	'Oolas Lab Lvl 1', _
	'Oolas Lab Lvl 2', _
	'Oolas Lab Lvl 3', _
	'Shards of Orr Lvl 1', _
	'Shards of Orr Lvl 2', _
	'Shards of Orr Lvl 3', _
	'Arachnis Haunt Lvl 1', _
	'Arachnis Haunt Lvl 2', _
	'Burning Embers', _
	'Burning Furnace', _
	'Burning Temple', _
	'Catacombs Lush', _
	'Catacombs Stone', _
	'Catacombs Tomb', _
	'Fetid River', _
	'Overlook', _
	'Cemetery', _
	'Forgotten Shrines', _
	'Track', _
	'Antechamber', _
	'Collision', _
	'The Hall of Heroes 2', _
	'Frozen Crevasse', _
	'Frozen Depleted', _
	'Frozen Fort', _
	'Vloxen Excavations Lvl 1', _
	'Vloxen Excavations Lvl 2', _
	'Vloxen Excavations Lvl 3', _
	'Heart of The Shiverpeaks Lvl 1', _
	'Heart of The Shiverpeaks Lvl 2', _
	'Heart of The Shiverpeaks Lvl 3', _
	'The Journey To Nornheim 1', _
	'The Journey To Nornheim 2', _
	'Bloodstone Caves Lvl 1', _
	'Bloodstone Caves Lvl 2', _
	'Bloodstone Caves Lvl 3', _
	'Bogroot Growths Lvl 1', _
	'Bogroot Growths Lvl 2', _
	'Ravens Point Lvl 1', _
	'Ravens Point Lvl 2', _
	'Ravens Point Lvl 3', _
	'Slavers Exile Lvl 1', _
	'Slavers Exile Lvl 2', _
	'Slavers Exile Lvl 3', _
	'Slavers Exile Lvl 4', _
	'Vloxs Falls', _
	'Battledepths', _
	'Battledepths Lvl 2', _
	'Battledepths Lvl 3', _
	'Sepulchre of Dragrimmar Lvl 1', _
	'Sepulchre of Dragrimmar Lvl 2', _
	'Frostmaws Burrows Lvl 1', _
	'Frostmaws Burrows Lvl 2', _
	'Frostmaws Burrows Lvl 3', _
	'Frostmaws Burrows Lvl 4', _
	'Frostmaws Burrows Lvl 5', _
	'Darkrime Delves Lvl 1', _
	'Darkrime Delves Lvl 2', _
	'Darkrime Delves Lvl 3', _
	'Gadds Encampment', _
	'Umbral Grotto', _
	'Rata Sum', _
	'Tarnished Haven', _
	'Eye of The North Default', _
	'Sifhalla', _
	'Gunnars Hold', _
	'Olafstead', _
	'Hall of Monuments', _
	'Dalada Uplands', _
	'Doomlore Shrine', _
	'Grothmar Wardowns', _
	'Longeyes Ledge', _
	'Sacnoth Valley', _
	'Central Transfer Chamber', _
	'Curse of The Nornbear', _
	'Blood Washes Blood', _
	'A Gate Too Far Lvl 1', _
	'A Gate Too Far Lvl 2', _
	'A Gate Too Far Lvl 3', _
	'The Elusive Golemancer Lvl 1', _
	'The Elusive Golemancer Lvl 2', _
	'The Elusive Golemancer Lvl 3', _
	'Finding The Bloodstone Lvl 1', _
	'Finding The Bloodstone Lvl 2', _
	'Finding The Bloodstone Lvl 3', _
	'Genius Operated Living Enchanted Manifestation', _
	'Against The Charr', _
	'Warbands of Brothers Lvl 1', _
	'Warbands of Brothers Lvl 2', _
	'Warbands of Brothers Lvl 3', _
	'Assault The Stronghold', _
	'Destructions Depths Lvl 1', _
	'Destructions Depths Lvl 2', _
	'Destructions Depths Lvl 3', _
	'A Time For Heroes', _
	'Warbands Training', _
	'Boreal Station', _
	'Catacombs of Kathandrax', _
	'Hall of Primordus', _
	'Attack of The Nornbear', _
	'Cinematic Cave Norn Cursed', _
	'Cinematic Steppe Interrogation', _
	'Cinematic Interior Research', _
	'Cinematic Eye Vision A', _
	'Cinematic Eye Vision B', _
	'Cinematic Eye Vision C', _
	'Cinematic Eye Vision D', _
	'Polymock Coliseum', _
	'Polymock Glacier', _
	'Polymock Crossing', _
	'Cinematic Mountain Resolution', _
	'Cold As Ice', _
	'Beneath Lions Arch', _
	'Tunnels Below Cantha', _
	'Caverns Below Kamadan', _
	'Cinematic Dwarfs Mountain', _
	'Service In Defense of The Eye', _
	'Mano A Norno', _
	'Service Practice Dummy', _
	'Hero Tutorial', _
	'Prototype Map', _
	'The Norn Fighting Tournament', _
	'Snowmen Lair', _
	'Norn Brawling Championship', _
	'Kilroys Punchout Training', _
	'Fronis Irontoes Lair', _
	'The Justiciars End', _
	'Designer Test Map', _
	'The Great Norn Alemoot', _
	'Varajar Fells 2', _
	'Battle For Nornheim', _
	'Epilogue', _
	'Insidious Remnants', _
	'Unknown Istan Arena', _
	'Unknown Vabbi Arena', _
	'Unknown Desolation Arena', _
	'Unknown Rise of White Mantle', _
	'Unknown Charr Mission', _
	'Attack On Jaliss Camp', _
	'Unknown Charr Mission 2', _
	'Unknown Tarnished Coast Mission', _
	'Unknown Charr Explorable', _
	'Costume Brawl', _
	'Whitefury Rapids', _
	'Kysten Shore', _
	'Deepway Ruins', _
	'Plikkup Works', _
	'Kilroys Punchout Tournamet', _
	'Special Ops Flame Temple Corridor', _
	'Special Ops Grendich Courthouse', _
	'Special Ops Grendich Courthouse 2', _
	'Unknown Depths Mission', _
	'Unknown Far Shiverpeaks Mission 1', _
	'Unknown Far Shiverpeaks Mission 2', _
	'Unknown Far Shiverpeaks Mission 3', _
	'Unknown Far Shiverpeaks Mission 4', _
	'Unknown Far Shiverpeaks Mission 5', _
	'Unknown Far Shiverpeaks Mission 6', _
	'Unknown Far Shiverpeaks Mission 7', _
	'Unknown Far Shiverpeaks Mission 8', _
	'Unknown Far Shiverpeaks Mission 9', _
	'Unknown Charr Mission 3', _
	'Unknown Charr Mission 4', _
	'Unknown Charr Mission 5', _
	'Unknown Charr Mission 6', _
	'Unknown Charr Mission 7', _
	'Unknown Charr Mission 8', _
	'Unknown Tarnished Coast Mission 2', _
	'Unknown Tarnished Coast Mission 3', _
	'Unknown Tarnished Coast Mission 4', _
	'Unknown Tarnished Coast Mission 5', _
	'Unknown Tarnished Coast Mission 6', _
	'Unknown Tarnished Coast Mission 7', _
	'Unknown Tarnished Coast Mission 8', _
	'Unknown Depths Mission 2', _
	'Unknown Depths Mission 3', _
	'Unknown Depths Mission 4', _
	'Unknown Prophecies Dev', _
	'Unknown Factions Dev', _
	'Unknown Nightfall Dev', _
	'Unknown Tarnished Coast Eotn Mission', _
	'Unknown Tarnished Coast Eotn Mission 2', _
	'Unknown Charr Eotn Mission', _
	'Unknown Charr Eotn Mission 2', _
	'Unknown Charr Eotn Mission 3', _
	'Unknown Depths Eotn Mission', _
	'Unknown Depths Eotn Mission 2', _
	'Unknown Far Shiverpeaks Eotn Mission', _
	'Unknown Far Shiverpeaks Eotn Mission 2', _
	'Unknown Far Shiverpeaks Eotn Mission 3', _
	'Unknown Tarnished Coast Eotn Mission 3', _
	'The Tengu Accords', _
	'The Battle of Jahai', _
	'The Flight North', _
	'The Rise of The White Mantle', _
	'Unknown Marketplace', _
	'The Tengu Accords Mission', _
	'Unknown Kryta Explorable', _
	'The Battle of Jahai Mission', _
	'The Flight North Mission', _
	'Unknown Dev Region 1', _
	'Unknown Dev Region 2', _
	'Secret Lair of The Snowmen Lvl 1', _
	'Secret Lair of The Snowmen Lvl 2', _
	'Droknars Forge Explorable', _
	'Isle of The Nameless 2', _
	'Unknown Jade Sea Hero Battle', _
	'Unknown Kaineng Guild Battle', _
	'Unknown Heroes Ascent Guild Battle', _
	'Deactivating Rox', _
	'Deactivating Pox', _
	'Deactivating Nox', _
	'Secret Underground Lair', _
	'Golem Tutorial Simulation', _
	'Snowball Dominance', _
	'Zaishen Menagerie Grounds', _
	'Zaishen Menagerie', _
	'Codex Arena', _
	'Unknown Dungeon 1', _
	'Unknown Dungeon 2', _
	'Unknown Dungeon 3', _
	'Unknown Dungeon 4', _
	'Unknown Dungeon 5', _
	'Unknown Dungeon 6', _
	'Unknown Dungeon 7', _
	'Unknown Dungeon 8', _
	'Unknown Dungeon 9', _
	'The Underworld Something Wicked This Way Comes', _
	'The Underworld Dont Fear The Reapers', _
	'Lions Arch Halloween', _
	'Lions Arch Wintersday', _
	'Lions Arch Canthans New Year', _
	'Ascalon City Wintersday', _
	'Droknars Forge Halloween', _
	'Droknars Forge Wintersday', _
	'Tomb of The Primeval Kings Halloween', _
	'Shing Jea Monastery Dragon Festival', _
	'Shing Jea Monastery Canthan New Year', _
	'Kaineng Center Canthan New Year', _
	'Kamadan Jewel of Istan Halloween', _
	'Kamadan Jewel of Istan Wintersday', _
	'Kamadan Jewel of Istan Canthan New Year', _
	'Eye of The North Wintersday', _
	'Unknown Maguuma City', _
	'Unknown Kryta Arena', _
	'Unknown Crystal Desert Arena', _
	'Unknown KournA Arena', _
	'Unknown Maguuma Arena', _
	'Unknown Echovald Arena', _
	'Unknown Ascalon Arena', _
	'Unknown Jade Sea Arena', _
	'Unknown Shiverpeaks Arena', _
	'Unknown Kaineng Arena', _
	'Unknown Fow Arena', _
	'Unknown Istan Arena 2', _
	'Unknown Shing Jea Arena 2', _
	'Unknown Ascalon Arena 2', _
	'Unknown Shiverpeaks Arena 2', _
	'War In Kryta Talmark Wilderness', _
	'Trial of Zinn', _
	'Divinity Coast Explorable', _
	'Lions Arch Keep', _
	'Dalessio Seaboard Explorable', _
	'The Battle For Lions Arch Explorable', _
	'Riverside Province Explorable', _
	'War In Kryta Lions Arch', _
	'The Masoleum', _
	'Rise Map', _
	'Shadows In The Jungle', _
	'A Vengeance of Blades', _
	'Auspicious Beginnings', _
	'Unknown Kryta Wik 1', _
	'Unknown Maguuma Wik', _
	'Unknown Kryta Wik 2', _
	'Unknown Kryta Wik 3', _
	'Olfstead Explorable', _
	'The Great Snowball Fight Crush Spirits', _
	'The Great Snowball Fight Winter Wonderland', _
	'Embark Beach', _
	'Unknown Swat 1', _
	'Unknown Swat 2', _
	'What Waits In Shadow Dragons Throat Explorable', _
	'Kaineng A Chance Encounter', _
	'Tracking The Corruption Marketplace Explorable', _
	'Cantha Courier Bukdek Byway', _
	'A Treatys A Treaty Tsumei Village', _
	'Deadly Cargo Seitung Harbor Explorable', _
	'The Rescue Attempt Tahnakai Temple', _
	'Viloence In The Streets Wajjun Bazaar', _
	'Sacred Psyche', _
	'Calling All Thugs Shadows Passage', _
	'Finding Jinnai Altrumm Ruins', _
	'Raid On Shing Jea Monastery Shing Jea Monastery', _
	'Raid On Kaineng Center Kaineng Center', _
	'Ministry of Oppression Wajjun Bazaar', _
	'The Final Confrontation', _
	'Lakeside County 1070 AE', _
	'Ashford Catacombs 1070 AE' _
]


Global Const $MAP_NAMES_FROM_IDS				=	MapFromArrays($MAP_IDS, $MAP_NAMES)
;Global Const $MAP_IDS_FROM_NAMES				=	MapFromArrays($MAP_NAMES, $MAP_IDS)
#EndRegion Map Arrays
