#CS ===========================================================================
; Author: caustic-kronos (aka Kronos, Night, Svarog)
; Contributor: Underavelvetmoon, Gahais
; Copyright 2025 caustic-kronos
;
; Licensed under the Apache License, Version 2.0 (the 'License');
; you may not use this file except in compliance with the License.
; You may obtain a copy of the License at
; http://www.apache.org/licenses/LICENSE-2.0
;
; Unless required by applicable law or agreed to in writing, software
; distributed under the License is distributed on an 'AS IS' BASIS,
; WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
; See the License for the specific language governing permissions and
; limitations under the License.
#CE ===========================================================================

#include-once

#include <Array.au3>
#include 'Utils.au3'

;~ Determines whether the provided item has expensive mods
Func ContainsValuableUpgrades($item)
	Local $modStruct = GetModStruct($item)
	If Not $modStruct Then Return False

	If IsWeapon($item) Then
		Local $itemType	= DllStructGetData($item, 'type')
		If IsInscribable($item) Then
			For $struct In $valuable_mods_by_weapon_type[$itemType]
				If StringInStr($modStruct, $struct) > 0 Then Return True
			Next
			For $struct In $valuable_inscriptions_array
				If StringInStr($modStruct, $struct) > 0 Then Return True
			Next
		Else
			For $struct In $valuable_mods_by_os_weapon_type[$itemType]
				If StringInStr($modStruct, $struct) > 0 Then Return True
			Next
		EndIf

	ElseIf IsArmorSalvageItem($item) Then
		For $struct In $valuable_runes_and_insignias_structs_array
			If StringInStr($modStruct, $struct) > 0 Then Return True
		Next
	EndIf
	Return False
EndFunc


;~ Determines whether the provided OS (Old School) item has perfect mods
Func HasPerfectMods($item)
	Local $itemType	= DllStructGetData($item, 'type')
	Local $modstruct	= GetModStruct($item)
	Local $typeMods	= $perfect_mods_by_weapon_type[$itemType]
	Switch $itemType
		; For martial weapons, only 1 inherent mod and the weapon is perfect
		Case $ID_TYPE_AXE, $ID_TYPE_BOW, $ID_TYPE_HAMMER, $ID_TYPE_SWORD, $ID_TYPE_DAGGER
			For $struct In $typeMods
				If StringInStr($ModStruct, $struct) > 0 Then
					; If the mod found is vampiric or zealous strength, we need to check we are not mixing it with vampiric or zealous mod
					If $struct	== $STRUCT_INHERENT_ZEALOUS_STRENGTH Then
						If StringInStr($ModStruct, $STRUCT_MOD_ZEALOUS) Then ContinueLoop
					EndIf
					If $struct	== $STRUCT_INHERENT_VAMPIRIC_STRENGTH Then
						If StringInStr($ModStruct, $STRUCT_MOD_VAMPIRIC_3) Or StringInStr($ModStruct, $STRUCT_MOD_VAMPIRIC_5) Then ContinueLoop
					EndIf
					Return True
				EndIf
			Next
			Return False
		; For staff, only 1 inherent mod as well, but no risk of zealous/vampiric
		Case $ID_TYPE_STAFF
			For $struct In $typeMods
				If StringInStr($ModStruct, $struct) > 0 Then Return True
			Next
			Return False
		; For wand, offhand and shield, there are 2 inherent mods, we need to check twice
		Case $ID_TYPE_WAND, $ID_TYPE_OFFHAND, $ID_TYPE_SHIELD
			Local $count	= 0
			For $struct In $typeMods
				If StringInStr($ModStruct, $struct) > 0 Then $count += 1
			Next
			Return $count > 1
		; For scythe and spear, if you are checking this, something is wrong, there are no OS scythe or spear. Congratulations.
		Case $ID_TYPE_SCYTHE, $ID_TYPE_SPEAR
			Return True
	EndSwitch
	Return False
EndFunc


;~ Too lazy to implement this today
Func HasAlmostPerfectMods($item)
	Return HasPerfectMods($item)
EndFunc


;~ Too lazy to implement this today
Func HasOkayMods($item)
	Return HasPerfectMods($item)
EndFunc


Global Const $STRUCT_MINUS_5_ENERGY	= '0500B820'
Global Const $STRUCT_15_ENERGY	= '0F00D822'
Global Const $STRUCT_ENERGY_REGENERATION	= '0100C820'


#Region Weapon Mods
Global Const $ID_STAFF_HEAD								= 896
Global Const $ID_STAFF_WRAPPING							= 908
Global Const $ID_SHIELD_HANDLE							= 15554
Global Const $ID_FOCUS_CORE								= 15551
Global Const $ID_WAND									= 15552
Global Const $ID_BOW_STRING								= 894
Global Const $ID_BOW_GRIP								= 906
Global Const $ID_SWORD_HILT								= 897
Global Const $ID_SWORD_POMMEL							= 909
Global Const $ID_AXE_HAFT								= 893
Global Const $ID_AXE_GRIP								= 905
Global Const $ID_DAGGER_TANG							= 6323
Global Const $ID_DAGGER_HANDLE							= 6331
Global Const $ID_HAMMER_HAFT							= 895
Global Const $ID_HAMMER_GRIP							= 907
Global Const $ID_SCYTHE_SNATHE							= 15543
Global Const $ID_SCYTHE_GRIP							= 15553
Global Const $ID_SPEARHEAD								= 15544
Global Const $ID_SPEAR_GRIP								= 15555
Global Const $ID_INSCRIPTIONS_MARTIAL					= 15540
Global Const $ID_INSCRIPTIONS_OFFHAND					= 15541
Global Const $ID_INSCRIPTIONS_ALL						= 15542
Global Const $ID_INSCRIPTIONS_GENERAL					= 17059
Global Const $ID_INSCRIPTIONS_SPELLCASTING				= 19122
Global Const $ID_INSCRIPTIONS_FOCUS						= 19123
Global Const $WEAPON_MODS_ARRAY[]						= [$ID_AXE_HAFT, $ID_BOW_STRING, $ID_HAMMER_HAFT, $ID_STAFF_HEAD, $ID_SWORD_HILT, $ID_AXE_GRIP, $ID_BOW_GRIP, $ID_HAMMER_GRIP, _
															$ID_STAFF_WRAPPING, $ID_SWORD_POMMEL, $ID_DAGGER_TANG, $ID_DAGGER_HANDLE, $ID_INSCRIPTIONS_MARTIAL, _
															$ID_INSCRIPTIONS_OFFHAND, $ID_INSCRIPTIONS_ALL, $ID_SCYTHE_SNATHE, $ID_SPEARHEAD, $ID_FOCUS_CORE, $ID_WAND, _
															$ID_SCYTHE_GRIP, $ID_SHIELD_HANDLE, $ID_SPEAR_GRIP, $ID_INSCRIPTIONS_GENERAL, $ID_INSCRIPTIONS_SPELLCASTING, _
															$ID_INSCRIPTIONS_FOCUS]
Global Const $MAP_WEAPON_MODS							= MapFromArray($WEAPON_MODS_ARRAY)
#EndRegion Weapon Mods


#Region Weapon Inscriptions
#Region Common Inscriptions
Global $STRUCT_INSCRIPTION_MEASURE_FOR_MEASURE			= '1F0208243E0432251'			;salvageable
Global $STRUCT_INSCRIPTION_SHOW_ME_THE_MONEY			= '1E0208243C043225'			;rare/money

Global $STRUCT_INSCRIPTION_STRENGTH_AND_HONOR			= '0F327822'					;+15% while health > 50%
Global $STRUCT_INSCRIPTION_GUIDED_BY_FATE				= '0F006822'					;+15% while enchanted
Global $STRUCT_INSCRIPTION_DANCE_WITH_DEATH				= '0F00A822'					;+15% while in a stance
Global $STRUCT_INSCRIPTION_TOO_MUCH_INFORMATION			= '0F005822'					;+15% against hexed foes
Global $STRUCT_INSCRIPTION_TO_THE_PAIN					= '0A001820'					;+15% damage -10 armor while attacking - -10 armor part
;Global $STRUCT_INSCRIPTION_TO_THE_PAIN_2				= '0F003822'					;+15% damage -10 armor while attacking - +15% damage part
Global $STRUCT_INSCRIPTION_BRAWN_OVER_BRAIN				= $STRUCT_MINUS_5_ENERGY		;+15% damage -5 energy - -5 energy part
;Global $STRUCT_INSCRIPTION_BRAWN_OVER_BRAIN_2			= '0F003822'					;+15% damage -5 energy - +15% damage part
Global $STRUCT_INSCRIPTION_VENGEANCE_IS_MINE			= '14328822'					;+20% while health < 50%
Global $STRUCT_INSCRIPTION_DONT_FEAR_THE_REAPER			= '14009822'					;+20% while hexed
Global $STRUCT_INSCRIPTION_DONT_THINK_TWICE				= '000A0822'					;hct 10
#EndRegion Common Inscriptions

#Region Martial Inscriptions
Global $STRUCT_INSCRIPTION_I_HAVE_THE_POWER				= '0500D822'					;+5e
Global $STRUCT_INSCRIPTION_LET_THE_MEMORY_LIVE_AGAIN	= '000AA823'					;hsr 10
#EndRegion Martial Inscriptions

#Region Caster Weapon Inscriptions
Global $STRUCT_INSCRIPTION_HALE_AND_HEARTY				= '05320823'					;+5e while health > 50%
Global $STRUCT_INSCRIPTION_HAVE_FAITH					= '0500F822'					;+5e while enchanted
Global $STRUCT_INSCRIPTION_DONT_CALL_IT_A_COME_BACK		= '07321823'					;+7e while health < 50%
Global $STRUCT_INSCRIPTION_I_AM_SORROW					= '07002823'					;+7e while hexed
Global $STRUCT_INSCRIPTION_SEIZE_THE_DAY_1				= $STRUCT_15_ENERGY				;+15e energy regeneration -1 - +15e part
Global $STRUCT_INSCRIPTION_SEIZE_THE_DAY_2				= $STRUCT_ENERGY_REGENERATION	;+15e energy regeneration -1 - energy regeneration -1 part
Global $STRUCT_INSCRIPTION_APTITUDE_NOT_ATTITUDE		= '00140828'					;hct 20
#EndRegion Caster Weapon Inscriptions
#EndRegion Weapon Inscriptions

#Region Offhand Inscriptions
#Region Focus Inscriptions
Global $STRUCT_INSCRIPTION_FORGET_ME_NOT				= '00142828'					;hsr 20
Global $STRUCT_INSCRIPTION_SERENITY_NOW					= '000AA823'					;hsr 10

Global $STRUCT_INSCRIPTION_HAIL_TO_THE_KING				= '0532A821'					;+5 armor while health > 50%
Global $STRUCT_INSCRIPTION_FAITH_IS_MY_SHIELD			= '05009821'					;+5 armor while enchanted
Global $STRUCT_INSCRIPTION_MIGHT_MAKES_RIGHT			= '05007821'					;+5 armor while attacking
Global $STRUCT_INSCRIPTION_KNOWING_IS_HALF_THE_BATTLE	= '05008821'					;+5 armor while casting
Global $STRUCT_INSCRIPTION_MAN_FOR_ALL_SEASONS			= '05002821'					;+5 armor vs elemental damage
Global $STRUCT_INSCRIPTION_SURVIVAL_OF_THE_FITTEST		= '05005821'					;+5 armor vs physical damage
Global $STRUCT_INSCRIPTION_IGNORANCE_IS_BLISS_1			= '05000821'					;+5 armor ^ -5 energy - +5 armor part
Global $STRUCT_INSCRIPTION_IGNORANCE_IS_BLISS_2			= $STRUCT_MINUS_5_ENERGY		;+5 armor ^ -5 energy - -5 energy part
Global $STRUCT_INSCRIPTION_LIFE_IS_PAIN					= '1400D820'					;+5 armor ^ -20 health - -20 health part
;Global $STRUCT_INSCRIPTION_LIFE_IS_PAIN_2				= '05000821'					;+5 armor ^ -20 health - +5 armor part
Global $STRUCT_INSCRIPTION_DOWN_BUT_NOT_OUT				= '0A32B821'					;+10 armor while health < 50%
Global $STRUCT_INSCRIPTION_BE_JUST_AND_FEAR_NOT			= '0A00C821'					;+10 armor while hexed
Global $STRUCT_INSCRIPTION_LIVE_FOR_TODAY_1				= $STRUCT_15_ENERGY				;+15 energy ^ -1 energy regeneration - +15 energy part
Global $STRUCT_INSCRIPTION_LIVE_FOR_TODAY_2				= $STRUCT_ENERGY_REGENERATION	;+15 energy ^ -1 energy regeneration - energy regeneration -1 part
#EndRegion Focus Inscriptions

#Region Focus and Shield Inscriptions
Global $STRUCT_INSCRIPTION_MASTER_OF_MY_DOMAIN			= '00143828'					;+1^20% item attribute

Global $STRUCT_INSCRIPTION_NOT_THE_FACE					= '0A0018A1'					;+10 armor vs blunt
Global $STRUCT_INSCRIPTION_LEAF_ON_THE_WIND				= '0A0318A1'					;+10 armor vs cold
Global $STRUCT_INSCRIPTION_LIKE_A_ROLLING_STONE			= '0A0B18A1'					;+10 armor vs earth
Global $STRUCT_INSCRIPTION_SLEEP_NOW_IN_THE_FIRE		= '0A0518A1'					;+10 armor vs fire
Global $STRUCT_INSCRIPTION_RIDERS_ON_THE_STORM			= '0A0418A1'					;+10 armor vs lightning
Global $STRUCT_INSCRIPTION_THROUGH_THICK_AND_THIN		= '0A0118A1'					;+10 armor vs piercing
Global $STRUCT_INSCRIPTION_THE_RIDDLE_OF_STEEL			= '0A0218A1'					;+10 armor vs slashing

Global $STRUCT_INSCRIPTION_SHELTERED_BY_FAITH			= '02008820'					;-2 physical damage while enchanted
Global $STRUCT_INSCRIPTION_RUN_FOR_YOUR_LIFE			= '0200A820'					;-2 physical damage while in a stance
Global $STRUCT_INSCRIPTION_NOTHING_TO_FEAR				= '03009820'					;-3 physical damage while hexed
Global $STRUCT_INSCRIPTION_LUCK_OF_THE_DRAW				= '05147820'					;-5 physical damage ^ 20%

Global $STRUCT_INSCRIPTION_FEAR_CUTS_DEEPER				= '00005828'					;-20 bleeding duration
Global $STRUCT_INSCRIPTION_I_CAN_SEE_CLEARLY_NOW		= '00015828'					;-20 blind duration
Global $STRUCT_INSCRIPTION_SWIFT_AS_THE_WIND			= '00035828'					;-20 crippled duration
Global $STRUCT_INSCRIPTION_SOUNDNESS_OF_MIND			= '00075828'					;-20 dazed duration
Global $STRUCT_INSCRIPTION_STRENGTH_OF_BODY				= '00045828'					;-20 deep wound duration
Global $STRUCT_INSCRIPTION_CAST_OUT_THE_UNCLEAN			= '00055828'					;-20 disease duration
Global $STRUCT_INSCRIPTION_CAST_OUT_THE_UNCLEAN_OS		= 'E3017824'					;-20 disease duration
Global $STRUCT_INSCRIPTION_PURE_OF_HEART				= '00065828'					;-20 poison duration
Global $STRUCT_INSCRIPTION_ONLY_THE_STRONG_SURVIVE		= '00085828'					;-20 weakness duration								; incorrect
#EndRegion Focus and Shield Inscriptions
#EndRegion Offhand Inscriptions



#Region Mods
#Region common mods
Global $STRUCT_MOD_30_HEALTH							= '001E4823'					;+30 health
Global $STRUCT_MOD_5_ARMOR								= '05000821'					;+5 armor
Global $STRUCT_MOD_OF_SHELTER							= '07005821'					;+7 armor vs physical
Global $STRUCT_MOD_OF_WARDING							= '07002821'					;+7 armor vs elemental
Global $STRUCT_MOD_OF_ENCHANTING						= '1400B822'					;+20% enchantment duration

Global $STRUCT_MOD_OF_THE_WARRIOR						= '0511A828'
Global $STRUCT_MOD_OF_THE_RANGER						= '0517A828'
Global $STRUCT_MOD_OF_THE_NECROMANCER					= '0506A828'
Global $STRUCT_MOD_OF_THE_MESMER						= '0500A828'
Global $STRUCT_MOD_OF_THE_ELEMENTALIST					= '050CA828'
Global $STRUCT_MOD_OF_THE_MONK							= '0510A828'
Global $STRUCT_MOD_OF_THE_RITUALIST						= '0524A828'
Global $STRUCT_MOD_OF_THE_ASSASSIN						= '0523A828'
Global $STRUCT_MOD_OF_THE_PARAGON						= '0528A828'
Global $STRUCT_MOD_OF_THE_DERVISH						= '052CA828'

Global $STRUCT_MOD_OF_DEATHBANE							= '00008080'
Global $STRUCT_MOD_OF_CHARRSLAYING						= '00018080'
Global $STRUCT_MOD_OF_TROLLSLAYING						= '00028080'
Global $STRUCT_MOD_OF_PRUNING							= '00038080'
Global $STRUCT_MOD_OF_SKELETON_SLAYING					= '00048080'
Global $STRUCT_MOD_OF_GIANT_SLAYING						= '00058080'
Global $STRUCT_MOD_OF_DWARF_SLAYING						= '00068080'
Global $STRUCT_MOD_OF_TENGU_SLAYING						= '00078080'
Global $STRUCT_MOD_OF_DEMON_SLAYING						= '00088080'
Global $STRUCT_MOD_OF_OGRE_SLAYING						= '000A8080'
Global $STRUCT_MOD_OF_DRAGON_SLAYING					= '00098080'
#EndRegion common mods

#Region martial mods
Global $STRUCT_MOD_BARBED								= 'DE016824'					;+33% bleeding
Global $STRUCT_MOD_CRUEL								= 'E2016824'					;+33% deep wound
Global $STRUCT_MOD_CRIPPLING							= 'E1016824'					;+33% crippled							;Doesn't match all crippling prefixes
Global $STRUCT_MOD_HEAVY								= 'E601824'						;+33% weakness
Global $STRUCT_MOD_POISONOUS							= 'E4016824'					;+33% poison
Global $STRUCT_MOD_SILENCING							= 'E5016824'					;+33% dazed

Global $STRUCT_MOD_EBON									= '000BB824'
Global $STRUCT_MOD_FIERY								= '0005B824'
Global $STRUCT_MOD_ICY									= '0003B824'
Global $STRUCT_MOD_SHOCKING								= '0004B824'

Global $STRUCT_MOD_FURIOUS								= '0A00B823'					;adrenaline * 2 ^ 20%
Global $STRUCT_MOD_SUNDERING							= '1414F823'					;armor penetration 20^20

Global $STRUCT_MOD_VAMPIRIC_3							= '00032825'
Global $STRUCT_MOD_VAMPIRIC_5							= '00052825'
Global $STRUCT_MOD_ZEALOUS								= '01001825'
; +1^20%
Global $STRUCT_MOD_OF_AXE_MASTERY						= '14121824'
Global $STRUCT_MOD_OF_MARKSMANSHIP						= '14191824'
Global $STRUCT_MOD_OF_DAGGER_MASTERY					= '141D1824'
Global $STRUCT_MOD_OF_HAMMER_MASTERY					= '14131824'
Global $STRUCT_MOD_OF_SCYTHE_MASTERY					= '14291824'
Global $STRUCT_MOD_OF_SPEAR_MASTERY						= '14251824'
Global $STRUCT_MOD_OF_SWORDMANSHIP						= '14141824'
#EndRegion of Mastery

#Region caster weapons mods
Global $STRUCT_MOD_HCT_20								= '00140828'
Global $STRUCT_MOD_HCT_10								= '000A0822'
Global $STRUCT_MOD_HSR_20								= '00142828'
Global $STRUCT_MOD_HSR_10								= '000AA823'
#EndRegion caster weapons mods

#Region staff mods
Global $STRUCT_MOD_OF_DEVOTION							= '002D6823'					;+45 health while enchanted
Global $STRUCT_MOD_OF_ENDURANCE							= '002D8823'					;+45 health while in a stance
Global $STRUCT_MOD_OF_VALOR								= '003C7823'					;+60 health while hexed

Global $STRUCT_MOD_STAFF_MASTERY						= '00143828'					;+1^20%
#EndRegion staff mods
#EndRegion Mods


#Region inherent bonus
#Region martial weapons
Global $STRUCT_INHERENT_ZEALOUS_STRENGTH				= $STRUCT_ENERGY_REGENERATION	;+15% damage energy regeneration -1 - energy regeneration -1 part
;Global $STRUCT_INHERENT_ZEALOUS_STRENGTH_2				= '0F003822'					;+15% damage -1 energy regeneration - +15% damage part

Global $STRUCT_INHERENT_VAMPIRIC_STRENGTH				= '0100E820'					;+15% damage health regeneration -1 - health regeneration -1 part
;Global $STRUCT_INHERENT_VAMPIRIC_STRENGTH_2			= '0F003822'					;+15% damage -1 health regeneration - +15% damage part
#EndRegion martial weapons

#Region caster weapons and focus
Global $STRUCT_INHERENT_FIRE_MAGIC_HCT					= '0A141822'
Global $STRUCT_INHERENT_FIRE_MAGIC_HSR					= '0A149823'
Global $STRUCT_INHERENT_WATER_MAGIC_HCT					= '0B141822'
Global $STRUCT_INHERENT_WATER_MAGIC_HSR					= '0B149823'
Global $STRUCT_INHERENT_AIR_MAGIC_HCT					= '08141822'
Global $STRUCT_INHERENT_AIR_MAGIC_HSR					= '08149823'
Global $STRUCT_INHERENT_EARTH_MAGIC_HCT					= '09141822'
Global $STRUCT_INHERENT_EARTH_MAGIC_HSR					= '09149823'
Global $STRUCT_INHERENT_ENERGY_STORAGE_HCT				= '0C141822'
Global $STRUCT_INHERENT_ENERGY_STORAGE_HSR				= '0C149823'
Global $STRUCT_INHERENT_SMITING_PRAYERS_HCT				= '0E141822'
Global $STRUCT_INHERENT_SMITING_PRAYERS_HSR				= '0E149823'
Global $STRUCT_INHERENT_DIVINE_FAVOR_HCT				= '10141822'
Global $STRUCT_INHERENT_DIVINE_FAVOR_HSR				= '10149823'
Global $STRUCT_INHERENT_HEALING_PRAYERS_HCT				= '0D141822'
Global $STRUCT_INHERENT_HEALING_PRAYERS_HSR				= '0D149823'
Global $STRUCT_INHERENT_PROTECTION_PRAYERS_HCT			= '0F141822'
Global $STRUCT_INHERENT_PROTECTION_PRAYERS_HSR			= '0F149823'
Global $STRUCT_INHERENT_CHANNELING_MAGIC_HCT			= '22141822'
Global $STRUCT_INHERENT_CHANNELING_MAGIC_HSR			= '22149823'
Global $STRUCT_INHERENT_RESTORATION_MAGIC_HCT			= '21141822'
Global $STRUCT_INHERENT_RESTORATION_MAGIC_HSR			= '21149823'
Global $STRUCT_INHERENT_COMMUNING_HCT					= '20141822'
Global $STRUCT_INHERENT_COMMUNING_HSR					= '20149823'
Global $STRUCT_INHERENT_SPAWNING_POWER_HCT				= '24141822'
Global $STRUCT_INHERENT_SPAWNING_POWER_HSR				= '24149823'
Global $STRUCT_INHERENT_ILLUSION_MAGIC_HCT				= '01149823'
Global $STRUCT_INHERENT_ILLUSION_MAGIC_HSR				= '01141822'
Global $STRUCT_INHERENT_DOMINATION_MAGIC_HCT			= '02141822'
Global $STRUCT_INHERENT_DOMINATION_MAGIC_HSR			= '02149823'
Global $STRUCT_INHERENT_INSPIRATION_MAGIC_HCT			= '03149823'
Global $STRUCT_INHERENT_INSPIRATION_MAGIC_HSR			= '03141822'
Global $STRUCT_INHERENT_DEATH_MAGIC_HCT					= '05141822'
Global $STRUCT_INHERENT_DEATH_MAGIC_HSR					= '05149823'
Global $STRUCT_INHERENT_BLOOD_MAGIC_HCT					= '04149823'
Global $STRUCT_INHERENT_BLOOD_MAGIC_HSR					= '04141822'
Global $STRUCT_INHERENT_SOUL_REAPING_HCT				= '06149823'
Global $STRUCT_INHERENT_SOUL_REAPING_HSR				= '06141822'
Global $STRUCT_INHERENT_CURSES_HCT						= '07149823'
Global $STRUCT_INHERENT_CURSES_HSR						= '07141822'
#EndRegion caster weapons and focus

#Region focus and shield OS (Old School)
; 10 armor VS ...
Global $STRUCT_INHERENT_ARMOR_VS_UNDEAD					= '0A004821'		;'A0048210'
Global $STRUCT_INHERENT_ARMOR_VS_CHARR					= '0A014821'
Global $STRUCT_INHERENT_ARMOR_VS_TROLLS					= '0A024821'
Global $STRUCT_INHERENT_ARMOR_VS_PLANTS					= '0A034821'		;'A0348210'
Global $STRUCT_INHERENT_ARMOR_VS_SKELETONS				= '0A044821'
Global $STRUCT_INHERENT_ARMOR_VS_GIANTS					= '0A054821'
Global $STRUCT_INHERENT_ARMOR_VS_DWARVES				= '0A064821'
Global $STRUCT_INHERENT_ARMOR_VS_TENGU					= '0A074821'		;'A0748210'
Global $STRUCT_INHERENT_ARMOR_VS_DEMONS					= '0A084821'		;'A0848210'
Global $STRUCT_INHERENT_ARMOR_VS_DRAGONS				= '0A094821'		;'A0948210'
Global $STRUCT_INHERENT_ARMOR_VS_OGRES					= '0A0A4821'

; +1^19% and +1^20%
; Adding 14 to the modstruct as a prefix gives you only +1^20%
Global $STRUCT_INHERENT_OF_ILLUSION_MAGIC				= '0118240'
Global $STRUCT_INHERENT_OF_DOMINATION_MAGIC				= '0218240'
Global $STRUCT_INHERENT_OF_INSPIRATION					= '0318240'
Global $STRUCT_INHERENT_OF_BLOOD_MAGIC					= '0418240'
Global $STRUCT_INHERENT_OF_DEATH_MAGIC					= '0518240'
Global $STRUCT_INHERENT_OF_SOUL_REAPING					= '0618240'
Global $STRUCT_INHERENT_OF_CURSE_MAGIC					= '0718240'
Global $STRUCT_INHERENT_OF_AIR_MAGIC					= '0818240'
Global $STRUCT_INHERENT_OF_EARTH_MAGIC					= '0918240'
Global $STRUCT_INHERENT_OF_FIRE_MAGIC					= '0A18240'
Global $STRUCT_INHERENT_OF_WATER_MAGIC					= '0B18240'
Global $STRUCT_INHERENT_OF_HEALING_PRAYERS				= '0D18240'
Global $STRUCT_INHERENT_OF_SMITING_PRAYERS				= '0E18240'
Global $STRUCT_INHERENT_OF_PROTECTION_PRAYERS			= '0F18240'
Global $STRUCT_INHERENT_OF_DIVINE_FAVOR					= '1018240'
Global $STRUCT_INHERENT_OF_COMMUNING_MAGIC				= '2018240'
Global $STRUCT_INHERENT_OF_RESTORATION_MAGIC			= '2118240'
Global $STRUCT_INHERENT_OF_CHANNELING_MAGIC				= '2218240'
Global $STRUCT_INHERENT_OF_SPAWNING_MAGIC				= '2418240'
#EndRegion focus and shield OS (Old School)
#EndRegion inherent bonus


#Region Runes
Global Const $ID_WARRIOR_INSIGNIAS_KNIGHTS					= '19152'
Global Const $ID_WARRIOR_INSIGNIAS_LIEUTENANTS				= '19153'
Global Const $ID_WARRIOR_INSIGNIAS_STONEFIST				= '19154'
Global Const $ID_WARRIOR_INSIGNIAS_DREADNOUGHT				= '19155'
Global Const $ID_WARRIOR_INSIGNIAS_SENTINELS				= '19156'
Global Const $ID_WARRIOR_RUNES_MINOR_ABSORPTION				= '903'
Global Const $ID_WARRIOR_RUNES_MINOR_AXE_MASTERY			= '903'
Global Const $ID_WARRIOR_RUNES_MINOR_HAMMER_MASTERY			= '903'
Global Const $ID_WARRIOR_RUNES_MINOR_STRENGTH				= '903'
Global Const $ID_WARRIOR_RUNES_MINOR_SWORDSMANSHIP			= '903'
Global Const $ID_WARRIOR_RUNES_MINOR_TACTICS				= '903'
Global Const $ID_WARRIOR_RUNES_MAJOR_ABSORPTION				= '5558'
Global Const $ID_WARRIOR_RUNES_MAJOR_AXE_MASTERY			= '5558'
Global Const $ID_WARRIOR_RUNES_MAJOR_HAMMER_MASTERY			= '5558'
Global Const $ID_WARRIOR_RUNES_MAJOR_STRENGTH				= '5558'
Global Const $ID_WARRIOR_RUNES_MAJOR_SWORDSMANSHIP			= '5558'
Global Const $ID_WARRIOR_RUNES_MAJOR_TACTICS				= '5558'
Global Const $ID_WARRIOR_RUNES_SUPERIOR_AXE_MASTERY			= '5559'
Global Const $ID_WARRIOR_RUNES_SUPERIOR_HAMMER_MASTERY		= '5559'
Global Const $ID_WARRIOR_RUNES_SUPERIOR_STRENGTH			= '5559'
Global Const $ID_WARRIOR_RUNES_SUPERIOR_SWORDSMANSHIP		= '5559'
Global Const $ID_WARRIOR_RUNES_SUPERIOR_TACTICS				= '5559'
Global Const $ID_WARRIOR_RUNES_SUPERIOR_ABSORPTION			= '5559'
Global Const $ID_RANGER_INSIGNIAS_FROSTBOUND				= '19157'
Global Const $ID_RANGER_INSIGNIAS_PYREBOUND					= '19159'
Global Const $ID_RANGER_INSIGNIAS_STORMBOUND				= '19160'
Global Const $ID_RANGER_INSIGNIAS_SCOUTS					= '19162'
Global Const $ID_RANGER_INSIGNIAS_EARTHBOUND				= '19158'
Global Const $ID_RANGER_INSIGNIAS_BEASTMASTERS				= '19161'
Global Const $ID_RANGER_RUNES_MINOR_BEAST_MASTERY			= '904'
Global Const $ID_RANGER_RUNES_MINOR_EXPERTISE				= '904'
Global Const $ID_RANGER_RUNES_MINOR_MARKSMANSHIP			= '904'
Global Const $ID_RANGER_RUNES_MINOR_WILDERNESS_SURVIVAL		= '904'
Global Const $ID_RANGER_RUNES_MAJOR_BEAST_MASTERY			= '5560'
Global Const $ID_RANGER_RUNES_MAJOR_EXPERTISE				= '5560'
Global Const $ID_RANGER_RUNES_MAJOR_MARKSMANSHIP			= '5560'
Global Const $ID_RANGER_RUNES_MAJOR_WILDERNESS_SURVIVAL		= '5560'
Global Const $ID_RANGER_RUNES_SUPERIOR_BEAST_MASTERY		= '5561'
Global Const $ID_RANGER_RUNES_SUPERIOR_EXPERTISE			= '5561'
Global Const $ID_RANGER_RUNES_SUPERIOR_MARKSMANSHIP			= '5561'
Global Const $ID_RANGER_RUNES_SUPERIOR_WILDERNESS_SURVIVAL	= '5561'
Global Const $ID_MONK_INSIGNIAS_WANDERERS					= '19149'
Global Const $ID_MONK_INSIGNIAS_DISCIPLES					= '19150'
Global Const $ID_MONK_INSIGNIAS_ANCHORITES					= '19151'
Global Const $ID_MONK_RUNES_MINOR_DIVINE_FAVOR				= '902'
Global Const $ID_MONK_RUNES_MINOR_HEALING_PRAYERS			= '902'
Global Const $ID_MONK_RUNES_MINOR_PROTECTION_PRAYERS		= '902'
Global Const $ID_MONK_RUNES_MINOR_SMITING_PRAYERS			= '902'
Global Const $ID_MONK_RUNES_MAJOR_HEALING_PRAYERS			= '5556'
Global Const $ID_MONK_RUNES_MAJOR_PROTECTION_PRAYERS		= '5556'
Global Const $ID_MONK_RUNES_MAJOR_SMITING_PRAYERS			= '5556'
Global Const $ID_MONK_RUNES_MAJOR_DIVINE_FAVOR				= '5556'
Global Const $ID_MONK_RUNES_SUPERIOR_DIVINE_FAVOR			= '5557'
Global Const $ID_MONK_RUNES_SUPERIOR_HEALING_PRAYERS		= '5557'
Global Const $ID_MONK_RUNES_SUPERIOR_PROTECTION_PRAYERS		= '5557'
Global Const $ID_MONK_RUNES_SUPERIOR_SMITING_PRAYERS		= '5557'
Global Const $ID_NECROMANCER_INSIGNIAS_BLOODSTAINED			= '19138'
Global Const $ID_NECROMANCER_INSIGNIAS_TORMENTORS			= '19139'
Global Const $ID_NECROMANCER_INSIGNIAS_BONELACE				= '19141'
Global Const $ID_NECROMANCER_INSIGNIAS_MINION_MASTERS		= '19142'
Global Const $ID_NECROMANCER_INSIGNIAS_BLIGHTERS			= '19143'
Global Const $ID_NECROMANCER_INSIGNIAS_UNDERTAKERS			= '19140'
Global Const $ID_NECROMANCER_RUNES_MINOR_BLOOD_MAGIC		= '900'
Global Const $ID_NECROMANCER_RUNES_MINOR_CURSES				= '900'
Global Const $ID_NECROMANCER_RUNES_MINOR_DEATH_MAGIC		= '900'
Global Const $ID_NECROMANCER_RUNES_MINOR_SOUL_REAPING		= '900'
Global Const $ID_NECROMANCER_RUNES_MAJOR_BLOOD_MAGIC		= '5552'
Global Const $ID_NECROMANCER_RUNES_MAJOR_CURSES				= '5552'
Global Const $ID_NECROMANCER_RUNES_MAJOR_DEATH_MAGIC		= '5552'
Global Const $ID_NECROMANCER_RUNES_MAJOR_SOUL_REAPING		= '5552'
Global Const $ID_NECROMANCER_RUNES_SUPERIOR_BLOOD_MAGIC		= '5553'
Global Const $ID_NECROMANCER_RUNES_SUPERIOR_CURSES			= '5553'
Global Const $ID_NECROMANCER_RUNES_SUPERIOR_DEATH_MAGIC		= '5553'
Global Const $ID_NECROMANCER_RUNES_SUPERIOR_SOUL_REAPING	= '5553'
Global Const $ID_MESMER_INSIGNIAS_VIRTUOSOS					= '19130'
Global Const $ID_MESMER_INSIGNIAS_ARTIFICERS				= '19128'
Global Const $ID_MESMER_INSIGNIAS_PRODIGYS					= '19129'
Global Const $ID_MESMER_RUNES_MINOR_DOMINATION_MAGIC		= '899'
Global Const $ID_MESMER_RUNES_MINOR_FAST_CASTING			= '899'
Global Const $ID_MESMER_RUNES_MINOR_ILLUSION_MAGIC			= '899'
Global Const $ID_MESMER_RUNES_MINOR_INSPIRATION_MAGIC		= '899'
Global Const $ID_MESMER_RUNES_MAJOR_DOMINATION_MAGIC		= '3612'
Global Const $ID_MESMER_RUNES_MAJOR_FAST_CASTING			= '3612'
Global Const $ID_MESMER_RUNES_MAJOR_ILLUSION_MAGIC			= '3612'
Global Const $ID_MESMER_RUNES_MAJOR_INSPIRATION_MAGIC		= '3612'
Global Const $ID_MESMER_RUNES_SUPERIOR_DOMINATION_MAGIC		= '5549'
Global Const $ID_MESMER_RUNES_SUPERIOR_FAST_CASTING			= '5549'
Global Const $ID_MESMER_RUNES_SUPERIOR_ILLUSION_MAGIC		= '5549'
Global Const $ID_MESMER_RUNES_SUPERIOR_INSPIRATION_MAGIC	= '5549'
Global Const $ID_ELEMENTALIST_INSIGNIAS_HYDROMANCER			= '19145'
Global Const $ID_ELEMENTALIST_INSIGNIAS_GEOMANCER			= '19146'
Global Const $ID_ELEMENTALIST_INSIGNIAS_PYROMANCER			= '19147'
Global Const $ID_ELEMENTALIST_INSIGNIAS_AEROMANCER			= '19148'
Global Const $ID_ELEMENTALIST_INSIGNIAS_PRISMATIC			= '19144'
Global Const $ID_ELEMENTALIST_RUNES_MINOR_AIR_MAGIC			= '901'
Global Const $ID_ELEMENTALIST_RUNES_MINOR_EARTH_MAGIC		= '901'
Global Const $ID_ELEMENTALIST_RUNES_MINOR_ENERGY_STORAGE	= '901'
Global Const $ID_ELEMENTALIST_RUNES_MINOR_WATER_MAGIC		= '901'
Global Const $ID_ELEMENTALIST_RUNES_MINOR_FIRE_MAGIC		= '901'
Global Const $ID_ELEMENTALIST_RUNES_MAJOR_AIR_MAGIC			= '5554'
Global Const $ID_ELEMENTALIST_RUNES_MAJOR_EARTH_MAGIC		= '5554'
Global Const $ID_ELEMENTALIST_RUNES_MAJOR_ENERGY_STORAGE	= '5554'
Global Const $ID_ELEMENTALIST_RUNES_MAJOR_FIRE_MAGIC		= '5554'
Global Const $ID_ELEMENTALIST_RUNES_MAJOR_WATER_MAGIC		= '5554'
Global Const $ID_ELEMENTALIST_RUNES_SUPERIOR_AIR_MAGIC		= '5555'
Global Const $ID_ELEMENTALIST_RUNES_SUPERIOR_EARTH_MAGIC	= '5555'
Global Const $ID_ELEMENTALIST_RUNES_SUPERIOR_ENERGY_STORAGE	= '5555'
Global Const $ID_ELEMENTALIST_RUNES_SUPERIOR_FIRE_MAGIC		= '5555'
Global Const $ID_ELEMENTALIST_RUNES_SUPERIOR_WATER_MAGIC	= '5555'
Global Const $ID_ASSASSIN_INSIGNIAS_VANGUARDS				= '19124'
Global Const $ID_ASSASSIN_INSIGNIAS_INFILTRATORS			= '19125'
Global Const $ID_ASSASSIN_INSIGNIAS_SABOTEURS				= '19126'
Global Const $ID_ASSASSIN_INSIGNIAS_NIGHTSTALKERS			= '19127'
Global Const $ID_ASSASSIN_RUNES_MINOR_CRITICAL_STRIKES		= '6324'
Global Const $ID_ASSASSIN_RUNES_MINOR_DAGGER_MASTERY		= '6324'
Global Const $ID_ASSASSIN_RUNES_MINOR_DEADLY_ARTS			= '6324'
Global Const $ID_ASSASSIN_RUNES_MINOR_SHADOW_ARTS			= '6324'
Global Const $ID_ASSASSIN_RUNES_MAJOR_CRITICAL_STRIKES		= '6325'
Global Const $ID_ASSASSIN_RUNES_MAJOR_DAGGER_MASTERY		= '6325'
Global Const $ID_ASSASSIN_RUNES_MAJOR_DEADLY_ARTS			= '6325'
Global Const $ID_ASSASSIN_RUNES_MAJOR_SHADOW_ARTS			= '6325'
Global Const $ID_ASSASSIN_RUNES_SUPERIOR_CRITICAL_STRIKES	= '6326'
Global Const $ID_ASSASSIN_RUNES_SUPERIOR_DAGGER_MASTERY		= '6326'
Global Const $ID_ASSASSIN_RUNES_SUPERIOR_DEADLY_ARTS		= '6326'
Global Const $ID_ASSASSIN_RUNES_SUPERIOR_SHADOW_ARTS		= '6326'
Global Const $ID_RITUALIST_INSIGNIAS_SHAMANS				= '19165'
Global Const $ID_RITUALIST_INSIGNIAS_GHOST_FORGE			= '19166'
Global Const $ID_RITUALIST_INSIGNIAS_MYSTICS				= '19167'
Global Const $ID_RITUALIST_RUNES_MINOR_CHANNELING_MAGIC		= '6327'
Global Const $ID_RITUALIST_RUNES_MINOR_COMMUNING			= '6327'
Global Const $ID_RITUALIST_RUNES_MINOR_RESTORATION_MAGIC	= '6327'
Global Const $ID_RITUALIST_RUNES_MINOR_SPAWNING_POWER		= '6327'
Global Const $ID_RITUALIST_RUNES_MAJOR_CHANNELING_MAGIC		= '6328'
Global Const $ID_RITUALIST_RUNES_MAJOR_COMMUNING			= '6328'
Global Const $ID_RITUALIST_RUNES_MAJOR_RESTORATION_MAGIC	= '6328'
Global Const $ID_RITUALIST_RUNES_MAJOR_SPAWNING_POWER		= '6328'
Global Const $ID_RITUALIST_RUNES_SUPERIOR_CHANNELING_MAGIC	= '6329'
Global Const $ID_RITUALIST_RUNES_SUPERIOR_COMMUNING			= '6329'
Global Const $ID_RITUALIST_RUNES_SUPERIOR_RESTORATION_MAGIC	= '6329'
Global Const $ID_RITUALIST_RUNES_SUPERIOR_SPAWNING_POWER	= '6329'
Global Const $ID_DERVISH_INSIGNIAS_WINDWALKER				= '19163'
Global Const $ID_DERVISH_INSIGNIAS_FORSAKEN					= '19164'
Global Const $ID_DERVISH_RUNES_MINOR_EARTH_PRAYERS			= '15545'
Global Const $ID_DERVISH_RUNES_MINOR_MYSTICISM				= '15545'
Global Const $ID_DERVISH_RUNES_MINOR_SCYTHE_MASTERY			= '15545'
Global Const $ID_DERVISH_RUNES_MINOR_WIND_PRAYERS			= '15545'
Global Const $ID_DERVISH_RUNES_MAJOR_EARTH_PRAYERS			= '15546'
Global Const $ID_DERVISH_RUNES_MAJOR_MYSTICISM				= '15546'
Global Const $ID_DERVISH_RUNES_MAJOR_SCYTHE_MASTERY			= '15546'
Global Const $ID_DERVISH_RUNES_MAJOR_WIND_PRAYERS			= '15546'
Global Const $ID_DERVISH_RUNES_SUPERIOR_EARTH_PRAYERS		= '15547'
Global Const $ID_DERVISH_RUNES_SUPERIOR_MYSTICISM			= '15547'
Global Const $ID_DERVISH_RUNES_SUPERIOR_SCYTHE_MASTERY		= '15547'
Global Const $ID_DERVISH_RUNES_SUPERIOR_WIND_PRAYERS		= '15547'
Global Const $ID_PARAGON_INSIGNIAS_CENTURIONS				= '19168'
Global Const $ID_PARAGON_RUNES_MINOR_COMMAND				= '15548'
Global Const $ID_PARAGON_RUNES_MINOR_LEADERSHIP				= '15548'
Global Const $ID_PARAGON_RUNES_MINOR_MOTIVATION				= '15548'
Global Const $ID_PARAGON_RUNES_MINOR_SPEAR_MASTERY			= '15548'
Global Const $ID_PARAGON_RUNES_MAJOR_COMMAND				= '15549'
Global Const $ID_PARAGON_RUNES_MAJOR_LEADERSHIP				= '15549'
Global Const $ID_PARAGON_RUNES_MAJOR_MOTIVATION				= '15549'
Global Const $ID_PARAGON_RUNES_MAJOR_SPEAR_MASTERY			= '15549'
Global Const $ID_PARAGON_RUNES_SUPERIOR_COMMAND				= '15550'
Global Const $ID_PARAGON_RUNES_SUPERIOR_LEADERSHIP			= '15550'
Global Const $ID_PARAGON_RUNES_SUPERIOR_MOTIVATION			= '15550'
Global Const $ID_PARAGON_RUNES_SUPERIOR_SPEAR_MASTERY		= '15550'
Global Const $ID_INSIGNIAS_SURVIVOR							= '19132'
Global Const $ID_INSIGNIAS_RADIANT							= '19131'
Global Const $ID_INSIGNIAS_STALWART							= '19133'
Global Const $ID_INSIGNIAS_BRAWLERS							= '19134'
Global Const $ID_INSIGNIAS_BLESSED							= '19135'
Global Const $ID_INSIGNIAS_HERALDS							= '19136'
Global Const $ID_INSIGNIAS_SENTRYS							= '19137'
Global Const $ID_RUNES_MINOR_VIGOR							= '898'
Global Const $ID_RUNES_VITAE								= '898'
Global Const $ID_RUNES_ATTUNEMENT							= '898'
Global Const $ID_RUNES_MAJOR_VIGOR							= '5550'
Global Const $ID_RUNES_RECOVERY								= '5550'
Global Const $ID_RUNES_RESTORATION							= '5550'
Global Const $ID_RUNES_CLARITY								= '5550'
Global Const $ID_RUNES_PURITY								= '5550'
Global Const $ID_RUNES_SUPERIOR_VIGOR						= '5551'


Global Const $STRUCT_WARRIOR_INSIGNIAS_KNIGHTS					= 'F9010824'
Global Const $STRUCT_WARRIOR_INSIGNIAS_LIEUTENANTS				= '08020824'
Global Const $STRUCT_WARRIOR_INSIGNIAS_STONEFIST				= '09020824'
Global Const $STRUCT_WARRIOR_INSIGNIAS_DREADNOUGHT				= 'FA010824'
Global Const $STRUCT_WARRIOR_INSIGNIAS_SENTINELS				= 'FB010824'
Global Const $STRUCT_WARRIOR_RUNES_MINOR_ABSORPTION				= 'EA02E827'
Global Const $STRUCT_WARRIOR_RUNES_MINOR_AXE_MASTERY			= '0112E821'
Global Const $STRUCT_WARRIOR_RUNES_MINOR_HAMMER_MASTERY			= '0113E821'
Global Const $STRUCT_WARRIOR_RUNES_MINOR_STRENGTH				= '0111E821'
Global Const $STRUCT_WARRIOR_RUNES_MINOR_SWORDSMANSHIP			= '0114E821'
Global Const $STRUCT_WARRIOR_RUNES_MINOR_TACTICS				= '0115E821'
Global Const $STRUCT_WARRIOR_RUNES_MAJOR_ABSORPTION				= 'EA02E927'
Global Const $STRUCT_WARRIOR_RUNES_MAJOR_AXE_MASTERY			= '0212E8217301'
Global Const $STRUCT_WARRIOR_RUNES_MAJOR_HAMMER_MASTERY			= '0213E8217301'
Global Const $STRUCT_WARRIOR_RUNES_MAJOR_STRENGTH				= '0211E8217301'
Global Const $STRUCT_WARRIOR_RUNES_MAJOR_SWORDSMANSHIP			= '0214E8217301'
Global Const $STRUCT_WARRIOR_RUNES_MAJOR_TACTICS				= '0215E8217301'
Global Const $STRUCT_WARRIOR_RUNES_SUPERIOR_AXE_MASTERY			= '0312E8217F01'
Global Const $STRUCT_WARRIOR_RUNES_SUPERIOR_HAMMER_MASTERY		= '0313E8217F01'
Global Const $STRUCT_WARRIOR_RUNES_SUPERIOR_STRENGTH			= '0311E8217F01'
Global Const $STRUCT_WARRIOR_RUNES_SUPERIOR_SWORDSMANSHIP		= '0314E8217F01'
Global Const $STRUCT_WARRIOR_RUNES_SUPERIOR_TACTICS				= '0315E8217F01'
Global Const $STRUCT_WARRIOR_RUNES_SUPERIOR_ABSORPTION			= 'EA02EA27'
Global Const $STRUCT_RANGER_INSIGNIAS_FROSTBOUND				= 'FC010824'
Global Const $STRUCT_RANGER_INSIGNIAS_PYREBOUND					= 'FE010824'
Global Const $STRUCT_RANGER_INSIGNIAS_STORMBOUND				= 'FF010824'
Global Const $STRUCT_RANGER_INSIGNIAS_SCOUTS					= '01020824'
Global Const $STRUCT_RANGER_INSIGNIAS_EARTHBOUND				= 'FD010824'
Global Const $STRUCT_RANGER_INSIGNIAS_BEASTMASTERS				= '00020824'
Global Const $STRUCT_RANGER_RUNES_MINOR_BEAST_MASTERY			= '0116E821'
Global Const $STRUCT_RANGER_RUNES_MINOR_EXPERTISE				= '0117E821'
Global Const $STRUCT_RANGER_RUNES_MINOR_MARKSMANSHIP			= '0119E821'
Global Const $STRUCT_RANGER_RUNES_MINOR_WILDERNESS_SURVIVAL		= '0118E821'
Global Const $STRUCT_RANGER_RUNES_MAJOR_BEAST_MASTERY			= '0216E8217501'
Global Const $STRUCT_RANGER_RUNES_MAJOR_EXPERTISE				= '0217E8217501'
Global Const $STRUCT_RANGER_RUNES_MAJOR_MARKSMANSHIP			= '0219E8217501'
Global Const $STRUCT_RANGER_RUNES_MAJOR_WILDERNESS_SURVIVAL		= '0218E8217501'
Global Const $STRUCT_RANGER_RUNES_SUPERIOR_BEAST_MASTERY		= '0316E8218101'
Global Const $STRUCT_RANGER_RUNES_SUPERIOR_EXPERTISE			= '0317E8218101'
Global Const $STRUCT_RANGER_RUNES_SUPERIOR_MARKSMANSHIP			= '0319E8218101'
Global Const $STRUCT_RANGER_RUNES_SUPERIOR_WILDERNESS_SURVIVAL	= '0318E8218101'
Global Const $STRUCT_MONK_INSIGNIAS_WANDERERS					= 'F6010824'
Global Const $STRUCT_MONK_INSIGNIAS_DISCIPLES					= 'F7010824'
Global Const $STRUCT_MONK_INSIGNIAS_ANCHORITES					= 'F8010824'
Global Const $STRUCT_MONK_RUNES_MINOR_DIVINE_FAVOR				= '0110E821'
Global Const $STRUCT_MONK_RUNES_MINOR_HEALING_PRAYERS			= '010DE821'
Global Const $STRUCT_MONK_RUNES_MINOR_PROTECTION_PRAYERS		= '010FE821'
Global Const $STRUCT_MONK_RUNES_MINOR_SMITING_PRAYERS			= '010EE821'
Global Const $STRUCT_MONK_RUNES_MAJOR_HEALING_PRAYERS			= '020DE8217101'
Global Const $STRUCT_MONK_RUNES_MAJOR_PROTECTION_PRAYERS		= '020FE8217101'
Global Const $STRUCT_MONK_RUNES_MAJOR_SMITING_PRAYERS			= '020EE8217101'
Global Const $STRUCT_MONK_RUNES_MAJOR_DIVINE_FAVOR				= '0210E8217101'
Global Const $STRUCT_MONK_RUNES_SUPERIOR_DIVINE_FAVOR			= '0310E8217D01'
Global Const $STRUCT_MONK_RUNES_SUPERIOR_HEALING_PRAYERS		= '030DE8217D01'
Global Const $STRUCT_MONK_RUNES_SUPERIOR_PROTECTION_PRAYERS		= '030FE8217D01'
Global Const $STRUCT_MONK_RUNES_SUPERIOR_SMITING_PRAYERS		= '030EE8217D01'
Global Const $STRUCT_NECROMANCER_INSIGNIAS_BLOODSTAINED			= '0A020824'
Global Const $STRUCT_NECROMANCER_INSIGNIAS_TORMENTORS			= 'EC010824'
Global Const $STRUCT_NECROMANCER_INSIGNIAS_BONELACE				= 'EE010824'
Global Const $STRUCT_NECROMANCER_MINION_MASTERS_INSIGNIA		= 'EF010824'
Global Const $STRUCT_NECROMANCER_INSIGNIAS_BLIGHTERS			= 'F0010824'
Global Const $STRUCT_NECROMANCER_INSIGNIAS_UNDERTAKERS			= 'ED010824'
Global Const $STRUCT_NECROMANCER_RUNES_MINOR_BLOOD_MAGIC		= '0104E821'
Global Const $STRUCT_NECROMANCER_RUNES_MINOR_CURSES				= '0107E821'
Global Const $STRUCT_NECROMANCER_RUNES_MINOR_DEATH_MAGIC		= '0105E821'
Global Const $STRUCT_NECROMANCER_RUNES_MINOR_SOUL_REAPING		= '0106E821'
Global Const $STRUCT_NECROMANCER_RUNES_MAJOR_BLOOD_MAGIC		= '0204E8216D01'
Global Const $STRUCT_NECROMANCER_RUNES_MAJOR_CURSES				= '0207E8216D01'
Global Const $STRUCT_NECROMANCER_RUNES_MAJOR_DEATH_MAGIC		= '0205E8216D01'
Global Const $STRUCT_NECROMANCER_RUNES_MAJOR_SOUL_REAPING		= '0206E8216D01'
Global Const $STRUCT_NECROMANCER_RUNES_SUPERIOR_BLOOD_MAGIC		= '0304E8217901'
Global Const $STRUCT_NECROMANCER_RUNES_SUPERIOR_CURSES			= '0307E8217901'
Global Const $STRUCT_NECROMANCER_RUNES_SUPERIOR_DEATH_MAGIC		= '0305E8217901'
Global Const $STRUCT_NECROMANCER_RUNES_SUPERIOR_SOUL_REAPING	= '0306E8217901'
Global Const $STRUCT_MESMER_INSIGNIAS_VIRTUOSOS					= 'E4010824'
Global Const $STRUCT_MESMER_INSIGNIAS_ARTIFICERS				= 'E2010824'
Global Const $STRUCT_MESMER_INSIGNIAS_PRODIGYS					= 'E3010824'
Global Const $STRUCT_MESMER_RUNES_MINOR_DOMINATION_MAGIC		= '0102E821'
Global Const $STRUCT_MESMER_RUNES_MINOR_FAST_CASTING			= '0100E821'
Global Const $STRUCT_MESMER_RUNES_MINOR_ILLUSION_MAGIC			= '0101E821'
Global Const $STRUCT_MESMER_RUNES_MINOR_INSPIRATION_MAGIC		= '0103E821'
Global Const $STRUCT_MESMER_RUNES_MAJOR_DOMINATION_MAGIC		= '0202E8216B01'
Global Const $STRUCT_MESMER_RUNES_MAJOR_FAST_CASTING			= '0200E8216B01'
Global Const $STRUCT_MESMER_RUNES_MAJOR_ILLUSION_MAGIC			= '0201E8216B01'
Global Const $STRUCT_MESMER_RUNES_MAJOR_INSPIRATION_MAGIC		= '0203E8216B01'
Global Const $STRUCT_MESMER_RUNES_SUPERIOR_DOMINATION_MAGIC		= '0302E8217701'
Global Const $STRUCT_MESMER_RUNES_SUPERIOR_FAST_CASTING			= '0300E8217701'
Global Const $STRUCT_MESMER_RUNES_SUPERIOR_ILLUSION_MAGIC		= '0301E8217701'
Global Const $STRUCT_MESMER_RUNES_SUPERIOR_INSPIRATION_MAGIC	= '0303E8217701'
Global Const $STRUCT_ELEMENTALIST_INSIGNIAS_HYDROMANCER			= 'F2010824'
Global Const $STRUCT_ELEMENTALIST_INSIGNIAS_GEOMANCER			= 'F3010824'
Global Const $STRUCT_ELEMENTALIST_INSIGNIAS_PYROMANCER			= 'F4010824'
Global Const $STRUCT_ELEMENTALIST_INSIGNIAS_AEROMANCER			= 'F5010824'
Global Const $STRUCT_ELEMENTALIST_INSIGNIAS_PRISMATIC			= 'F1010824'
Global Const $STRUCT_ELEMENTALIST_RUNES_MINOR_AIR_MAGIC			= '0108E821'
Global Const $STRUCT_ELEMENTALIST_RUNES_MINOR_EARTH_MAGIC		= '0109E821'
Global Const $STRUCT_ELEMENTALIST_RUNES_MINOR_ENERGY_STORAGE	= '010CE821'
Global Const $STRUCT_ELEMENTALIST_RUNES_MINOR_WATER_MAGIC		= '010BE821'
Global Const $STRUCT_ELEMENTALIST_RUNES_MINOR_FIRE_MAGIC		= '010AE821'
Global Const $STRUCT_ELEMENTALIST_RUNES_MAJOR_AIR_MAGIC			= '0208E8216F01'
Global Const $STRUCT_ELEMENTALIST_RUNES_MAJOR_EARTH_MAGIC		= '0209E8216F01'
Global Const $STRUCT_ELEMENTALIST_RUNES_MAJOR_ENERGY_STORAGE	= '020CE8216F01'
Global Const $STRUCT_ELEMENTALIST_RUNES_MAJOR_FIRE_MAGIC		= '020AE8216F01'
Global Const $STRUCT_ELEMENTALIST_RUNES_MAJOR_WATER_MAGIC		= '020BE8216F01'
Global Const $STRUCT_ELEMENTALIST_RUNES_SUPERIOR_AIR_MAGIC		= '0308E8217B01'
Global Const $STRUCT_ELEMENTALIST_RUNES_SUPERIOR_EARTH_MAGIC	= '0309E8217B01'
Global Const $STRUCT_ELEMENTALIST_RUNES_SUPERIOR_ENERGY_STORAGE	= '030CE8217B01'
Global Const $STRUCT_ELEMENTALIST_RUNES_SUPERIOR_FIRE_MAGIC		= '030AE8217B01'
Global Const $STRUCT_ELEMENTALIST_RUNES_SUPERIOR_WATER_MAGIC	= '030BE8217B01'
Global Const $STRUCT_ASSASSIN_INSIGNIAS_VANGUARDS				= 'DE010824'
Global Const $STRUCT_ASSASSIN_INSIGNIAS_INFILTRATORS			= 'DF010824'
Global Const $STRUCT_ASSASSIN_INSIGNIAS_SABOTEURS				= 'E0010824'
Global Const $STRUCT_ASSASSIN_INSIGNIAS_NIGHTSTALKERS			= 'E1010824'
Global Const $STRUCT_ASSASSIN_RUNES_MINOR_CRITICAL_STRIKES		= '0123E821'
Global Const $STRUCT_ASSASSIN_RUNES_MINOR_DAGGER_MASTERY		= '011DE821'
Global Const $STRUCT_ASSASSIN_RUNES_MINOR_DEADLY_ARTS			= '011EE821'
Global Const $STRUCT_ASSASSIN_RUNES_MINOR_SHADOW_ARTS			= '011FE821'
Global Const $STRUCT_ASSASSIN_RUNES_MAJOR_CRITICAL_STRIKES		= '0223E8217902'
Global Const $STRUCT_ASSASSIN_RUNES_MAJOR_DAGGER_MASTERY		= '021DE8217902'
Global Const $STRUCT_ASSASSIN_RUNES_MAJOR_DEADLY_ARTS			= '021EE8217902'
Global Const $STRUCT_ASSASSIN_RUNES_MAJOR_SHADOW_ARTS			= '021FE8217902'
Global Const $STRUCT_ASSASSIN_RUNES_SUPERIOR_CRITICAL_STRIKES	= '0323E8217B02'
Global Const $STRUCT_ASSASSIN_RUNES_SUPERIOR_DAGGER_MASTERY		= '031DE8217B02'
Global Const $STRUCT_ASSASSIN_RUNES_SUPERIOR_DEADLY_ARTS		= '031EE8217B02'
Global Const $STRUCT_ASSASSIN_RUNES_SUPERIOR_SHADOW_ARTS		= '031FE8217B02'
Global Const $STRUCT_RITUALIST_INSIGNIAS_SHAMANS				= '04020824'
Global Const $STRUCT_RITUALIST_GHOST_FORGE_INSIGNIA				= '05020824'
Global Const $STRUCT_RITUALIST_INSIGNIAS_MYSTICS				= '06020824'
Global Const $STRUCT_RITUALIST_RUNES_MINOR_CHANNELING_MAGIC		= '0122E821'
Global Const $STRUCT_RITUALIST_RUNES_MINOR_COMMUNING			= '0120E821'
Global Const $STRUCT_RITUALIST_RUNES_MINOR_RESTORATION_MAGIC	= '0121E821'
Global Const $STRUCT_RITUALIST_RUNES_MINOR_SPAWNING_POWER		= '0124E821'
Global Const $STRUCT_RITUALIST_RUNES_MAJOR_CHANNELING_MAGIC		= '0222E8217F02'
Global Const $STRUCT_RITUALIST_RUNES_MAJOR_COMMUNING			= '0220E8217F02'
Global Const $STRUCT_RITUALIST_RUNES_MAJOR_RESTORATION_MAGIC	= '0221E8217F02'
Global Const $STRUCT_RITUALIST_RUNES_MAJOR_SPAWNING_POWER		= '0224E8217F02'
Global Const $STRUCT_RITUALIST_RUNES_SUPERIOR_CHANNELING_MAGIC	= '0322E8218102'
Global Const $STRUCT_RITUALIST_RUNES_SUPERIOR_COMMUNING			= '0320E8218102'
Global Const $STRUCT_RITUALIST_RUNES_SUPERIOR_RESTORATION_MAGIC	= '0321E8218102'
Global Const $STRUCT_RITUALIST_RUNES_SUPERIOR_SPAWNING_POWER	= '0324E8218102'
Global Const $STRUCT_DERVISH_INSIGNIAS_WINDWALKER				= '02020824'
Global Const $STRUCT_DERVISH_INSIGNIAS_FORSAKEN					= '03020824'
Global Const $STRUCT_DERVISH_RUNES_MINOR_EARTH_PRAYERS			= '012BE821'
Global Const $STRUCT_DERVISH_RUNES_MINOR_MYSTICISM				= '012CE821'
Global Const $STRUCT_DERVISH_RUNES_MINOR_SCYTHE_MASTERY			= '0129E821'
Global Const $STRUCT_DERVISH_RUNES_MINOR_WIND_PRAYERS			= '012AE821'
Global Const $STRUCT_DERVISH_RUNES_MAJOR_EARTH_PRAYERS			= '022BE8210703'
Global Const $STRUCT_DERVISH_RUNES_MAJOR_MYSTICISM				= '022CE8210703'
Global Const $STRUCT_DERVISH_RUNES_MAJOR_SCYTHE_MASTERY			= '0229E8210703'
Global Const $STRUCT_DERVISH_RUNES_MAJOR_WIND_PRAYERS			= '022AE8210703'
Global Const $STRUCT_DERVISH_RUNES_SUPERIOR_EARTH_PRAYERS		= '032BE8210903'
Global Const $STRUCT_DERVISH_RUNES_SUPERIOR_MYSTICISM			= '032CE8210903'
Global Const $STRUCT_DERVISH_RUNES_SUPERIOR_SCYTHE_MASTERY		= '0329E8210903'
Global Const $STRUCT_DERVISH_RUNES_SUPERIOR_WIND_PRAYERS		= '032AE8210903'
Global Const $STRUCT_PARAGON_INSIGNIAS_CENTURIONS				= '07020824'
Global Const $STRUCT_PARAGON_RUNES_MINOR_COMMAND				= '0126E821'
Global Const $STRUCT_PARAGON_RUNES_MINOR_LEADERSHIP				= '0128E821'
Global Const $STRUCT_PARAGON_RUNES_MINOR_MOTIVATION				= '0127E821'
Global Const $STRUCT_PARAGON_RUNES_MINOR_SPEAR_MASTERY			= '0125E821'
Global Const $STRUCT_PARAGON_RUNES_MAJOR_COMMAND				= '0226E8210D03'
Global Const $STRUCT_PARAGON_RUNES_MAJOR_LEADERSHIP				= '0228E8210D03'
Global Const $STRUCT_PARAGON_RUNES_MAJOR_MOTIVATION				= '0227E8210D03'
Global Const $STRUCT_PARAGON_RUNES_MAJOR_SPEAR_MASTERY			= '0225E8210D03'
Global Const $STRUCT_PARAGON_RUNES_SUPERIOR_COMMAND				= '0326E8210F03'
Global Const $STRUCT_PARAGON_RUNES_SUPERIOR_LEADERSHIP			= '0328E8210F03'
Global Const $STRUCT_PARAGON_RUNES_SUPERIOR_MOTIVATION			= '0327E8210F03'
Global Const $STRUCT_PARAGON_RUNES_SUPERIOR_SPEAR_MASTERY		= '0325E8210F03'
Global Const $STRUCT_ALL_INSIGNIAS_SURVIVOR						= 'E6010824'
Global Const $STRUCT_ALL_INSIGNIAS_RADIANT						= 'E5010824'
Global Const $STRUCT_ALL_INSIGNIAS_STALWART						= 'E7010824'
Global Const $STRUCT_ALL_INSIGNIAS_BRAWLERS						= 'E8010824'
Global Const $STRUCT_ALL_INSIGNIAS_BLESSED						= 'E9010824'
Global Const $STRUCT_ALL_INSIGNIAS_HERALDS						= 'EA010824'
Global Const $STRUCT_ALL_INSIGNIAS_SENTRYS						= 'EB010824'
Global Const $STRUCT_ALL_RUNES_MINOR_VIGOR						= 'C202E827'
Global Const $STRUCT_ALL_RUNES_VITAE							= '000A4823'
Global Const $STRUCT_ALL_RUNES_ATTUNEMENT						= '0200D822'
Global Const $STRUCT_ALL_RUNES_MAJOR_VIGOR						= 'C202E927'
Global Const $STRUCT_ALL_RUNES_RECOVERY							= '07047827'
Global Const $STRUCT_ALL_RUNES_RESTORATION						= '00037827'
Global Const $STRUCT_ALL_RUNES_CLARITY							= '01087827'
Global Const $STRUCT_ALL_RUNES_PURITY							= '05067827'
Global Const $STRUCT_ALL_RUNES_SUPERIOR_VIGOR					= 'C202EA27'
#EndRegion Runes


#Region Struct Utils
; Insignias are present at index 0 of their armor salvageable item
; Runes are present at index 1 of their armor salvageable item
Global $valuable_runes_and_insignias_structs_array[]	= DefaultCreateValuableRunesAndInsigniasArray()
Global $valuable_mods_by_os_weapon_type					= DefaultCreateValuableModsByOSWeaponTypeMap()
Global $valuable_mods_by_weapon_type					= DefaultCreateValuableModsByOSWeaponTypeMap()
Global $perfect_mods_by_weapon_type						= CreatePerfectModsByOSWeaponTypeMap()
Global $valuable_inscriptions_array[]


;~ Creates an array of all valuable runes and insignias
Func DefaultCreateValuableRunesAndInsigniasArray()
	Local $valuableRunesAndInsigniasStructsArray[]	= [ _
		$STRUCT_WARRIOR_INSIGNIAS_SENTINELS, _
		_ ;$STRUCT_RANGER_INSIGNIAS_BEASTMASTERS, _
		_ ;$STRUCT_MONK_INSIGNIAS_ANCHORITES, _
		_ ;$STRUCT_MONK_RUNES_MINOR_DIVINE_FAVOR, _
		_ ;$STRUCT_NECROMANCER_INSIGNIAS_BLOODSTAINED, _
		$STRUCT_NECROMANCER_INSIGNIAS_TORMENTORS, _
		_ ;$STRUCT_NECROMANCER_RUNES_MINOR_SOUL_REAPING, _
		$STRUCT_NECROMANCER_RUNES_MAJOR_SOUL_REAPING, _
		$STRUCT_NECROMANCER_RUNES_SUPERIOR_SOUL_REAPING, _
		$STRUCT_NECROMANCER_RUNES_MINOR_CURSES, _
		_ ;$STRUCT_NECROMANCER_RUNES_SUPERIOR_DEATH_MAGIC, _
		$STRUCT_MESMER_INSIGNIAS_PRODIGYS, _
		$STRUCT_MESMER_RUNES_MINOR_FAST_CASTING, _
		$STRUCT_MESMER_RUNES_MINOR_INSPIRATION_MAGIC, _
		$STRUCT_MESMER_RUNES_MAJOR_FAST_CASTING, _
		$STRUCT_MESMER_RUNES_MAJOR_DOMINATION_MAGIC, _
		$STRUCT_MESMER_RUNES_SUPERIOR_DOMINATION_MAGIC, _
		_ ;$STRUCT_MESMER_RUNES_SUPERIOR_ILLUSION_MAGIC, _
		_ ;$STRUCT_ELEMENTALIST_RUNES_MINOR_ENERGY_STORAGE, _
		$STRUCT_ASSASSIN_INSIGNIAS_NIGHTSTALKERS, _
		_ ;$STRUCT_ASSASSIN_RUNES_MINOR_CRITICAL_STRIKES, _
		$STRUCT_RITUALIST_INSIGNIAS_SHAMANS, _
		$STRUCT_RITUALIST_RUNES_MINOR_COMMUNING, _
		_ ;$STRUCT_RITUALIST_RUNES_MINOR_SPAWNING_POWER, _
		$STRUCT_RITUALIST_RUNES_MINOR_RESTORATION_MAGIC, _
		$STRUCT_RITUALIST_RUNES_SUPERIOR_COMMUNING, _
		$STRUCT_RITUALIST_RUNES_SUPERIOR_SPAWNING_POWER, _
		$STRUCT_DERVISH_INSIGNIAS_WINDWALKER, _
		$STRUCT_DERVISH_RUNES_MINOR_MYSTICISM, _
		$STRUCT_DERVISH_RUNES_MINOR_SCYTHE_MASTERY, _
		_ ;$STRUCT_DERVISH_RUNES_SUPERIOR_EARTH_PRAYERS, _
		$STRUCT_PARAGON_INSIGNIAS_CENTURIONS, _
		$STRUCT_PARAGON_RUNES_MINOR_SPEAR_MASTERY, _
		_ ;$STRUCT_ALL_INSIGNIAS_SURVIVOR, _
		_ ;$STRUCT_ALL_INSIGNIAS_RADIANT, _
		_ ;$STRUCT_ALL_INSIGNIAS_BRAWLERS, _
		$STRUCT_ALL_INSIGNIAS_BLESSED, _
		_ ;$STRUCT_ALL_RUNES_VITAE, _
		_ ;$STRUCT_ALL_RUNES_CLARITY, _
		$STRUCT_ALL_RUNES_MINOR_VIGOR, _
		$STRUCT_ALL_RUNES_MAJOR_VIGOR, _
		$STRUCT_ALL_RUNES_SUPERIOR_VIGOR _
	]
	Return $valuableRunesAndInsigniasStructsArray
EndFunc


;~ Creates a map to use to find whether an OS (Old School) weapon has a valuable mod - this doesn't mean the weapon itself is valuable
Func DefaultCreateValuableModsByOSWeaponTypeMap()
	; Nothing worth it on OS shields and focii, and there are no OS scythes and spears
	Local Const $ShieldModsArray			= []
	Local Const $OffhandModsArray			= []
	Local Const $ScytheModsArray			= []
	Local Const $SpearModsArray				= []
	Local Const $WandModsArray				= [$STRUCT_MOD_OF_THE_NECROMANCER]
	Local Const $DaggerModsArray			= [$STRUCT_MOD_OF_THE_NECROMANCER, $STRUCT_MOD_OF_THE_RANGER]
	Local Const $StaffModsArray				= [ _
		$STRUCT_MOD_OF_THE_NECROMANCER, $STRUCT_MOD_OF_CHARRSLAYING, $STRUCT_MOD_OF_TROLLSLAYING, $STRUCT_MOD_OF_GIANT_SLAYING, $STRUCT_MOD_OF_DWARF_SLAYING, $STRUCT_MOD_OF_TENGU_SLAYING _
	]
	Local Const $BowModsArray				= [ _
		$STRUCT_MOD_OF_THE_NECROMANCER, $STRUCT_MOD_OF_THE_RANGER, _
		$STRUCT_MOD_OF_CHARRSLAYING, $STRUCT_MOD_OF_TROLLSLAYING, $STRUCT_MOD_OF_GIANT_SLAYING, $STRUCT_MOD_OF_DWARF_SLAYING, $STRUCT_MOD_OF_TENGU_SLAYING _
	]
	Local Const $AxeModsArray				= [ _
		$STRUCT_MOD_OF_THE_NECROMANCER, $STRUCT_MOD_OF_THE_RANGER, _
		$STRUCT_MOD_OF_CHARRSLAYING, $STRUCT_MOD_OF_TROLLSLAYING, $STRUCT_MOD_OF_GIANT_SLAYING, $STRUCT_MOD_OF_DWARF_SLAYING, $STRUCT_MOD_OF_TENGU_SLAYING _
	]
	Local Const $HammerModsArray			= [ _
		$STRUCT_MOD_OF_THE_NECROMANCER, $STRUCT_MOD_OF_THE_RANGER, _
		$STRUCT_MOD_OF_CHARRSLAYING, $STRUCT_MOD_OF_TROLLSLAYING, $STRUCT_MOD_OF_GIANT_SLAYING, $STRUCT_MOD_OF_DWARF_SLAYING, $STRUCT_MOD_OF_TENGU_SLAYING _
	]
	Local Const $SwordModsArray			= [ _
		$STRUCT_MOD_OF_THE_NECROMANCER, $STRUCT_MOD_OF_THE_RANGER, _
		$STRUCT_MOD_OF_CHARRSLAYING, $STRUCT_MOD_OF_TROLLSLAYING, $STRUCT_MOD_OF_GIANT_SLAYING, $STRUCT_MOD_OF_DWARF_SLAYING, $STRUCT_MOD_OF_TENGU_SLAYING _
	]
	; Redefining types here remove dependency on GWA2_ID - and we only execute this function once
	Local Const $IDTypeAxe					= 2
	Local Const $IDTypeBow					= 5
	Local Const $IDTypeOffhand				= 12
	Local Const $IDTypeHammer				= 15
	Local Const $IDTypeWand					= 22
	Local Const $IDTypeShield				= 24
	Local Const $IDTypeStaff				= 26
	Local Const $IDTypeSword				= 27
	Local Const $IDTypeDagger				= 32
	Local Const $IDTypeScythe				= 35
	Local Const $IDTypeSpear				= 36
	Local Const $AllWeaponsArray			= [$IDTypeShield, $IDTypeOffhand, $IDTypeWand, $IDTypeStaff, $IDTypeBow, $IDTypeAxe, $IDTypeHammer, $IDTypeSword, $IDTypeDagger, $IDTypeScythe, $IDTypeSpear]
	Local Const $AllWeaponsModsArray		= [$ShieldModsArray, $OffhandModsArray, $WandModsArray, $StaffModsArray, $BowModsArray, $AxeModsArray, $HammerModsArray, _
													$SwordModsArray, $DaggerModsArray, $ScytheModsArray, $SpearModsArray]
	Local $valuableModsByOSWeaponType[]		= MapFromArrays($AllWeaponsArray, $AllWeaponsModsArray)
	Return $valuableModsByOSWeaponType
EndFunc


;~ Creates a map to use to find whether a weapon (not Old School) has a valuable mod - this doesn't mean the weapon itself is valuable
Func DefaultCreateValuableModsByWeaponTypeMap()
	; Nothing worth on shields - maybe could keep +45^enchanted handles ....
	Local Const $ShieldModsArray	= []
	Local Const $OffhandModsArray	= [$STRUCT_INSCRIPTION_FORGET_ME_NOT, $STRUCT_MOD_HCT_20, $STRUCT_MOD_HSR_20]
	Local Const $WandModsArray		= [$STRUCT_INSCRIPTION_APTITUDE_NOT_ATTITUDE, $STRUCT_MOD_OF_THE_NECROMANCER]
	Local Const $StaffModsArray		= [$STRUCT_INSCRIPTION_APTITUDE_NOT_ATTITUDE, $STRUCT_MOD_OF_THE_NECROMANCER]
	Local Const $BowModsArray		= [$STRUCT_MOD_OF_THE_NECROMANCER, $STRUCT_MOD_OF_THE_RANGER]
	Local Const $AxeModsArray		= [$STRUCT_MOD_OF_THE_NECROMANCER, $STRUCT_MOD_OF_THE_RANGER]
	Local Const $HammerModsArray	= [$STRUCT_MOD_OF_THE_NECROMANCER, $STRUCT_MOD_OF_THE_RANGER]
	Local Const $SwordModsArray		= [$STRUCT_MOD_OF_THE_NECROMANCER, $STRUCT_MOD_OF_THE_RANGER]
	Local Const $DaggerModsArray	= [$STRUCT_MOD_OF_THE_NECROMANCER, $STRUCT_MOD_OF_THE_RANGER]
	Local Const $ScytheModsArray	= [ _
		$STRUCT_MOD_ZEALOUS, $STRUCT_MOD_OF_ENCHANTING, $STRUCT_MOD_SUNDERING, _
		$STRUCT_MOD_OF_THE_NECROMANCER, $STRUCT_MOD_OF_THE_RANGER _
	]
	Local Const $SpearModsArray		= [ _
		$STRUCT_MOD_OF_ENCHANTING, _
		$STRUCT_MOD_OF_THE_NECROMANCER, $STRUCT_MOD_OF_THE_RANGER _
	]
	; Redefining types here remove dependency on GWA2_ID - and we only execute this function once
	Local Const $IDTypeAxe					= 2
	Local Const $IDTypeBow					= 5
	Local Const $IDTypeOffhand				= 12
	Local Const $IDTypeHammer				= 15
	Local Const $IDTypeWand					= 22
	Local Const $IDTypeShield				= 24
	Local Const $IDTypeStaff				= 26
	Local Const $IDTypeSword				= 27
	Local Const $IDTypeDagger				= 32
	Local Const $IDTypeScythe				= 35
	Local Const $IDTypeSpear				= 36
	Local Const $AllWeaponsArray			= [$IDTypeShield, $IDTypeOffhand, $IDTypeWand, $IDTypeStaff, $IDTypeBow, $IDTypeAxe, $IDTypeHammer, $IDTypeSword, $IDTypeDagger, $IDTypeScythe, $IDTypeSpear]
	Local Const $AllWeaponsModsArray		= [$ShieldModsArray, $OffhandModsArray, $WandModsArray, $StaffModsArray, $BowModsArray, $AxeModsArray, $HammerModsArray, _
													$SwordModsArray, $DaggerModsArray, $ScytheModsArray, $SpearModsArray]
	Local Const $weaponModsByType[]			= MapFromArrays($AllWeaponsArray, $AllWeaponsModsArray)
	Return $weaponModsByType
EndFunc


;~ Creates a map to use to find whether an OS (Old School) weapon ITSELF has perfect mods or not
Func CreatePerfectModsByOSWeaponTypeMap()
	; For martial weapons, only one of those mods is enough to say the weapon is perfect
	; But for zealous strength and vampiric strength, we need to check that it's not the zealous/vampiric mod
	Local $martialWeapons = [ _
		$STRUCT_INSCRIPTION_STRENGTH_AND_HONOR, _
		$STRUCT_INSCRIPTION_GUIDED_BY_FATE, _
		$STRUCT_INSCRIPTION_DANCE_WITH_DEATH, _
		$STRUCT_INSCRIPTION_I_HAVE_THE_POWER, _
		$STRUCT_INHERENT_ZEALOUS_STRENGTH, _
		$STRUCT_INHERENT_VAMPIRIC_STRENGTH _
	]

	; Those are common to caster weapons and focii
	Local $casterAndFocus = [ _
		$STRUCT_INHERENT_FIRE_MAGIC_HCT, _
		$STRUCT_INHERENT_FIRE_MAGIC_HSR, _
		$STRUCT_INHERENT_WATER_MAGIC_HCT, _
		$STRUCT_INHERENT_WATER_MAGIC_HSR, _
		$STRUCT_INHERENT_AIR_MAGIC_HCT, _
		$STRUCT_INHERENT_AIR_MAGIC_HSR, _
		$STRUCT_INHERENT_EARTH_MAGIC_HCT, _
		$STRUCT_INHERENT_EARTH_MAGIC_HSR, _
		$STRUCT_INHERENT_ENERGY_STORAGE_HCT, _
		$STRUCT_INHERENT_ENERGY_STORAGE_HSR, _
		$STRUCT_INHERENT_SMITING_PRAYERS_HCT, _
		$STRUCT_INHERENT_SMITING_PRAYERS_HSR, _
		$STRUCT_INHERENT_DIVINE_FAVOR_HCT, _
		$STRUCT_INHERENT_DIVINE_FAVOR_HSR, _
		$STRUCT_INHERENT_HEALING_PRAYERS_HCT, _
		$STRUCT_INHERENT_HEALING_PRAYERS_HSR, _
		$STRUCT_INHERENT_PROTECTION_PRAYERS_HCT, _
		$STRUCT_INHERENT_PROTECTION_PRAYERS_HSR, _
		$STRUCT_INHERENT_CHANNELING_MAGIC_HCT, _
		$STRUCT_INHERENT_CHANNELING_MAGIC_HSR, _
		$STRUCT_INHERENT_RESTORATION_MAGIC_HCT, _
		$STRUCT_INHERENT_RESTORATION_MAGIC_HSR, _
		$STRUCT_INHERENT_COMMUNING_HCT, _
		$STRUCT_INHERENT_COMMUNING_HSR, _
		$STRUCT_INHERENT_SPAWNING_POWER_HCT, _
		$STRUCT_INHERENT_SPAWNING_POWER_HSR, _
		$STRUCT_INHERENT_ILLUSION_MAGIC_HCT, _
		$STRUCT_INHERENT_ILLUSION_MAGIC_HSR, _
		$STRUCT_INHERENT_DOMINATION_MAGIC_HCT, _
		$STRUCT_INHERENT_DOMINATION_MAGIC_HSR, _
		$STRUCT_INHERENT_INSPIRATION_MAGIC_HCT, _
		$STRUCT_INHERENT_INSPIRATION_MAGIC_HSR, _
		$STRUCT_INHERENT_DEATH_MAGIC_HCT, _
		$STRUCT_INHERENT_DEATH_MAGIC_HSR, _
		$STRUCT_INHERENT_BLOOD_MAGIC_HCT, _
		$STRUCT_INHERENT_BLOOD_MAGIC_HSR, _
		$STRUCT_INHERENT_SOUL_REAPING_HCT, _
		$STRUCT_INHERENT_SOUL_REAPING_HSR, _
		$STRUCT_INHERENT_CURSES_HCT, _
		$STRUCT_INHERENT_CURSES_HSR _
	]

	; Those are common to shield and focus - They might be less interesting on one or the other so maybe it will need to be splitted further
	Local $shieldAndFocus	= [ _
		$STRUCT_INSCRIPTION_NOT_THE_FACE, _
		$STRUCT_INSCRIPTION_LEAF_ON_THE_WIND, _
		$STRUCT_INSCRIPTION_LIKE_A_ROLLING_STONE, _
		$STRUCT_INSCRIPTION_SLEEP_NOW_IN_THE_FIRE, _
		$STRUCT_INSCRIPTION_RIDERS_ON_THE_STORM, _
		$STRUCT_INSCRIPTION_THROUGH_THICK_AND_THIN, _
		$STRUCT_INSCRIPTION_THE_RIDDLE_OF_STEEL, _
		$STRUCT_INSCRIPTION_SHELTERED_BY_FAITH, _
		$STRUCT_INSCRIPTION_RUN_FOR_YOUR_LIFE, _
		$STRUCT_INSCRIPTION_LUCK_OF_THE_DRAW, _
		$STRUCT_INHERENT_OF_ILLUSION_MAGIC, _
		$STRUCT_INHERENT_OF_DOMINATION_MAGIC, _
		$STRUCT_INHERENT_OF_INSPIRATION, _
		$STRUCT_INHERENT_OF_BLOOD_MAGIC, _
		$STRUCT_INHERENT_OF_DEATH_MAGIC, _
		$STRUCT_INHERENT_OF_SOUL_REAPING, _
		$STRUCT_INHERENT_OF_CURSE_MAGIC, _
		$STRUCT_INHERENT_OF_AIR_MAGIC, _
		$STRUCT_INHERENT_OF_EARTH_MAGIC, _
		$STRUCT_INHERENT_OF_FIRE_MAGIC, _
		$STRUCT_INHERENT_OF_WATER_MAGIC, _
		$STRUCT_INHERENT_OF_HEALING_PRAYERS, _
		$STRUCT_INHERENT_OF_SMITING_PRAYERS, _
		$STRUCT_INHERENT_OF_PROTECTION_PRAYERS, _
		$STRUCT_INHERENT_OF_DIVINE_FAVOR, _
		$STRUCT_INHERENT_OF_COMMUNING_MAGIC, _
		$STRUCT_INHERENT_OF_RESTORATION_MAGIC, _
		$STRUCT_INHERENT_OF_CHANNELING_MAGIC, _
		$STRUCT_INHERENT_OF_SPAWNING_MAGIC, _
		$STRUCT_INHERENT_ARMOR_VS_UNDEAD, _
		$STRUCT_INHERENT_ARMOR_VS_CHARR, _
		$STRUCT_INHERENT_ARMOR_VS_TROLLS, _
		$STRUCT_INHERENT_ARMOR_VS_PLANTS, _
		$STRUCT_INHERENT_ARMOR_VS_SKELETONS, _
		$STRUCT_INHERENT_ARMOR_VS_GIANTS, _
		$STRUCT_INHERENT_ARMOR_VS_DWARVES, _
		$STRUCT_INHERENT_ARMOR_VS_TENGU, _
		$STRUCT_INHERENT_ARMOR_VS_DEMONS, _
		$STRUCT_INHERENT_ARMOR_VS_DRAGONS, _
		$STRUCT_INHERENT_ARMOR_VS_OGRES, _
		$STRUCT_MOD_OF_DEVOTION, _
		$STRUCT_MOD_OF_ENDURANCE, _
		$STRUCT_MOD_30_HEALTH _
	]

	Local $casterWeapons = [ _
		$STRUCT_INSCRIPTION_HALE_AND_HEARTY, _
		$STRUCT_INSCRIPTION_HAVE_FAITH, _
		$STRUCT_INSCRIPTION_SEIZE_THE_DAY_1, _
		$STRUCT_INSCRIPTION_SEIZE_THE_DAY_2, _
		$STRUCT_INSCRIPTION_APTITUDE_NOT_ATTITUDE _
	]
	_ArrayAdd($casterWeapons, $casterAndFocus)

	Local $focus = [ _
		$STRUCT_INSCRIPTION_FORGET_ME_NOT, _
		$STRUCT_INSCRIPTION_HAIL_TO_THE_KING, _
		$STRUCT_INSCRIPTION_FAITH_IS_MY_SHIELD, _
		$STRUCT_INSCRIPTION_LIFE_IS_PAIN, _
		$STRUCT_INSCRIPTION_LIVE_FOR_TODAY_1, _
		$STRUCT_INSCRIPTION_LIVE_FOR_TODAY_2 _
	]
	_ArrayAdd($focus, $casterAndFocus)
	_ArrayAdd($focus, $shieldAndFocus)

	Local $shield = [ _
		$STRUCT_INSCRIPTION_I_CAN_SEE_CLEARLY_NOW, _
		$STRUCT_INSCRIPTION_SWIFT_AS_THE_WIND, _
		$STRUCT_INSCRIPTION_ONLY_THE_STRONG_SURVIVE _
	]
	_ArrayAdd($shield, $shieldAndFocus)

	; Empty because there are no OS (Old School) scythes and spears
	Local $scytheAndSpear			= []

	; Redefining types here remove dependency on GWA2_ID - and we only execute this function once
	Local Const $IDTypeAxe					= 2
	Local Const $IDTypeBow					= 5
	Local Const $IDTypeOffhand				= 12
	Local Const $IDTypeHammer				= 15
	Local Const $IDTypeWand					= 22
	Local Const $IDTypeShield				= 24
	Local Const $IDTypeStaff				= 26
	Local Const $IDTypeSword				= 27
	Local Const $IDTypeDagger				= 32
	Local Const $IDTypeScythe				= 35
	Local Const $IDTypeSpear				= 36
	Local Const $AllWeaponsArray			= [$IDTypeShield, $IDTypeOffhand, $IDTypeWand, $IDTypeStaff, $IDTypeBow, $IDTypeAxe, $IDTypeHammer, $IDTypeSword, $IDTypeDagger, $IDTypeScythe, $IDTypeSpear]
	Local Const $AllWeaponsModsArray			= [$shield, $focus, $casterWeapons, $casterWeapons, $martialWeapons, $martialWeapons, $martialWeapons, _
													$martialWeapons, $martialWeapons, $scytheAndSpear, $scytheAndSpear]
	Local Const $weaponModsByType[]			= MapFromArrays($AllWeaponsArray, $AllWeaponsModsArray)
	Return $weaponModsByType
EndFunc


;~ Replace valuable runes/insignias/inscriptions/mods default lists by the lists of elements selected in the GUI interface
Func RefreshValuableListsFromInterface()
	$valuable_runes_and_insignias_structs_array = CreateValuableRunesAndInsigniasArray()
	;$valuable_mods_by_os_weapon_type = Createvaluable_mods_by_os_weapon_typeMap()
	$valuable_mods_by_weapon_type = CreateValuableModsByWeaponTypeMap()
	$valuable_inscriptions_array = CreateValuableInscriptionsArray()
EndFunc


;~ Creates an array of all valuable runes and insignias based on selected elements in treeview
Func CreateValuableRunesAndInsigniasArray()
	Local $tickedRunesAndInsignias = GetLootOptionsTickedCheckboxes('Keep components.Armor upgrades')
	Local $valuableRunesAndInsigniasStructsArray[UBound($tickedRunesAndInsignias)]
	For $i = 0 To UBound($tickedRunesAndInsignias) - 1
		; removing leftmost string with dot 'Armor upgrades.'
		Local $varName = StringTrimLeft($tickedRunesAndInsignias[$i], 15)
		$varName = 'Struct_' & StringReplace(StringReplace($varName, '.', '_'), ' ', '_')
		$valuableRunesAndInsigniasStructsArray[$i] = Eval($varName)
	Next
	Return $valuableRunesAndInsigniasStructsArray
EndFunc


;~ TODO: finish this function
;~ Creates an array of all valuable OS (Old School without inscription) weapon mods based on selected elements in treeview
Func CreateValuableModsByOSWeaponTypeMap()
	Local $tickedMods = GetLootOptionsTickedCheckboxes('Keep components.Mods')
	Local $valuableModsByOSWeaponTypeMap[UBound($tickedMods)]
	For $tickedMod In $tickedMods
		Info($tickedMods)
	Next
	Return Null
EndFunc


;~ Creates an array of all valuable not OS (Old School) weapon mods based on selected elements in treeview
Func CreateValuableModsByWeaponTypeMap()
	Local Const $IDTypeAxe					= 2
	Local Const $IDTypeBow					= 5
	Local Const $IDTypeOffhand				= 12
	Local Const $IDTypeHammer				= 15
	Local Const $IDTypeWand					= 22
	Local Const $IDTypeShield				= 24
	Local Const $IDTypeStaff				= 26
	Local Const $IDTypeSword				= 27
	Local Const $IDTypeDagger				= 32
	Local Const $IDTypeScythe				= 35
	Local Const $IDTypeSpear				= 36
	Local Const $AllWeaponsArray = [$IDTypeShield, $IDTypeOffhand, $IDTypeWand, $IDTypeStaff, $IDTypeBow, $IDTypeAxe, $IDTypeHammer, $IDTypeSword, $IDTypeDagger, $IDTypeScythe, $IDTypeSpear]

	Local $prefixWeaponModRules[]
	Local $suffixWeaponModRules[]
	$prefixWeaponModRules['Axe']	= 'Axe.Prefix - Haft.'
	$prefixWeaponModRules['Bow']	= 'Bow.Prefix - String.'
	$prefixWeaponModRules['Dagger']	= 'Dagger.Prefix - Tang.'
	$prefixWeaponModRules['Hammer']	= 'Hammer.Prefix - Haft.'
	$prefixWeaponModRules['Scythe']	= 'Scythe.Prefix - Snathe.'
	$prefixWeaponModRules['Spear']	= 'Spear.Prefix - Head.'
	$prefixWeaponModRules['Staff']	= 'Staff.Prefix - Head.'
	$prefixWeaponModRules['Sword']	= 'Sword.Prefix - Hilt.'
	$suffixWeaponModRules['Axe']	= 'Axe.Suffix - Grip.'
	$suffixWeaponModRules['Bow']	= 'Bow.Suffix - Grip.'
	$suffixWeaponModRules['Dagger']	= 'Dagger.Suffix - Handle.'
	$suffixWeaponModRules['Focus']	= 'Focus.Suffix - Core.'
	$suffixWeaponModRules['Hammer']	= 'Hammer.Suffix - Grip.'
	$suffixWeaponModRules['Scythe']	= 'Scythe.Suffix - Grip.'
	$suffixWeaponModRules['Shield']	= 'Shield.Suffix - Handle.'
	$suffixWeaponModRules['Spear']	= 'Spear.Suffix - Grip.'
	$suffixWeaponModRules['Staff']	= 'Staff.Suffix - Wrapping.'
	$suffixWeaponModRules['Sword']	= 'Sword.Suffix - Pommel.'
	$suffixWeaponModRules['Wand']	= 'Wand.Suffix - Wrapping.'

	Local $weaponModsByType[]
	For $i = 0 To UBound($AllWeaponsArray) - 1
		Local $weaponType = $AllWeaponsArray[$i]
		Local $weaponName = $WEAPON_NAMES_FROM_TYPES[$weaponType]
		Local $tickedMods = GetLootOptionsTickedCheckboxes('Keep components.Mods.' & $weaponName)
		Local $count = UBound($tickedMods)
		Local $mods[$count]

		If $count = 0 Then
			$weaponModsByType[$weaponType] = $mods
			ContinueLoop
		EndIf

		Local $prefixRule = $prefixWeaponModRules[$weaponName]
		Local $suffixRule = $suffixWeaponModRules[$weaponName]
		For $j = 0 To $count - 1
			Local $varName = $tickedMods[$j]
			If $prefixRule <> Null Then $varName = StringReplace($varName, $prefixRule, 'STRUCT_MOD_')
			If $suffixRule <> Null Then $varName = StringReplace($varName, $suffixRule, 'STRUCT_MOD_')
			$varName = ModNameCleanupHelper($varName)
			$mods[$j] = Eval($varName)
		Next
		$weaponModsByType[$weaponType] = $mods
	Next

	Return $weaponModsByType
EndFunc


Func ModNameCleanupHelper($modName)
	; cleanup of all parentheses and contents in them
	$modName = StringRegExpReplace($modName, '\s*\(.*?\)', '')
	$modName = StringReplace($modName, ' ', '_')
	$modName = StringUpper($modName)
	Return $modName
EndFunc


;~ Creates an array of all valuable inscriptions based on selected elements in treeview
Func CreateValuableInscriptionsArray()
	Local $tickedInscriptions = GetLootOptionsTickedCheckboxes('Keep components.Inscriptions')
	Local $valuableInscriptionsArray[UBound($tickedInscriptions)]
	For $i = 0 To UBound($tickedInscriptions) - 1
		Local $varName = $tickedInscriptions[$i]
		$varName = StringReplace($varName, 'Inscriptions.All.', 'STRUCT_INSCRIPTION_')
		$varName = StringReplace($varName, 'Inscriptions.Weapon.All.', 'STRUCT_INSCRIPTION_')
		$varName = StringReplace($varName, 'Inscriptions.Weapon.Martial.', 'STRUCT_INSCRIPTION_')
		$varName = StringReplace($varName, 'Inscriptions.Weapon.Spellcasting.', 'STRUCT_INSCRIPTION_')
		$varName = StringReplace($varName, 'Inscriptions.Offhand.Focus.', 'STRUCT_INSCRIPTION_')
		$varName = StringReplace($varName, 'Inscriptions.Offhand.Focus and shield.', 'STRUCT_INSCRIPTION_')
		$varName = ModNameCleanupHelper($varName)
		$valuableInscriptionsArray[$i] = Eval($varName)
	Next
	Return $valuableInscriptionsArray
EndFunc
#EndRegion Struct Utils