#include <gwa3/core/CrashDiag.h>
#include <gwa3/core/Log.h>
#include <gwa3/core/HookMarker.h>

#include <Windows.h>
#include <DbgHelp.h>

#include <cstdio>
#include <cstring>

namespace GWA3::CrashDiag {

namespace {

static PVOID s_vectoredHandler = nullptr;
static LPTOP_LEVEL_EXCEPTION_FILTER s_prevUnhandledFilter = nullptr;
static volatile LONG s_loggedUnhandled = 0;
static volatile LONG s_loggedStackCookie = 0;
static volatile LONG s_loggedHardFault = 0;
static volatile LONG s_dumpSequence = 0;
static bool s_symbolsInitialized = false;

// === MAP file resolver for crash RVA-to-function resolution ===
// Parses the DLL's own .map file at init time so CrashDiag can log
// human-readable function names for our own code in crash stacks.
// The MAP file is generated by /MAP linker flag and placed next to the DLL.

struct MapEntry {
    uintptr_t rva;          // DLL-relative virtual address
    const char* name;        // Points into s_mapFileData buffer
};

static MapEntry* s_mapEntries = nullptr;
static unsigned s_mapEntryCount = 0;
static char* s_mapFileData = nullptr;    // Raw file content (names point into this)
static size_t s_mapFileSize = 0;
static uintptr_t s_dllBase = 0;          // Preferred load address from MAP header
static uintptr_t s_dllActualBase = 0;    // Actual loaded base (for relocation adjustment)
static size_t s_nameArenaUsed = 0;
static size_t s_nameArenaCap = 0;
static char* s_nameArena = nullptr;

// Parse the MAP file "Publics by Value" section and build s_mapEntries.
// Format: each line in the publics section is:
//   0001:XXXXXXXX       ?decorated_name@@...  1XXXXXXXX f  objfile.obj
// We extract the section:offset, convert to RVA, and store the mangled name.
static void LoadMapFile() {
    if (s_mapFileData) return;  // Already loaded

    // Find our own DLL path
    char dllPath[MAX_PATH] = {};
    HMODULE hSelf = nullptr;
    if (!GetModuleHandleExA(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS | GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
                             reinterpret_cast<LPCSTR>(&LoadMapFile), &hSelf)) {
        return;
    }
    if (!GetModuleFileNameA(hSelf, dllPath, MAX_PATH)) return;
    s_dllActualBase = reinterpret_cast<uintptr_t>(hSelf);

    // Build .map file path: same dir, same base name, .map extension
    char mapPath[MAX_PATH] = {};
    strncpy_s(mapPath, sizeof(mapPath), dllPath, _TRUNCATE);
    char* dot = strrchr(mapPath, '.');
    if (dot) {
        strncpy_s(dot, static_cast<size_t>(sizeof(mapPath) - (dot - mapPath)), ".map", _TRUNCATE);
    } else {
        strncat_s(mapPath, sizeof(mapPath), ".map", _TRUNCATE);
    }

    // Read the entire MAP file
    HANDLE hFile = CreateFileA(mapPath, GENERIC_READ, FILE_SHARE_READ, nullptr,
                               OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, nullptr);
    if (hFile == INVALID_HANDLE_VALUE) {
        GWA3::Log::Warn("CrashDiag: MAP file not found at %s", mapPath);
        return;
    }
    DWORD fileSize = GetFileSize(hFile, nullptr);
    if (fileSize == 0 || fileSize > 16 * 1024 * 1024) {
        CloseHandle(hFile);
        return;
    }
    s_mapFileSize = fileSize;
    s_mapFileData = static_cast<char*>(HeapAlloc(GetProcessHeap(), 0, fileSize + 1));
    if (!s_mapFileData) {
        CloseHandle(hFile);
        return;
    }
    DWORD bytesRead = 0;
    if (!ReadFile(hFile, s_mapFileData, fileSize, &bytesRead, nullptr) || bytesRead != fileSize) {
        HeapFree(GetProcessHeap(), 0, s_mapFileData);
        s_mapFileData = nullptr;
        CloseHandle(hFile);
        return;
    }
    s_mapFileData[fileSize] = '\0';
    CloseHandle(hFile);

    GWA3::Log::Info("CrashDiag: Loaded MAP file %s (%u bytes)", mapPath, bytesRead);

    // Parse preferred load address from header
    // Look for line like " preferred load address is 10000000"
    s_dllBase = 0x10000000;  // Default MSVC preferred base
    {
        const char* p = s_mapFileData;
        while (*p) {
            const char* lineStart = p;
            while (*p && *p != '\n') p++;
            size_t lineLen = static_cast<size_t>(p - lineStart);
            if (*p == '\n') p++;
            if (lineLen > 20 && lineLen < 256) {
                char lineBuf[256];
                memcpy(lineBuf, lineStart, lineLen);
                lineBuf[lineLen] = '\0';
                if (strstr(lineBuf, "preferred load address") || strstr(lineBuf, "Preferred load address")) {
                    const char* hex = strstr(lineBuf, "is ");
                    if (hex) {
                        hex += 3;
                        while (*hex == ' ') hex++;
                        s_dllBase = strtoul(hex, nullptr, 16);
                    }
                }
            }
        }
    }

    // Find "Publics by Value" section
    const char* p = strstr(s_mapFileData, "Publics by Value");
    if (!p) {
        GWA3::Log::Warn("CrashDiag: MAP file has no Publics by Value section");
        return;
    }
    // Skip the header line
    while (*p && *p != '\n') p++;
    if (*p == '\n') p++;

    // First pass: count entries
    unsigned entryCount = 0;
    {
        const char* scanP = p;
        while (*scanP) {
            while (*scanP == '\r' || *scanP == '\n') scanP++;
            if (*scanP == '\0') break;
            const char* lineEnd = scanP;
            while (*lineEnd && *lineEnd != '\n') lineEnd++;
            size_t lLen = static_cast<size_t>(lineEnd - scanP);
            if (lLen > 10 && lLen < 512) {
                char lineBuf[512];
                memcpy(lineBuf, scanP, lLen);
                lineBuf[lLen] = '\0';
                const char* lStart = lineBuf;
                while (*lStart == ' ' || *lStart == '\t') lStart++;
                if (lStart[0] >= '0' && lStart[0] <= '9' && lStart[4] == ':') {
                    entryCount++;
                }
            }
            scanP = lineEnd;
            if (*scanP == '\n') scanP++;
        }
    }

    if (entryCount == 0) {
        GWA3::Log::Warn("CrashDiag: MAP file has no public symbol entries");
        return;
    }

    s_mapEntries = static_cast<MapEntry*>(HeapAlloc(GetProcessHeap(), 0, entryCount * sizeof(MapEntry)));
    if (!s_mapEntries) return;
    s_mapEntryCount = 0;

    // Allocate name arena
    s_nameArenaCap = entryCount * 128;
    s_nameArena = static_cast<char*>(HeapAlloc(GetProcessHeap(), 0, s_nameArenaCap));
    if (!s_nameArena) return;
    s_nameArenaUsed = 0;

    // Second pass: parse entries
    while (*p && s_mapEntryCount < entryCount) {
        while (*p == '\r' || *p == '\n') p++;
        if (*p == '\0') break;
        const char* lineEnd = p;
        while (*lineEnd && *lineEnd != '\n') lineEnd++;
        size_t lLen = static_cast<size_t>(lineEnd - p);
        if (lLen <= 10 || lLen >= 512) {
            p = lineEnd;
            if (*p == '\n') p++;
            continue;
        }

        char lineBuf[512];
        memcpy(lineBuf, p, lLen);
        lineBuf[lLen] = '\0';
        p = lineEnd;
        if (*p == '\n') p++;

        // Parse: " 0001:XXXXXXXX  name  addr f obj.obj"
        const char* lStart = lineBuf;
        while (*lStart == ' ' || *lStart == '\t') lStart++;

        // Section:offset
        unsigned section = 0;
        unsigned sectionOffset = 0;
        if (sscanf(lStart, "%x:%x", &section, &sectionOffset) != 2) continue;
        if (section < 1 || section > 16) continue;

        // Parse all columns in one pass:
        //   col1: section:offset  (e.g. "0001:0001B760")
        //   col2: decorated name  (e.g. "?ReadPtr@TradeMgr@@...")
        //   col3: virtual address (e.g. "1001C760")
        //   col4: "f" or "i"
        //   col5: object file     (e.g. "TradeMgr.obj")
        // We compute RVA from the virtual address column (VA - preferredBase)
        // rather than from section:offset, because the section-to-RVA mapping
        // depends on the PE section layout and the simple formula
        // sectionOffset + section*0x1000 is wrong for section 2+ (.rdata,
        // .data, etc).  The VA column is always correct.
        const char* cursor = lStart;

        // Skip col1 (section:offset)
        while (*cursor && *cursor != ' ' && *cursor != '\t') cursor++;
        while (*cursor == ' ' || *cursor == '\t') cursor++;

        // col2: decorated name
        const char* nameStart = cursor;
        while (*cursor && *cursor != ' ' && *cursor != '\t') cursor++;
        size_t nameLen = static_cast<size_t>(cursor - nameStart);
        if (nameLen == 0) continue;

        // col3: virtual address (hex, at preferred load address)
        while (*cursor == ' ' || *cursor == '\t') cursor++;
        uintptr_t va = strtoul(cursor, nullptr, 16);
        uintptr_t rva = (va > s_dllBase) ? (va - s_dllBase) : 0;

        // Store the name in the arena
        if (s_nameArenaUsed + nameLen + 1 > s_nameArenaCap) continue;
        char* nameCopy = s_nameArena + s_nameArenaUsed;
        memcpy(nameCopy, nameStart, nameLen);
        nameCopy[nameLen] = '\0';
        s_nameArenaUsed += nameLen + 1;

        s_mapEntries[s_mapEntryCount].rva = rva;
        s_mapEntries[s_mapEntryCount].name = nameCopy;
        s_mapEntryCount++;
    }

    // Sort by RVA for binary search
    for (unsigned i = 1; i < s_mapEntryCount; ++i) {
        MapEntry key = s_mapEntries[i];
        unsigned j = i;
        while (j > 0 && s_mapEntries[j - 1].rva > key.rva) {
            s_mapEntries[j] = s_mapEntries[j - 1];
            --j;
        }
        s_mapEntries[j] = key;
    }

    GWA3::Log::Info("CrashDiag: MAP file loaded %u public symbols (preferred base=0x%08X, actual base=0x%08X)",
                    s_mapEntryCount, static_cast<unsigned>(s_dllBase), static_cast<unsigned>(s_dllActualBase));
}
// Look up a DLL-relative offset in the MAP file entries.
// Returns the function name or nullptr.
static const char* LookupRvaInMapEntries(uintptr_t rva) {
    if (!s_mapEntries || s_mapEntryCount == 0) return nullptr;

    // Binary search for the largest RVA <= the target
    unsigned lo = 0;
    unsigned hi = s_mapEntryCount;
    while (lo < hi) {
        unsigned mid = lo + (hi - lo) / 2;
        if (s_mapEntries[mid].rva <= rva) {
            lo = mid + 1;
        } else {
            hi = mid;
        }
    }
    // lo is now one past the last entry with rva <= target
    if (lo == 0) return nullptr;

    // Sanity check: if the nearest symbol is more than 64KB away,
    // the target is likely in a data section (.rdata, .data) where
    // there are no function symbols. Returning a distant .text symbol
    // would produce a misleading name with a huge offset.
    const uintptr_t kMaxMatchDistance = 0x10000;  // 64KB
    if (rva - s_mapEntries[lo - 1].rva > kMaxMatchDistance) return nullptr;
    return s_mapEntries[lo - 1].name;
}

bool ShouldLogStackCookie(DWORD code) {
    return code == static_cast<DWORD>(STATUS_STACK_BUFFER_OVERRUN) ||
           code == EXCEPTION_STACK_OVERFLOW ||
           code == EXCEPTION_ILLEGAL_INSTRUCTION ||
           code == EXCEPTION_PRIV_INSTRUCTION;
}

// "Hard fault" exceptions ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Â likely to be the actual process-killing
// crash rather than something GW's internal __try/__except is
// expected to catch. We gate these to once-per-session because first-
// chance AVs can be frequent in normal operation (stack probes,
// structured handling, etc.); logging every one would drown the log.
bool IsHardFault(DWORD code) {
    return code == EXCEPTION_ACCESS_VIOLATION ||
           code == EXCEPTION_INT_DIVIDE_BY_ZERO ||
           code == EXCEPTION_ARRAY_BOUNDS_EXCEEDED ||
           code == EXCEPTION_DATATYPE_MISALIGNMENT ||
           code == EXCEPTION_IN_PAGE_ERROR ||
           code == EXCEPTION_NONCONTINUABLE_EXCEPTION;
}

void BuildOutputPath(const char* extension, char* outPath, size_t outPathSize) {
    if (!outPath || outPathSize == 0) return;
    outPath[0] = '\0';

    char modulePath[MAX_PATH] = {};
    HMODULE hSelf = nullptr;
    if (!GetModuleHandleExA(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS | GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
                            reinterpret_cast<LPCSTR>(&BuildOutputPath), &hSelf)) {
        return;
    }
    if (!GetModuleFileNameA(hSelf, modulePath, MAX_PATH)) {
        return;
    }

    char* slash = strrchr(modulePath, '\\');
    if (!slash) return;
    *slash = '\0';

    char dumpDir[MAX_PATH] = {};
    snprintf(dumpDir, sizeof(dumpDir), "%s\\crashdumps", modulePath);
    CreateDirectoryA(dumpDir, nullptr);

    SYSTEMTIME st = {};
    GetLocalTime(&st);
    const LONG seq = InterlockedIncrement(&s_dumpSequence);
    snprintf(outPath, outPathSize,
             "%s\\gwa3_crash_%04u%02u%02u_%02u%02u%02u_pid%u_tid%u_%ld.%s",
             dumpDir,
             st.wYear, st.wMonth, st.wDay,
             st.wHour, st.wMinute, st.wSecond,
             GetCurrentProcessId(),
             GetCurrentThreadId(),
             seq,
             extension ? extension : "log");
}

void ResolveModuleForAddress(const void* addr, char* modulePath, size_t modulePathSize,
                             uintptr_t* outBase, uintptr_t* outOffset,
                             const char** outFuncName) {
    if (modulePath && modulePathSize > 0) {
        modulePath[0] = '\0';
    }
    if (outBase) *outBase = 0;
    if (outOffset) *outOffset = 0;
    if (outFuncName) *outFuncName = nullptr;
    if (!addr) return;

    HMODULE hModule = nullptr;
    if (!GetModuleHandleExA(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS | GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
                            reinterpret_cast<LPCSTR>(addr), &hModule)) {
        return;
    }

    if (modulePath && modulePathSize > 0) {
        GetModuleFileNameA(hModule, modulePath, static_cast<DWORD>(modulePathSize));
    }

    if (outBase) {
        *outBase = reinterpret_cast<uintptr_t>(hModule);
    }
    if (outOffset) {
        const uintptr_t base = reinterpret_cast<uintptr_t>(hModule);
        *outOffset = reinterpret_cast<uintptr_t>(addr) - base;
    }

    // If the address is in our own DLL and we have MAP entries, resolve the function name
    if (outFuncName && hModule == reinterpret_cast<HMODULE>(s_dllActualBase) && s_mapEntries) {
        const uintptr_t rva = reinterpret_cast<uintptr_t>(addr) - s_dllActualBase;
        *outFuncName = LookupRvaInMapEntries(rva);
    }
}

void WriteMiniDump(const char* tag, EXCEPTION_POINTERS* exceptionPointers) {
    char dumpPath[MAX_PATH] = {};
    BuildOutputPath("dmp", dumpPath, sizeof(dumpPath));
    if (!dumpPath[0]) return;

    HANDLE file = CreateFileA(dumpPath, GENERIC_WRITE, FILE_SHARE_READ, nullptr,
                              CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, nullptr);
    if (file == INVALID_HANDLE_VALUE) {
        GWA3::Log::Error("CrashDiag: CreateFile failed for dump %s err=%u", dumpPath, GetLastError());
        return;
    }

    const auto dumpType = static_cast<MINIDUMP_TYPE>(
        MiniDumpNormal |
        MiniDumpWithThreadInfo |
        MiniDumpWithIndirectlyReferencedMemory |
        MiniDumpScanMemory
    );
    MINIDUMP_EXCEPTION_INFORMATION mei = {};
    MINIDUMP_EXCEPTION_INFORMATION* meiPtr = nullptr;
    if (exceptionPointers) {
        mei.ThreadId = GetCurrentThreadId();
        mei.ExceptionPointers = exceptionPointers;
        mei.ClientPointers = FALSE;
        meiPtr = &mei;
    }
    const BOOL ok = MiniDumpWriteDump(GetCurrentProcess(),
                                      GetCurrentProcessId(),
                                      file,
                                      dumpType,
                                      meiPtr,
                                      nullptr,
                                      nullptr);
    const DWORD err = ok ? ERROR_SUCCESS : GetLastError();
    CloseHandle(file);

    if (ok) {
        GWA3::Log::Error("CrashDiag: %s minidump written to %s", tag ? tag : "exception", dumpPath);
    } else {
        GWA3::Log::Error("CrashDiag: MiniDumpWriteDump failed for %s err=%u", dumpPath, err);
    }
}

bool EnsureSymbols() {
    if (s_symbolsInitialized) {
        return true;
    }

    SymSetOptions(SYMOPT_DEFERRED_LOADS | SYMOPT_LOAD_LINES | SYMOPT_UNDNAME);
    if (!SymInitialize(GetCurrentProcess(), nullptr, TRUE)) {
        GWA3::Log::Error("CrashDiag: SymInitialize failed err=%u", GetLastError());
        return false;
    }

    s_symbolsInitialized = true;
    return true;
}

void LogStackTrace(const char* tag, const CONTEXT* sourceCtx) {
#if defined(_M_IX86)
    if (!sourceCtx || !EnsureSymbols()) {
        return;
    }

    CONTEXT ctx = *sourceCtx;
    STACKFRAME64 frame = {};
    frame.AddrPC.Mode = AddrModeFlat;
    frame.AddrPC.Offset = ctx.Eip;
    frame.AddrFrame.Mode = AddrModeFlat;
    frame.AddrFrame.Offset = ctx.Ebp;
    frame.AddrStack.Mode = AddrModeFlat;
    frame.AddrStack.Offset = ctx.Esp;

    HANDLE process = GetCurrentProcess();
    HANDLE thread = GetCurrentThread();
    constexpr unsigned kMaxFrames = 24;

    for (unsigned i = 0; i < kMaxFrames; ++i) {
        const DWORD64 addr = frame.AddrPC.Offset;
        if (addr == 0) {
            break;
        }

        char symbolBuffer[sizeof(SYMBOL_INFO) + MAX_SYM_NAME] = {};
        auto* symbol = reinterpret_cast<SYMBOL_INFO*>(symbolBuffer);
        symbol->SizeOfStruct = sizeof(SYMBOL_INFO);
        symbol->MaxNameLen = MAX_SYM_NAME;
        DWORD64 displacement = 0;

        char modulePath[MAX_PATH] = {};
        uintptr_t moduleBase = 0;
        uintptr_t moduleOffset = 0;
        const char* funcName = nullptr;
        ResolveModuleForAddress(reinterpret_cast<const void*>(static_cast<uintptr_t>(addr)),
                                modulePath, sizeof(modulePath),
                                &moduleBase, &moduleOffset, &funcName);

        IMAGEHLP_LINE64 line = {};
        line.SizeOfStruct = sizeof(line);
        DWORD lineDisplacement = 0;
        const BOOL haveSymbol = SymFromAddr(process, addr, &displacement, symbol);
        const BOOL haveLine = SymGetLineFromAddr64(process, addr, &lineDisplacement, &line);

        if (haveSymbol && haveLine) {
            GWA3::Log::Error("CrashDiag: %s stack[%u] 0x%08X %s +0x%X [%s:%lu]",
                             tag ? tag : "exception",
                             i,
                             static_cast<unsigned>(addr),
                             symbol->Name,
                             static_cast<unsigned>(displacement),
                             line.FileName,
                             static_cast<unsigned long>(line.LineNumber));
        } else if (haveSymbol) {
            GWA3::Log::Error("CrashDiag: %s stack[%u] 0x%08X %s +0x%X [%s+0x%08X]",
                             tag ? tag : "exception",
                             i,
                             static_cast<unsigned>(addr),
                             symbol->Name,
                             static_cast<unsigned>(displacement),
                             modulePath[0] ? modulePath : "<unknown>",
                             static_cast<unsigned>(moduleOffset));
        } else if (funcName) {
            // No PDB symbol, but we have MAP file resolution for our own DLL
            GWA3::Log::Error("CrashDiag: %s stack[%u] 0x%08X %s+0x%X [%s+0x%08X]",
                             tag ? tag : "exception",
                             i,
                             static_cast<unsigned>(addr),
                             funcName,
                             static_cast<unsigned>(moduleOffset),
                             modulePath[0] ? modulePath : "<unknown>",
                             static_cast<unsigned>(moduleOffset));
        } else {
            GWA3::Log::Error("CrashDiag: %s stack[%u] 0x%08X [%s+0x%08X]",
                             tag ? tag : "exception",
                             i,
                             static_cast<unsigned>(addr),
                             modulePath[0] ? modulePath : "<unknown>",
                             static_cast<unsigned>(moduleOffset));
        }

        if (!StackWalk64(IMAGE_FILE_MACHINE_I386,
                         process,
                         thread,
                         &frame,
                         &ctx,
                         nullptr,
                         SymFunctionTableAccess64,
                         SymGetModuleBase64,
                         nullptr)) {
            break;
        }
    }
#endif
}

void LogExceptionContext(const char* tag, EXCEPTION_POINTERS* ep) {
    if (!ep || !ep->ExceptionRecord) return;

    const EXCEPTION_RECORD* rec = ep->ExceptionRecord;
    const CONTEXT* ctx = ep->ContextRecord;

    char faultModule[MAX_PATH] = {};
    uintptr_t faultBase = 0;
    uintptr_t faultOffset = 0;
    const char* faultFunc = nullptr;
    ResolveModuleForAddress(rec->ExceptionAddress, faultModule, sizeof(faultModule), &faultBase, &faultOffset, &faultFunc);

    if (faultFunc) {
        GWA3::Log::Error("CrashDiag: %s code=0x%08X flags=0x%08X addr=0x%08X %s+0x%X [%s+0x%08X] tid=%u",
                         tag ? tag : "exception",
                         rec->ExceptionCode,
                         rec->ExceptionFlags,
                         static_cast<unsigned>(reinterpret_cast<uintptr_t>(rec->ExceptionAddress)),
                         faultFunc,
                         static_cast<unsigned>(faultOffset),
                         faultModule[0] ? faultModule : "<unknown>",
                         static_cast<unsigned>(faultOffset),
                         GetCurrentThreadId());
    } else {
        GWA3::Log::Error("CrashDiag: %s code=0x%08X flags=0x%08X addr=0x%08X [%s+0x%08X] tid=%u",
                         tag ? tag : "exception",
                         rec->ExceptionCode,
                         rec->ExceptionFlags,
                         static_cast<unsigned>(reinterpret_cast<uintptr_t>(rec->ExceptionAddress)),
                         faultModule[0] ? faultModule : "<unknown>",
                         static_cast<unsigned>(faultOffset),
                         GetCurrentThreadId());
    }

    if (rec->NumberParameters > 0) {
        char paramsLine[512] = {};
        size_t written = snprintf(paramsLine, sizeof(paramsLine),
                                  "CrashDiag: %s params[%lu]",
                                  tag ? tag : "exception",
                                  static_cast<unsigned long>(rec->NumberParameters));
        for (ULONG i = 0; i < rec->NumberParameters && i < EXCEPTION_MAXIMUM_PARAMETERS; ++i) {
            if (written >= sizeof(paramsLine)) break;
            written += snprintf(paramsLine + written,
                                sizeof(paramsLine) - written,
                                " p%lu=0x%08X",
                                static_cast<unsigned long>(i),
                                static_cast<unsigned>(rec->ExceptionInformation[i]));
        }
        GWA3::Log::Error("%s", paramsLine);
    }

#if defined(_M_IX86)
    if (ctx) {
        char ipModule[MAX_PATH] = {};
        uintptr_t ipBase = 0;
        uintptr_t ipOffset = 0;
        const char* ipFunc = nullptr;
        ResolveModuleForAddress(reinterpret_cast<const void*>(ctx->Eip), ipModule, sizeof(ipModule), &ipBase, &ipOffset, &ipFunc);
        GWA3::Log::Error("CrashDiag: %s regs EIP=0x%08X ESP=0x%08X EBP=0x%08X EAX=0x%08X EBX=0x%08X ECX=0x%08X EDX=0x%08X ESI=0x%08X EDI=0x%08X",
                         tag ? tag : "exception",
                         static_cast<unsigned>(ctx->Eip),
                         static_cast<unsigned>(ctx->Esp),
                         static_cast<unsigned>(ctx->Ebp),
                         static_cast<unsigned>(ctx->Eax),
                         static_cast<unsigned>(ctx->Ebx),
                         static_cast<unsigned>(ctx->Ecx),
                         static_cast<unsigned>(ctx->Edx),
                         static_cast<unsigned>(ctx->Esi),
                         static_cast<unsigned>(ctx->Edi));
        if (ipFunc) {
            GWA3::Log::Error("CrashDiag: %s control EFlags=0x%08X %s+0x%X [%s+0x%08X]",
                             tag ? tag : "exception",
                             static_cast<unsigned>(ctx->EFlags),
                             ipFunc,
                             static_cast<unsigned>(ipOffset),
                             ipModule[0] ? ipModule : "<unknown>",
                             static_cast<unsigned>(ipOffset));
        } else {
            GWA3::Log::Error("CrashDiag: %s control EFlags=0x%08X [%s+0x%08X]",
                             tag ? tag : "exception",
                             static_cast<unsigned>(ctx->EFlags),
                             ipModule[0] ? ipModule : "<unknown>",
                             static_cast<unsigned>(ipOffset));
        }
        LogStackTrace(tag, ctx);
    }
#endif
}

LONG CALLBACK VectoredExceptionHandler(EXCEPTION_POINTERS* ep) {
    if (!ep || !ep->ExceptionRecord) {
        return EXCEPTION_CONTINUE_SEARCH;
    }

    const DWORD code = ep->ExceptionRecord->ExceptionCode;

    // Stack cookie / stack overflow: fatal, no SEH recovery possible.
    // Log context but do NOT write minidumps from VEH (see below).
    if (ShouldLogStackCookie(code)) {
        __try { HookMarker::DumpOnCrash(); } __except(EXCEPTION_EXECUTE_HANDLER) { GWA3::Log::Error("CrashDiag: DumpOnCrash itself crashed in VEH-cookie"); }
        LogExceptionContext("VEH-cookie", ep);
        return EXCEPTION_CONTINUE_SEARCH;
    }

    // Hard faults: log every occurrence.  Recurring SEH-caught crashes
    // (e.g. TradeMgr::ReadPtr race conditions on the bridge thread) are
    // invisible if we only log the first one.  We do NOT call
    // WriteMiniDump from VEH because MiniDumpWriteDump suspends all
    // threads and modifies the exception context, which disrupts the
    // SEH unwind chain and prevents our per-builder __try/__except
    // handlers (GameSnapshot::TryWriteMerchantJson etc.) from firing.
    // Minidumps are written from the UEF path instead, where the
    // process is already terminating and SEH chain integrity no
    // longer matters.
    if (IsHardFault(code)) {
        __try { HookMarker::DumpOnCrash(); } __except(EXCEPTION_EXECUTE_HANDLER) { GWA3::Log::Error("CrashDiag: DumpOnCrash itself crashed in VEH-hard"); }
        LogExceptionContext("VEH-hard", ep);
        return EXCEPTION_CONTINUE_SEARCH;
    }

    return EXCEPTION_CONTINUE_SEARCH;
}

LONG WINAPI UnhandledExceptionFilterThunk(EXCEPTION_POINTERS* ep) {
    if (InterlockedCompareExchange(&s_loggedUnhandled, 1, 0) == 0) {
        __try { HookMarker::DumpOnCrash(); } __except(EXCEPTION_EXECUTE_HANDLER) { GWA3::Log::Error("CrashDiag: DumpOnCrash itself crashed in UEF"); }
        LogExceptionContext("UEF", ep);
        WriteMiniDump("uef", ep);
    }

    if (s_prevUnhandledFilter) {
        return s_prevUnhandledFilter(ep);
    }
    return EXCEPTION_CONTINUE_SEARCH;
}

} // namespace

bool Initialize() {
    if (s_vectoredHandler) {
        return true;
    }

    s_loggedUnhandled = 0;
    s_loggedStackCookie = 0;
    s_loggedHardFault = 0;
    s_vectoredHandler = AddVectoredExceptionHandler(1, &VectoredExceptionHandler);
    s_prevUnhandledFilter = SetUnhandledExceptionFilter(&UnhandledExceptionFilterThunk);

    if (!s_vectoredHandler) {
        GWA3::Log::Error("CrashDiag: AddVectoredExceptionHandler failed err=%u", GetLastError());
        return false;
    }

    LoadMapFile();

    GWA3::Log::Info("CrashDiag: Installed VEH and unhandled exception filter");
    return true;
}

void CaptureProcessState(const char* tag) {
    GWA3::Log::Error("CrashDiag: capture requested tag=%s tid=%u",
                     tag ? tag : "manual",
                     GetCurrentThreadId());
    __try { HookMarker::DumpOnCrash(); } __except(EXCEPTION_EXECUTE_HANDLER) { GWA3::Log::Error("CrashDiag: DumpOnCrash itself crashed in capture"); }
    WriteMiniDump(tag ? tag : "manual", nullptr);
}

void Shutdown() {
    if (s_vectoredHandler) {
        RemoveVectoredExceptionHandler(s_vectoredHandler);
        s_vectoredHandler = nullptr;
    }
    if (s_symbolsInitialized) {
        SymCleanup(GetCurrentProcess());
        s_symbolsInitialized = false;
    }
    SetUnhandledExceptionFilter(s_prevUnhandledFilter);
    s_prevUnhandledFilter = nullptr;

    // Free MAP file data and name arena
    if (s_mapEntries) {
        HeapFree(GetProcessHeap(), 0, s_mapEntries);
        s_mapEntries = nullptr;
    }
    s_mapEntryCount = 0;
    if (s_mapFileData) {
        HeapFree(GetProcessHeap(), 0, s_mapFileData);
        s_mapFileData = nullptr;
    }
    s_mapFileSize = 0;
    if (s_nameArena) {
        HeapFree(GetProcessHeap(), 0, s_nameArena);
        s_nameArena = nullptr;
    }
    s_nameArenaUsed = 0;
    s_nameArenaCap = 0;
}

const char* ResolveRvaToFunctionName(uintptr_t rva) {
    return LookupRvaInMapEntries(rva);
}

unsigned GetMapEntryCount() {
    return s_mapEntryCount;
}

} // namespace GWA3::CrashDiag



